### ISSUE TITLE
Light weight packages

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#1]
What do you think which light weight packages we need? What core tasks should these focus on?

**Comment by strengejacke** [comment]
- [] model metrics, like R2, ICC...
- [] model information, like terms/predictors, model frame...
- [] ?

**Comment by DominiqueMakowski** [comment]
IMO a possible structure could be, hierarchically (from the lower level to the top):

#### Core (i,.e., with a less deps as possible)

- Model information (accessors functions to get inside (insights?) models and access the internals; model info (variables, formulas, model frame, random effects, their structure and so on...)
- bayestestR: helpers computing things from posterior distributions
- ...

#### Middle level (that use the core packages)

- Computation Model "performance" metrics (R2, ICC, CoD, AIC, BIC and whatnot)
- ...

#### High Level (for non-experts/beginners that one full-baked solutions to solve their problems and that one to experience the power of R)

- Reporting
- Plotting
- ...

**Comment by strengejacke** [comment]
I think we can close this, we have a pretty clear roadmap, or not?

**Comment by DominiqueMakowski** [comment]
Yup, just have to follow it now haha
