### ISSUE TITLE
README action broken?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#100]
Since last update https://github.com/easystats/easystats/runs/1726721266 with a weird error

Quitting from lines 381-559 (README.Rmd) 
Error: Error: Assigned data `rev(...)` must be compatible with existing data.
✖ Existing data has 19 rows.
✖ Assigned data has 18 rows.
ℹ Only vectors of size 1 are recycled.

**Comment by strengejacke** [comment]
Looks like you have to add the new blog post. Since we don't include the blog posts in the plots anymore, we could comment out that code.

**Comment by DominiqueMakowski** [comment]
Ah yes right!

**Comment by DominiqueMakowski** [comment]
it didn't show up on rbloggers right? I wonder whether it's because they have an automated system to not publish "duplicates" (to avoid people just bumping the date to keep a post up) or something, or whether it was on our side (though aside from the double posting, everything looked alright 🤔)

**Comment by strengejacke** [comment]
yeah, not sure. We can try with another blog post the next days or week.

**Comment by IndrajeetPatil** [comment]
It's working again.

**Comment by strengejacke** [comment]
Yep, fixed in https://github.com/easystats/easystats/commit/85d783847cebacf5e43b376cea359284218d9c39
