### ISSUE TITLE
getting code coverage as close to 100% as possible

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#101]
This will be key in stabilizing the API across packages and stop us from making unwanted breaking changes.

Also, we should have a badge on the `README` to showcase the code coverage.

Progress tracker (check if anywhere above 90%):

- [ ] insight 
- [ ] modelbased
- [ ] bayestestR
- [x] effectsize
- [ ] parameters
- [ ] performance
- [ ] correlation
- [ ] report
- [ ] see
- [ ] datawizard
- [ ] easystats

**Comment by DominiqueMakowski** [comment]
We dropped the badge because we were ashamed 🤭

But I trust SuperIndra to get us out of this testing misery!

**Comment by strengejacke** [comment]
I guess that in many cases we need to run these checks only conditionally (for the Dev version, i.e. version number is x.y.z.1 or similar), because we're reaching the limits of allowed check time on CRAN for most packages.

**Comment by IndrajeetPatil** [comment]
But even if the tests are run conditionally (e.g., only on CI platforms, this will still compute the code coverage for all conditional tests). I run almost none of my tests for `ggstatsplot` on `CRAN`, but my code coverage on `README` is 100% 😅 
Because I run the tests on all CIs and compute code coverage that way.

**Comment by strengejacke** [comment]
Yes, yes, that's what I wanted to say. :-)

**Comment by IndrajeetPatil** [comment]
I think `correlation` is going to win the race 😄 

<img width="921" alt="Screenshot 2021-02-07 at 18 57 19" src="https://user-images.githubusercontent.com/11330453/107155037-71b9ee00-6976-11eb-8fdd-2225ebe8cb8f.png">

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/kwcRp24Wz4lZm/giphy.gif)

**Comment by strengejacke** [comment]
So why do I always get this page?

![image](https://user-images.githubusercontent.com/26301769/107672391-1ef17680-6c95-11eb-8385-94576ae452e2.png)

Codecov is pretty useless then.

**Comment by IndrajeetPatil** [comment]
You need to log in to `codecov` via `GitHub`, then you wouldn't get this error.

**Comment by strengejacke** [comment]
Can someone explain why codecoverage dropped to 0%? https://github.com/easystats/insight 😆 
If code-cov it not really reliable, I probably remove that action again...

**Comment by IndrajeetPatil** [comment]
I have added `codecov.yml`, which should fix this. We will see after the next commit if it is fixed.

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil can ya halp me fixing the tests and coverage for bayestestR 🙏

**Comment by DominiqueMakowski** [comment]
oh no I feel like you took that personally! It's true that afaik we are pretty lazy on that front, and it did happen that I myself 
 for instance commented out some tests that were failing -  instead of properly fixing - But it doesn't mean that we think it's unimportant, on the contrary! by all means, keep this global tracker open and help us be better software engineers... we do appreciate your nudges  :)

**Comment by strengejacke** [comment]
snapshot tests didn't work on my machine resp. I couldn't get them updated, so I prefer adding "real" tests instead. Same for code-cov, which failed for some reason, and if it does, this "hides" that all tests are actually passing. If checks from CI fail, this should indicate that there are issues with the package, not with some external stuff like code-cov had problems ;-)

**Comment by mattansb** [comment]
<img width="165" alt="image" src="https://user-images.githubusercontent.com/35330040/154427487-6586804c-d450-4052-88f0-95cde80bb735.png">

I'm so close I can TASTE IT!

**Comment by mattansb** [comment]
How about we set some lower bars first?

Try to get to 50% on all pkgs, then 75, then 90%?
(I've just spent almost an hour and I've went from 86.09 to 86.13....)

**Comment by strengejacke** [comment]
The title already says "as close as possible", so the bar is as high as we want it to be ;-)
Some packages supported in _insight_ and _parameters_ are not on CRAN, and therefore not tested against - I think, all packages that appear in tests also need to appear somewhere in the DESCRIPTION, and this requires packages to be on a official repository (CRAN, bioconductor). That's why these packages will have lower coverage by design, if I'm not mistaken.

**Comment by mattansb** [comment]
I think you can have as many `skip_if_not_installed()` as you want, regardless of CRAN status...

**Comment by strengejacke** [comment]
> I think you can have as many `skip_if_not_installed()` as you want, regardless of CRAN status...

But skipping tests does not increase code coverage?

**Comment by IndrajeetPatil** [comment]
@LeoDutriaux and @mkshaw  Hi Leo and Mairead! 👋 

Will you be interested in contributing here?

You can pick a repo of your choice that closely aligns with your interests. 

Unit tests are the most basic form of developer-facing documentation, and so this might be a great way for you to get to know the codebase of whichever repo you choose. 😊

**Comment by mkshaw** [comment]
@IndrajeetPatil do you have any recommended resources on writing unit tests?

**Comment by IndrajeetPatil** [comment]
Sure. 

You can have a look at this for a starter: https://r-pkgs.org/testing-basics.html

Once you are comfortable with that material, if you want, you can also have a look at `{testthat}` vignettes: https://testthat.r-lib.org/articles/

And, of course, feel free to ping us if something is not clear :)
We'll also be happy to chaperone a PR!

**Comment by LeoDutriaux** [comment]
Hi! Sorry for reacting that slowly, I'm going to have a look now at your links and hopefully start to work on the codes soon!
Thanks a lot!

**Comment by IndrajeetPatil** [comment]
@mkshaw and @LeoDutriaux Have you had any luck in understanding how to write unit tests?

Please let us know if you feel like you are stuck and can use a helping hand. I will also be happy to jump on a call to explain things if that's easier for you.

If you haven't had time to look at this yet, no worries. Just want to underscore that we are happy to help you get started.

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/194054343-d94b483c-57ab-40e7-ae9a-0c4131c0d7bd.png)

😔😟☹️😭

`performance` at 28%???

Can we at least get to 50%? (easystats, modelbased, see, performance)

**Comment by strengejacke** [comment]
I think if we set the version to devel (e.g. 0.10.0.1), then coverage will increase.

**Comment by IndrajeetPatil** [comment]
I am closing this issue since I now think it's pointless to chase after a certain level of code coverage. 

Additionally, as discussed in #336, our code coverage might be higher than what we see on Ubuntu.

Going forward, we just need to make sure that any new functionality is always accompanied by tests.
