### ISSUE TITLE
new vignette to collect learning resources about `easystats`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#103]
This will be part of the `easystats` meta-package itself and would contain links to presentation slides, workshop materials, YouTube tutorials, etc. by us or by others.

**Comment by strengejacke** [comment]
https://youtu.be/EPIxQ5i5oxs

**Comment by strengejacke** [comment]
https://twitter.com/patilindrajeets/status/1366681760944304128?s=19 (and you still need to tell me how to easily record such videos for Twitter)

**Comment by strengejacke** [comment]
https://twitter.com/patilindrajeets/status/1364843800124936192?s=19

**Comment by DominiqueMakowski** [comment]
> and you still need to tell me how to easily record such videos for Twitter

https://www.screentogif.com/

**Comment by IndrajeetPatil** [comment]
> and you still need to tell me how to easily record such videos for Twitter

I personally use `QuickTime Player` on `MacOS` and `screentogif` (@DominiqueMakowski already mentioned this) on `Windows`.

That said, as much as I don't like Mac, I definitely favour the former over the latter. 😅

**Comment by mattansb** [comment]
Demo of `bayestestR` functions (: 
https://mattansb.github.io/bayesian-evidence-iscop-2021

**Comment by IndrajeetPatil** [comment]
Closing this since the vignette is now there to be updated: https://easystats.github.io/easystats/articles/resources.html

Keep updating it as you come across learning resources.
