### ISSUE TITLE
next release cycle: "Happy Easter" edition

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#106]
High priority

- [x] `insight`
- [x] `parameters`
- [x] `performance`
- [x] `see`

Low priority

- [x] `modelbased`
- [x] `bayestestR`
- [x] `correlation`
- [x] `effectsize`

New

- [ ] `report`

**Comment by mattansb** [comment]
Unless insight / bayestestR / parameters need to update, I can do that today. @DominiqueMakowski @strengejacke

**Comment by strengejacke** [comment]
I lost a bit the track of the interdependencies and tests - are all tests passing, resp. will the current CRAN version of parameters work with the new effectsize? Else, go ahead!

**Comment by mattansb** [comment]
Hmmm... These are the changes:

![image](https://user-images.githubusercontent.com/35330040/110758622-639d0d00-8255-11eb-897a-aea1d2ff1f7f.png)

I don't think any of this should matter, right?

**Comment by DominiqueMakowski** [comment]
wow such nice and well-kept changelog 🙄

**Comment by mattansb** [comment]
So much shade being thrown here.... 🤣

**Comment by mattansb** [comment]
effectsize is on CRAN

**Comment by strengejacke** [comment]
@DominiqueMakowski What do we need to have on CRAN for _report_?

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil wanted to iron out some things if I'm not mistaken

**Comment by IndrajeetPatil** [comment]
If I am not mistaken, I think Daniel meant if `report` needs any of the devel versions of `easystats` packages to be on CRAN before it can be submitted?

Yeah, I was thinking of adding support for some robust versions of parametric tests. But if you think this is holding back the submission, you can go ahead with the initial release and I can add that functionality for the next release.

**Comment by strengejacke** [comment]
> If I am not mistaken, I think Daniel meant if report needs any of the devel versions of easystats packages to be on CRAN before it can be submitted?

Yes. exactly!

**Comment by IndrajeetPatil** [comment]
Checking in #143

**Comment by IndrajeetPatil** [comment]
Nope, at least right now, `report` doesn't require devel versions of the other `easystats` 📦 s it relies on.

**Comment by DominiqueMakowski** [comment]
Ah right, I'll submit to winchecks

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/gXnGAD2zxkcB
The files will be removed after roughly 72 hours.
Installation time in seconds: 13
Check time in seconds: 603
Status: 2 ERRORs, 1 NOTE
R version 3.6.3 (2020-02-29)

https://win-builder.r-project.org/yC7zBEQf0929
The files will be removed after roughly 72 hours.
Installation time in seconds: 14
Check time in seconds: 605
Status: 2 ERRORs, 1 NOTE
R version 4.0.4 (2021-02-15)

https://win-builder.r-project.org/ytg2EimE1oHV
The files will be removed after roughly 72 hours.
Installation time in seconds: 13
Check time in seconds: 648
Status: 2 ERRORs, 2 NOTEs
R Under development (unstable) (2021-03-27 r80128)

**Comment by IndrajeetPatil** [comment]
The errors are all related to `brms`-tests. I think we should be skipping these tests on `CRAN` given how fragile they are.

**Comment by strengejacke** [comment]
yeah, I modified the test files already

**Comment by strengejacke** [comment]
Still some issues that could be fixed before submission, see https://github.com/easystats/report/issues/144

**Comment by strengejacke** [comment]
_insight_ would be ready to submit.

**Comment by IndrajeetPatil** [comment]
@mattansb Can we also push a new **minor** version release of `effectsize`?

I would like to update my packages but would prefer if the Kendall's _W_ bug fix in `effectsize` is already on `CRAN`; it leads to a big difference in the estimates.

**Comment by mattansb** [comment]
I think it's too soon - only been 2 weeks... @strengejacke ?

**Comment by DominiqueMakowski** [comment]
yeah and since cran-people already hate indra we don't want to be associated with him 😁 

![](https://media.giphy.com/media/J1AMvYNMGYRWUGzegc/giphy.gif)

**Comment by IndrajeetPatil** [comment]
LOL, I am not author on `effectsize`, so I think you guys are fine ;)

@mattansb: The 2-week rule is just a suggestion and not a strict rule. I have done a hotfix release the _next day_ if I realized there was a critical bug that needed immediate fix. As long as your `cran_comments.md` clarifies the urgency of the update, the CRAN team wouldn't mind.

**Comment by IndrajeetPatil** [comment]
Oh, and the last `effectsize` release was on 2021-03-14, so we already past the 2-week window.

**Comment by strengejacke** [comment]
@DominiqueMakowski can bayestestR be submitted or is there anything you would like to address before?

**Comment by DominiqueMakowski** [comment]
There's only https://github.com/easystats/bayestestR/issues/364 ... In any case we should take some action to avoid eternal warning messages (and the ROPE one is particularly annoying since it shows up everytime we summarize a model)...

**Comment by strengejacke** [comment]
I plan to submit _parameters_ the next days... anything that needs to be addressed before submission?

**Comment by mattansb** [comment]
(effectsize has been submitted - waiting for the final "on its way to CRAN")

**Comment by IndrajeetPatil** [comment]
> anything that needs to be addressed before submission

None from my end.

**Comment by DominiqueMakowski** [comment]
I'll submit bayestestR tomorrow

**Comment by mattansb** [comment]
_On its way to CRAN_

**Comment by strengejacke** [comment]
bayestestR checks now seem to pass, you may check on winbuildr.

**Comment by IndrajeetPatil** [comment]
`correlation` is now on `CRAN`

**Comment by strengejacke** [comment]
_performance_ submitted.

**Comment by strengejacke** [comment]
ok, _see_ and _performance_ on CRAN. Not sure if modelbased is planned to be released soon?

**Comment by DominiqueMakowski** [comment]
> Not sure if modelbased is planned to be released soon?

Yes we should, even though the API is not polished due to the recent get_predicted changes, at least it won't be broken

**Comment by strengejacke** [comment]
You may check if you want to disable certain tests for OSX to avoid the errors we have for bayestestR on CRAN. Latest rstanarm is not available for all OSX versions, and thus get_predicted fails.

**Comment by DominiqueMakowski** [comment]
modelbased_0.6.0, report submitted :)

**Comment by IndrajeetPatil** [comment]
So only `report` remains now. I am closing the issue now because the `report` submission is being tracked in a separate issue (https://github.com/easystats/report/issues/124).
