### ISSUE TITLE
A list of possible projects for GSoC 2022

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#109]
For an example, see `stan`'s list for 2021:
https://github.com/stan-dev/design-docs/blob/master/gsoc_proposals/2021/proposal_main.md

For how it works:
https://summerofcode.withgoogle.com/how-it-works/

**Comment by IndrajeetPatil** [comment]
Few possibilities:

- Supporting more ML algorithms (cf. https://github.com/easystats/easystats/issues/110)

**Comment by DominiqueMakowski** [comment]
Deadline for project submission is likely to be around **February 20, 2022** (based on the one of this year)

**Comment by IndrajeetPatil** [comment]
I am moving automated feature selection to the bottom of the list because, although we support this functionality, none of us really believe it's a good practice. So better not to make others work on something that we ourselves are so unsure to begin with 😅

**Comment by IndrajeetPatil** [comment]
Closing this. It was aspirational on our part to make it happen, but seems unlikely to happen.

**Comment by DominiqueMakowski** [comment]
😢
