### ISSUE TITLE
Roadmap for CRAN submissions

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#11]
What would you consider to be the next packages (order of submission) to be released on CRAN?

Does following order make sense?

1. bayestestR
2. performance
3. parameters
4. report

- estimate?
- correlation?
- circus?

I personally would currently focus on _performance_, as I have still some parts to contribute (ICC etc.). Still haven't heard anything from CRAN yet according _insight_, though they wrote that it takes approx. 10 working days to hear from them (would be by the end of this week).

**Comment by DominiqueMakowski** [comment]
for `circus`, I don't think its scope / dev stage is advanced enough for a CRAN release. I see it more as an "internal" easystats thing just to help with systematic testing. I am not sure it can be useful to others...

`correlation`, after some feedback, could be ready for release quite fast, as its scope is clearly defined and it is pretty much feature complete (do not hesitate to check if anything can be improve/added).

For the order of the others, I would say that bayestestR is also well advanced for release in terms of documentation, testing and design. `performance`'s basis is also there. The main lacking things that I see of `parameters` are p values for mixed models and omega squared for anovas (😅), as it is necessary for their `report()`.

Yes, report(), as it is depending on all the others, should be released last :)

**Comment by strengejacke** [comment]
bayestestR needs to be released first, because other packages depend on it. I'm trying to see whether I can work a bit on that package the next days. Hopefully, insight will be accepted soon.

**Comment by DominiqueMakowski** [comment]
Based on the dependencies hierarchy, a potential roadmap can be:

1. bayestestR
2. parameters & performance
3. correlation & estimate
4. report

**Comment by strengejacke** [comment]
Yes. bayestestR is now quite advanced, the most important thing is polishing the docs, I think.
But first, we need to update _insight_! Maybe we should aim the first week of April? It's just one month after initial release, but there are some important changes in _insight_, and we will for sure have longer release-cycles in the future.

**Comment by DominiqueMakowski** [comment]
yes insight should go first as it has indeed major changes, that could justify this particularly short cycle. Let's continue polishing the docs and updating the other packages in the meantime, so we can chain-release them after :)

I would prefer to have report released sooner than later, it will be easier to use it with students

**Comment by strengejacke** [comment]
performance was submitted on Monday, I think. I'll await feedback latest next week. What's the next package? _parameters_?

**Comment by DominiqueMakowski** [comment]
I think so yes!

**Comment by strengejacke** [comment]
performance is on CRAN now...

**Comment by DominiqueMakowski** [comment]
I think we can close this, as the release roadmap is now quite clear: `parameters`, then `correlation` & `estimate` and finally `report`

We're somewhat half way :)
