### ISSUE TITLE
Being more selective with suggested packages?

### ISSUE THREAD

**Issue by mattansb** [easystats/easystats#111]
There are currently two types of suggested packages:

- Packages used internally by our functions (e.g. `lme4::ranef()`, `lavaan::coef()`)
- Packages with models we support, that are only used in testing to see that out functions are working properly (e.g. `tidymodels`)

Is there a way to have tests run properly without having to add the latter packages to our suggests?

**Comment by strengejacke** [comment]
no.

**Comment by mattansb** [comment]
:(

**Comment by strengejacke** [comment]
> All packages that are needed12 to successfully run R CMD check on the package must be listed in one of ‘Depends’ or ‘Suggests’ or ‘Imports’. Packages used to run examples or tests conditionally (e.g. via if(require(pkgname))) should be listed in ‘Suggests’ or ‘Enhances’. (This allows checkers to ensure that all the packages needed for a complete check are installed.)

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies

**Comment by DominiqueMakowski** [comment]
I agree with @mattansb that it would help us get a clearer view on the dependencies we use and the ones we support. Maybe we could start splitting the suggest list in two (i.e.., two alphabetically ordered sublists)?

**Comment by mattansb** [comment]
Maybe we can add the supported packages under `Enhances`? We do call these tests conditionally...

**Comment by mattansb** [comment]
> Finally, the ‘Enhances’ field lists packages “enhanced” by the package at hand, e.g., by providing methods for classes from these packages, or ways to handle objects from these packages.

Sounds exactly right.
I'm gonna try this with `effectsize` - I'll let you know how it goes (:

**Comment by mattansb** [comment]
So it worked!

Here are the things I did:

## Changes in `DESCRIPTION`

1. Packages in `Suggests`:
   1. I searched the repo for `requireNamespace` - any package called I left in suggests.
   2. I also left all the `easystats` packages that were in `Suggests`
   3. I also left some dev related packages here (`rmarkdown`, `testthat`...)
2. Packages in `Suggests`: All the model-generating packages, that we... enhance!

Final version looks like this:

```
Depends:
    R (>= 3.4)
Imports:
    bayestestR (>= 0.8.2),
    insight (>= 0.13.2),
    parameters (>= 0.12.0),
    stats,
    utils
Suggests:
    boot,
    correlation,
    covr,
    dplyr,
    gamm4,
    ggplot2,
    knitr,
    lme4,
    lmerTest,
    modelbased,
    performance,
    rmarkdown,
    rstanarm,
    rstantools,
    see,
    spelling,
    testthat,
    tidyr
Enhances:
    afex,
    BayesFactor,
    brms,
    car,
    emmeans,
    lavaan,
    lm.beta,
    MASS,
    mediation,
    MuMIn,
    pscl,
    tidymodels
```

## Changes to tests

I made sure that all relevant tests run conditionally with `testthat::skip_if_not_installed()`.

## Changed to `workflows/R-check.yaml`

We still want all the tests to run, so I had to tell GH-actions to also install the `Enhanced` packages by changing:

```R
saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)

...

remotes::install_deps(dependencies = TRUE)
```

To 

```R
saveRDS(remotes::dev_package_deps(dependencies = c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances")), ".github/depends.Rds", version = 2)

...

remotes::install_deps(dependencies = c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances"))
```

This means that in GH-actions all tests should run, but on CRAN only the tests that are conditional on the `Suggests` packages will run.

**Comment by mattansb** [comment]
Two advantages to this:

1. When using `install.packages(, dependencies = TRUE)` the `Enhances` don't get installed!
2. This also have the advantage of looking really cool on CRAN:

![image](https://user-images.githubusercontent.com/35330040/113974534-bf53b980-9846-11eb-826b-51121a25bb73.png)

_"all of these packages are made better by my package!_"

**Comment by IndrajeetPatil** [comment]
This is really cool!

I often saw this `Enhances` field but had no idea what it stands for, and glad to see that this is what it stands for! 😅 
> "all of these packages are made better by my package!"

**Comment by DominiqueMakowski** [comment]
indeed, very cool, once we have that we should change the installation instructions to have `dependencies=TRUE` in the README so that new users don't run into "you need to install this and that" too often

**Comment by strengejacke** [comment]
ok, I tried this for _parameters_ now. If it works, I'll submit then.

**Comment by strengejacke** [comment]
Looking at the test output from here https://github.com/easystats/effectsize/runs/2270368389 or parameters, I'm not sure the enhanced packages are really checked?

**Comment by mattansb** [comment]
That's weird, because if you look at the installed deps z you'll see that all those skipped packages are installed!
Any idea why this is happening?

**Comment by strengejacke** [comment]
No, not really... I'll wait for this move until the next release cycle.

**Comment by bwiernik** [comment]
It appears by design:

> Finally, the ‘Enhances’ field lists packages “enhanced” by the package at hand, e.g., by providing methods for classes from these packages, or ways to handle objects from these packages (so several packages have ‘Enhances: chron’ because they can handle datetime objects from chron even though they prefer R’s native datetime functions). Version requirements can be specified, but are currently not used. Such packages cannot be required to check the package: any tests which use them must be conditional on the presence of the package. (If your tests use e.g. a dataset from another package it should be in ‘Suggests’ and not ‘Enhances’.)

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies

Based on my reading of that section, I think it would work if a `require()` call to the packages is added to the tests?

**Comment by strengejacke** [comment]
I do that by default for tests, to ensure checks don't fail when conditionally used packages are not available.
So each test-file from all easystats packages _should_ start with 

``` r
if (require("xyz") {
  # ... do tests ...
}
``` 

I think, @mattansb switched to `skip_if_not_installed()` recently.

**Comment by mattansb** [comment]
@bwiernik The tests don't fail, they're skipped... But they shouldn't (on GH actions) because all the Enhanced packages are installed... :/

`skip_if_not_installed()` is just a fancy wrapper for `require()` - I prefer it because I have on test file per function, with often different required packages for different sub-tests...

**Comment by mattansb** [comment]
I am unable to get CI tests to work with the packages in `Enhances`. Reverting these changes in `effectsize` :(

Keeping this issue open, in case any one has any ideas in the future.

**Comment by bwiernik** [comment]
😥

**Comment by mattansb** [comment]
@bwiernik I almost got it to work! Maybe you have some ideas...

**Comment by bwiernik** [comment]
Nope, I don't see why it would fail unfortunately

**Comment by IndrajeetPatil** [comment]
Are we still giving this a go or can this be closed?

**Comment by mattansb** [comment]
Sadly, closing...
