### ISSUE TITLE
CRAN check issues

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#115]
@DominiqueMakowski @IndrajeetPatil @mattansb 

Please inspect and see if it's something we should address/fix in our packages:

I think the bayestestR issue is fixed in this commit: https://github.com/easystats/bayestestR/commit/bd32814d3c041d073503772e6e9915da441d1057

``` r
easystats::CRAN_checks()
#> insight     Ok
#> bayestestR  1 Error, 1 Note
#> performance Ok
#> parameters  3 Notes
#> effectsize  1 Warning
#> modelbased  1 Error
#> correlation 1 Error, 1 Note
#> see         1 Warning
#> report      1 Error
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
`effectsize` is just a docs issue on one system. Haven't addressed this in 4 releases, so seems insignificant 😅

**Comment by IndrajeetPatil** [comment]
All good on `correlation` side

**Comment by IndrajeetPatil** [comment]
Should we do a minor `bayestestR` release to get rid of these `ERROR`s in CRAN checks for other packages?

**Comment by IndrajeetPatil** [comment]
Closing in favor of #139
