### ISSUE TITLE
print release cycle info while loading `easystats` meta-package

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#117]
Just like `tidyverse` and `tidymodels`:

![universe](https://user-images.githubusercontent.com/11330453/115842172-da652280-a41d-11eb-9504-1c2f269695da.jpeg)

**Comment by strengejacke** [comment]
what do you mean?

**Comment by IndrajeetPatil** [comment]
I mean let the user know which `eaystats` version is being loaded. 

In the example, the user can notice that they are loading `tidyverse 1.3.1` and `tidymodels 0.1.3`, but no such info is available for `easystats`.

**Comment by strengejacke** [comment]
I don't mind, we can do that, but I don't think there's so much change that we really need to print that information. Package versions are more important.

**Comment by DominiqueMakowski** [comment]
One thing that we could steal from tidyverse are their green checks symbols ✔️ which are a bit neater than ours :)

**Comment by strengejacke** [comment]
We had those tick marks, but I couldn't make it work with #105, that's why I switched to simple "v".

**Comment by bwiernik** [comment]
I can make that work

**Comment by IndrajeetPatil** [comment]
The tick marks issue addressed in https://github.com/easystats/easystats/commit/12d71445524cdbb418b81dce3f82bfb839543a13
