### ISSUE TITLE
dplyr < 0.8

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#12]
Do you still have dplyr 0.7.8 installed? I can't find our discussion where you posted the `str()` of a grouped data frame grouped with dplyr 0.7.8... I need once again the information on grouped df's from dplyr < 0.8

**Comment by DominiqueMakowski** [comment]
I think I do still have it if you need anything

The discussion was [here](https://github.com/easystats/parameters/pull/16#issuecomment-466958809)

**Comment by strengejacke** [comment]
Ah, ok. It's still difficult to see how dplyr treats two grouping vars... Can you please post the output from:

`dplyr::group_by(mtcars, gear, cyl) %>% str()`

Then I have a base-R-replacement for tidyr-functions (nest/unnest, spread/gather). I'm working on removing tidyr-deps for my other packages.

**Comment by DominiqueMakowski** [comment]
Oups I was wrong, it seems like I've upgraded dplyr to 0.8.0.1... 😕 

```
Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...
 - attr(*, "groups")=Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	8 obs. of  3 variables:
  ..$ gear : num  3 3 3 4 4 5 5 5
  ..$ cyl  : num  4 6 8 4 6 4 6 8
  ..$ .rows:List of 8
  .. ..$ : int 21
  .. ..$ : int  4 6
  .. ..$ : int  5 7 12 13 14 15 16 17 22 23 ...
  .. ..$ : int  3 8 9 18 19 20 26 32
  .. ..$ : int  1 2 10 11
  .. ..$ : int  27 28
  .. ..$ : int 30
  .. ..$ : int  29 31
  ..- attr(*, ".drop")= logi TRUE
```
