### ISSUE TITLE
README questions

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#129]
- [x] Can we leave out the labels here? The plot is becoming (increasingly) cluttered to the point of illegible:
  https://raw.githubusercontent.com/easystats/easystats/master/man/figures/unnamed-chunk-6-1.png

- [x] I am not sure what this is supposed to be for. Can this be removed?
  https://github.com/easystats/easystats/blob/ce14a1a9b49c1c3786fdabe929fe8e6f0ad523a0/README.Rmd#L650-L672

- [x] The _List of functions_ section is too long, and I am not sure what purpose it serves. Can we think of a better way to illustrate functionality provided by `easystats` packages (cf. https://github.com/easystats/easystats/issues/26)?
I think workflow figures like [these](https://github.com/easystats/performance/blob/master/man/figures/figure_workflow.png) are much better at piquing users' interest and inviting them to explore these functions more. I am not sure if just listing them is going to be much helpful for anyone. But I might be wrong here.

**Comment by bwiernik** [comment]
(1) how about
