### ISSUE TITLE
introducing a new function to check if package is installed?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#134]
Throughout `easystats` packages, we have multiple instances of checking the needed packages, but the exact wording of the message might differ from package to package. Additionally, it is an unnecessary duplication of code.

So I was wondering if we should introduce a function like the following in `insight`:

```r
#' Checking if needed package is installed

#' @param string naming the package, whose installation needs to be checked in any of the libraries
#' @param … Currently ignored

check_if_installed <- function(package, ...) {
  if (!requireNamespace(package, quietly = TRUE)) {
    stop(message(paste0("Package '", package, "' required for this function to work. Please install it.")),
         call. = FALSE)
  }
}

# does it work?
check_if_installed("bestNormalize")
#> Package 'bestNormalize' required for this function to work. Please install it.
#> Error:
```

<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
I like it. Perhaps also add an install.packages() call as a final line that could be copy pasted.

**Comment by strengejacke** [comment]
I think a `check` function could possibly return TRUE / FALSE, and an additional argument (maybe default to TRUE?) could stop the code.

**Comment by IndrajeetPatil** [comment]
> additional argument (maybe default to TRUE?) could stop the code

Why is this necessary? Shouldn't we be stopping the functon _always_ since the needed package is not available?

**Comment by strengejacke** [comment]
Usually, yes. But if we have an additional argument, we _could_ us the function in other contexts as well.

**Comment by IndrajeetPatil** [comment]
Gotcha!

**Comment by strengejacke** [comment]
I wonder if this function could really be helpful... We most check namespace if we want to use packages conditionally. CRAN checks if packages are in imports or in suggests, and if only suggested, the checks look whether the availability of the package was checked with `requireNamespace()`. I'm not sure if CRAN checks will detect this if we use this function?

**Comment by IndrajeetPatil** [comment]
Let's start small: we can replace one instance of this in `insight` with the new function during the next release and see if CRAN complaints and take it from there.

I think it should be fine.

**Comment by IndrajeetPatil** [comment]
Trying this in https://github.com/easystats/insight/pull/355

Let's see if any of the checks complain.
