### ISSUE TITLE
add a new function to install all suggested packages in `easystats` core packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#135]
cf https://github.com/easystats/modelbased/issues/103#issuecomment-834244437

**Comment by mattansb** [comment]
Such a function would have to be smart enough to not install packages in the suggests that aren't actually ever required by any easystats function....

**Comment by IndrajeetPatil** [comment]
But we will be hardcoding this not automating it via `DESCRIPTION` file.

We will basically keep an updated list of such packages in this function.

**Comment by DominiqueMakowski** [comment]
> Such a function would have to be smart enough to not install packages in the suggests that aren't actually ever required by any easystats function...

I wonder if there's a solution besides manually listing all these packages :/

**Comment by IndrajeetPatil** [comment]
Basically, the list will cover every instance of `check_if_installed` like this:

https://github.com/easystats/insight/blob/f5923ec009a128397d72d7d35f54e7fccd9ea5fe/R/get_priors.R#L29-L30

This should be simple enough.

**Comment by IndrajeetPatil** [comment]
> I wonder if there's a solution besides manually listing all these packages :/

Once we use `check_if_installed` everywhere in core packages, we can try to automate this.

**Comment by bwiernik** [comment]
We can do a whole-directory search for `/check_if_installed\((["|'].+["|'])\)/` and extract the match groups.

**Comment by IndrajeetPatil** [comment]
Preparing the vector manually to expedite this.

```r
install_suggested <- function() {
  # if you add a new instance of `check_if_installed`, please edit the corresponding entry
  # duplicated entries are fine; we are using unique values anyway
  pkg_download <- unique(c(

    # `datawizard` --------
    "boot", "gamm4", "mclust", "multimode", "rstanarm",

    # `effectsize` --------
    "BayesFactor", "boot", "lme4", "lmerTest", "rstanarm", "rstantools",

    # `correlation` --------
    "BayesFactor", "Hmisc", "polycor", "psych", "wdm",

    # `report` ----------
    # none

    # `modelbased` ----------
    "emmeans"
  ))

  install.packages(pkg_download)
}
```

**Comment by mattansb** [comment]
Perhaps we should have `install_suggested(package = "bayestestR")` or something of the sort to get only the ones for a specific easystats package?

**Comment by IndrajeetPatil** [comment]
Yeah, sounds good.

**Comment by IndrajeetPatil** [comment]
Can someone please test this new function (and fix it if you find a bug)?
