### ISSUE TITLE
use `check_if_installed` for conditional package installation

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#136]
see: https://easystats.github.io/insight/reference/check_if_installed.html

- [x] `insight`
- [x] `correlation`
- [x] `parameters`
- [x] `performance`
- [x] `see`
- [x] `modelbased`
- [x] `bayestestR`
- [x] `effectsize` 
- [x] `report`
- [x] `easystats`

**Comment by mattansb** [comment]
I made some changes to the function so that it can also be used when an error is not required (is `stop = FALSE` is gives a warning instead + the function returns a logical value)
