### ISSUE TITLE
visualisation package

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#14]
Was thinking about the writing on the vignette for bayestestR, for the introductory examples, and it needs some plots to show the posteriors, visualise the indices and such. Hence, we might want to push these plotting functions for bayestestR :)

So, about the name... any ideas?

- visualizeR is already [taken](https://github.com/SantanderMetGroup/visualizeR)
- visualize also
- vizreport is not, but it would be quite contrasting with the other easystats names, which are quite "plain"

**Comment by DominiqueMakowski** [comment]
Ok maybe something even more original and more in the feel of "insight", simply "see" (with its punchline being "see to believe" or "don't believe until you see").

**Comment by DominiqueMakowski** [comment]
Since you have more experience with plotting packages (sjplot), I think you should be the maintainer of this one also. What do you say?

**Comment by DominiqueMakowski** [comment]
One design idea for this, a bit uncommon for the whole tidy- philosophy, that could still be interesting to experiment, is the following:

- Contrary to other packages (in particular broom), the easystats packages return the actual names of things instead of generic and consistent names (i.e., Median and beta instead of `coef`, t or z instead of `statistics` etc.). This is IMHO a strength, increasing direct usability (publication-wise) and transparency (especially for beginners)
- This approach presents also weaknesses, in particular in regard to output consistency, e.g., dataframes returned by `parameters` do not always have the same names. This weakness becomes particularly relevant when it comes to plotting

With that being said, this could maybe be turned into an advantage to 1) make plots easily, 2) making them easily customisable and 3) show people how to make the said-plots. Indeed, in respect to the last point, it seems that built-in plotting functions are mainly used by people that don't have time/the knowledge to create these plots, but users familiar with ggplot will often create their plots themselves.

The idea would be to separate the two main steps of plotting, 1) generating the right dataframe (usually the most complicated part) and 2) plotting it with the arguments correctly specified (the right column for colour, the right column for x etc.). 

- For the first step, I could see a function (e.g., `data_plot`) that takes any easystats object and returns a consistent dataframe. This could go even further as the names would be directly the names of the aesthetics (column names like `x`, `colour`, `group`, `fill`, `ymin` etc.). The only trick would be store the titles and custom names (`y.axis.title = "Median of the Effect of Sepal.Length"`) in attributes to be able to retrieve them if needed.
- Then, the plotting function would plot this dataframe.

Of course, directly calling the plot function without data_plot first would run the latter under the hood. This way, people could directly call "plot()" and have cool outputs. At the same time, people wanting to customize their plots and having more control over it could call "data_plot()" and then make the plotting themselves, using different backend than ggplot if they want to etc...

What do you think?

**Comment by strengejacke** [comment]
> I think you should be the maintainer of this one also. 

Yes, absolutely ok for me.

I'm not sure, but somewhere we have already discussed the issue of consistent vs. matching colum names (I guess bayestestR), and we have though about a "translating" function or argument, that either returns column names that match what the indices actually mean, or that are consistent accross all functions.

We may think about implementing such behavour accross all easystats-packages?

According to your previous post: yes, agreed! It's actually similar to what ggeffects does, creating a constistent data frame, and optional plotting.

**Comment by DominiqueMakowski** [comment]
any thoughts about the name of the package :)?

**Comment by DominiqueMakowski** [comment]
I think we could go ahead and create the repo, to start experimenting a bit in order to find the right design

**Comment by strengejacke** [comment]
I still have no good idea about the name, but honestly I didn't have the time to think about it.

**Comment by DominiqueMakowski** [comment]
I understand :) In that case, maybe we could go for a provisory one just to name the repo ("see"?), then we can just experiment there for now (I'd like to try out some stuff) waiting for when we will have more time to give it some love do decide what do we do with this code
