### ISSUE TITLE
blog post about printing single and multiple models as tabular summaries

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#142]
I have drafted a vignette here:
https://easystats.github.io/parameters/articles/model_parameters_print.html

Is somebody motivated making a blog post out of it?

**Comment by IndrajeetPatil** [comment]
Is there any way to avoid this spilling of the header on the next line?

<img width="879" alt="Screenshot 2021-06-02 at 18 59 53" src="https://user-images.githubusercontent.com/11330453/120521040-c9241400-c3d4-11eb-8de0-a9ab0b69b16d.png">

**Comment by bwiernik** [comment]
Adjust options(width = 80)

**Comment by IndrajeetPatil** [comment]
I am closing this since this is quite outdated and the vignette has been out there for a while by now. 

We can highlight this functionality once in a while through Tweets, though, like I did just right now.
