### ISSUE TITLE
`datawizard` and `visualization_recipe()` cycle

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#143]
The next cycle will take place after `datawizard` makes it to CRAN, and the new visualization recipes are included:

Status for individual packages:
- [x] `insight`
- [x] `datawizard`
- [x] `parameters`
- [x] `performance`
- [x] `see`
- [x] `modelbased`
- [x] `bayestestR`
- [x] `correlation`
- [x] `effectsize` 
- [x] `report`

**Comment by IndrajeetPatil** [comment]
@strengejacke, @mattansb, @DominiqueMakowski You can safely start removing the `datawizard` functions now! ✂️

**Comment by DominiqueMakowski** [comment]
So do we make this cycle the 1.0 cycle? or do we allow ourselves for one last beta update to make sure everything is clean?

**Comment by IndrajeetPatil** [comment]
I would vote for the latter.
So the one after the next one should be 1.0.

**Comment by mattansb** [comment]
Same.

Just to be clear, we remove + add datawizard to imports, correct?

**Comment by IndrajeetPatil** [comment]
Yes, re-export to be exact to not break anything

**Comment by IndrajeetPatil** [comment]
For example,
https://github.com/easystats/correlation/pull/191

**Comment by strengejacke** [comment]
Anything to do for _insight_? Need to submit, due to fixest update.

**Comment by IndrajeetPatil** [comment]
As far as I can see, nothing.

**Comment by IndrajeetPatil** [comment]
Unless there is an objection, I'll be submitting `correlation` to `CRAN` today.

**Comment by IndrajeetPatil** [comment]
Sigh, since we are re-exporting `simulate_simpson()` from devel-`bayestestR`, I can't submit it before `bayestestR`.

I will wait.

**Comment by DominiqueMakowski** [comment]
How about we don't reexport 👀 

We could even search all GitHub for the instances of functions used from wrong packages in other packages and notify the authors ? But I think with v1 approaching we should not hesitate to tidy up

**Comment by bwiernik** [comment]
There is revdepcheck that can find any breakage

**Comment by IndrajeetPatil** [comment]
@strengejacke Can you please let me know when you plan to submit `parameters` to CRAN?

I need to organize submissions of my packages accordingly. I would prefer if it is submitted after `WRS2 1.1-3` is on CRAN (this should happen soon; I am coordinating with Patrick about this).

**Comment by strengejacke** [comment]
I have no concrete plans, but I think in general, it is ready to submit. I would probably wait for https://github.com/easystats/insight/pull/401 to be merged to see if the changes affect _parameters_ or not.

**Comment by IndrajeetPatil** [comment]
> I have no concrete plans, but I think in general, it is ready to submit.

Okay, can you please then wait for `WRS2`'s next release. I will let you know once it's on CRAN.

**Comment by IndrajeetPatil** [comment]
High-priority issues we should attempt to close before this cycle makes it to CRAN:

- [ ] https://github.com/easystats/parameters/issues/523
- [ ] https://github.com/easystats/correlation/issues/203
- [ ] https://github.com/easystats/insight/issues/400
- [ ] https://github.com/easystats/insight/issues/396
- [ ] https://github.com/easystats/see/issues/119

**Comment by IndrajeetPatil** [comment]
> Okay, can you please then wait for WRS2's next release. I will let you know once it's on CRAN.

@strengejacke If you want, `parameters` can be submitted to CRAN. Although WRS2's next version is not yet on CRAN, I have already made the necessary changes and am also skipping tests for a lower version than the upcoming one.

**Comment by IndrajeetPatil** [comment]
@strengejacke Does the version of *performance* accepted on CRAN not contain https://github.com/easystats/performance/commit/24d0a3b257b92aee72d18274505f3a805a8de9f6?
This is going to be an issue for updating other packages on CRAN, and we will need to do another hotfix release.

**Comment by IndrajeetPatil** [comment]
Unless there are any objections, I will submit new version of `datawizard` to CRAN today.

**Comment by strengejacke** [comment]
> @strengejacke Does the version of _performance_ accepted on CRAN not contain [easystats/performance@24d0a3b](https://github.com/easystats/performance/commit/24d0a3b257b92aee72d18274505f3a805a8de9f6)?
> This is going to be an issue for updating other packages on CRAN, and we will need to do another hotfix release.

The submission included all commits until https://github.com/easystats/performance/commit/7f5b941ca20e4123bc0e98feff08d33c566583b5. Where does this caus additional issues?

**Comment by IndrajeetPatil** [comment]
Because I don't see the new `check_` functions in CRAN version [manual](https://cran.r-project.org/web/packages/performance/performance.pdf): 
`check_multimodal()` and `check_heterogeneity_bias()`


<img width="1200" alt="Screenshot 2021-07-22 at 12 36 11" src="https://user-images.githubusercontent.com/11330453/126626532-3b5fadf8-20a6-4790-9e66-cf6c6fa5a1dd.png">

**Comment by strengejacke** [comment]
Yes, yes, _performance_ was submitted before those changes (at this stage: https://github.com/easystats/performance/issues/326#issuecomment-879798585).

**Comment by IndrajeetPatil** [comment]
That's what I meant. We need to another release of `performance`, otherwise we can't update `effectsize`, which relies on the newly added function:

https://github.com/easystats/effectsize/blob/059602e63a40bc8a342133aa223e5feefd572a30/R/standardize_info.R#L365

**Comment by strengejacke** [comment]
Are there any urgent changes in _effectsize_, or can we skip the current release cycle for it?

**Comment by IndrajeetPatil** [comment]
But we *must* release `performance`, there is just no way around it.

CRAN version of `effectsize` relies on `check_heterogeneity` function in `parameters`, which we have now removed.

This means, once we update `parameters` in this cycle, CRAN-`effectsize` will break.

**Comment by strengejacke** [comment]
How I do a revdep-check? I don't have the script here on my office PC.

**Comment by IndrajeetPatil** [comment]
```r
library(revdepcheck)

revdep_check(num_workers = 4)
revdep_report()
revdep_reset()

```

**Comment by strengejacke** [comment]
Ok, we must first submit _insight_ then.

**Comment by IndrajeetPatil** [comment]
Okay here is the order, I _think_, we need to follow:

1. insight
2. bayestestR (critical)
3. parameters
4. performance
5. effectsize
6. correlation
7. datawizard
8. see
9. modelbased
10. easystats

**Comment by strengejacke** [comment]
I would even put _bayestestR_ first, because the deadline is very close. Anyone an idea where @DominiqueMakowski is?

**Comment by IndrajeetPatil** [comment]
He is busy doing French things.

![EmbellishedFancyGrayreefshark-max-1mb](https://user-images.githubusercontent.com/11330453/126652838-451d7f18-e80f-4120-a760-e284e537111d.gif)

**Comment by IndrajeetPatil** [comment]
`bayestestR` is on CRAN.

**Comment by strengejacke** [comment]
Regarding the dependencies, is your submission order still up to date? Shouldn't _effectsize_ be submitted before _parameters_?

**Comment by IndrajeetPatil** [comment]
Hmm, but `effectsize` currently relies on `performance::check_heterogeneity_bias()`, which is not present in CRAN version of `performance`.

So we can possibly do `parameters` after `effectsize`, but `performance` definitely needs to be before `effectsize`.

**Comment by mattansb** [comment]
Can we not have a quick fix to performance first?

**Comment by DominiqueMakowski** [comment]
(in any case, datawizard needs to be submitted first)

**Comment by strengejacke** [comment]
_insight_ on CRAN.

**Comment by IndrajeetPatil** [comment]
`{datawizard}` is on CRAN

**Comment by IndrajeetPatil** [comment]
The next one should be (I think) `{performance}`, but this needs to be closed first:
https://github.com/easystats/parameters/issues/581

**Comment by strengejacke** [comment]
https://github.com/easystats/parameters/issues/581 will be addressed in the next release-cycle.

**Comment by strengejacke** [comment]
Looks like _see_ should be the next package to be updated? Are there any issues that need to be resolved before submission, @IndrajeetPatil @bwiernik ?

**Comment by IndrajeetPatil** [comment]
Nothing urgent for the next release, so`{see}` can be updated.

**Comment by bwiernik** [comment]
I'd potentially like to see https://github.com/easystats/see/pull/195 finished, but that could wait until the next cycle for CRAN

**Comment by strengejacke** [comment]
Is the news file up to date?

**Comment by bwiernik** [comment]
Actually, wait, I just found a pretty big bug with `plot.check_model()` for rstanarm objects. Let me look at it.

**Comment by strengejacke** [comment]
Yes, no hurry.

**Comment by bwiernik** [comment]
I'm not really sure what `performance:::.check_assumptions_stan()` is doing.

**Comment by strengejacke** [comment]
> I'm not really sure what `performance:::.check_assumptions_stan()` is doing. I'll open an issue on _performance_

I think it simply shows prior distribution overlayed by posterior distribution.

**Comment by bwiernik** [comment]
Could you weigh in at https://github.com/easystats/performance/issues/354?

**Comment by IndrajeetPatil** [comment]
@strengejacke When are `{performance}` and `{parameters}` updates going to be submitted to CRAN?

**Comment by strengejacke** [comment]
These are the next ones, but I'm not sure which of the remaining easystats packages needs to go first? What about _effectsize_?

**Comment by mattansb** [comment]
effectsize can be submitted, but I'd prefer to wait for https://github.com/easystats/effectsize/issues/367 @bwiernik if possible...

**Comment by bwiernik** [comment]
Will try to get to this weekend

**Comment by strengejacke** [comment]
_parameters_ requires the new _effectsize_, so I would wait for your submission.

**Comment by mattansb** [comment]
Alright, I'll submit now (@bwiernik we'll keep working on our stuff for next relese)

**Comment by mattansb** [comment]
effectsize depends on the new performance... Is performance on its way to CRAN?

**Comment by bwiernik** [comment]
Do we have a dependency diagram for our own packages to understand which ones are relatively more downstream vs upstream?

**Comment by mattansb** [comment]
We use to have that, don't know where it has gone...

``` r
pkgs <- available.packages(repos = "https://easystats.r-universe.dev")
pkgs <- rownames(pkgs)
pkgs <- pkgs[!pkgs %in% c("see", "easystats")]

deps <- lapply(pkgs, deepdep::plot_dependencies)

patchwork::wrap_plots(deps) &
  ggplot2::theme(legend.position = "none")
```

![](https://i.imgur.com/wNHjbVs.png)

<sup>Created on 2021-09-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
Thanks. Based on that, this is the order of dependence. We should pin this order as an issue, always be sure to update in this order, and be careful to not introduce new dependencies out of order:

`1.` insight
`2.` datawizard
`3.` bayestestR
`4.` performance
`4.` parameters
`5.` correlation
`5.` effectsize
`6.` report
`6.` modelbased
`7.` see
`8.` easystats

performance+parameters occupy the same level of the hierarchy (share all higher dependencies, don't import each other), as do correlation+effectsize and report+modelbased

**Comment by bwiernik** [comment]
![image](https://user-images.githubusercontent.com/4773225/132884878-330544dc-d451-4cef-ac9c-bf263afba5f7.jpeg)

**Comment by mattansb** [comment]
Note that in the soon to be on CRAN version of effectsize, it does now depend on performance as well.

**Comment by strengejacke** [comment]
And note that we have circular dependencies, which are the cause for the current confusion in our submission process. ;-)

**Comment by mattansb** [comment]
But these aren't "true" dependencies. Like, parameters conditionally depends on effectsize, but can still be summitted before it. No?

**Comment by strengejacke** [comment]
I'm not sure. I'm currently looking into this issue:
https://github.com/easystats/parameters/runs/3564543595#step:10:838

Currently, _parameters_ doesn't seem to pass checks for the current CRAN version of _effectsize_, so it kind of "depends" on the latest _effectsize_ version.

**Comment by strengejacke** [comment]
And _effectsize_ fails for current _parameters_ (https://github.com/easystats/effectsize/runs/3564780735#step:10:14).

**Comment by strengejacke** [comment]
So we can't submit either package. :-D

**Comment by bwiernik** [comment]
I think we need to excise any dependency on effectsize out of parameters

**Comment by bwiernik** [comment]
But I'm not seeing how that test is even possible. The GitHub version of parameters doesn't Imports effectsize

**Comment by mattansb** [comment]
Are tests of parameters failing? Or the actual build?

If the tests, they can be conditional on a higher version on effectsize.

---

The effectsize tests are failing because someone (ehem, Daniel) removed the "remotes" from the description while the required version of performance isn't on CRAN yet... Which is why I need performance on CRAN before I submit effectsize.

**Comment by strengejacke** [comment]
> because someone (ehem, Daniel) removed the "remotes" from the description

Yes, this was intentional, to see potential issues with the current CRAN versions when submitting.

**Comment by strengejacke** [comment]
> But I'm not seeing how that test is even possible. The GitHub version of parameters doesn't Imports effectsize

To get effect sizes from `model_parameters()` for htest-objects, we call _effectsize_, if installed. _effectsize_, in turn, calls `model_parameters()` to get the parameters to calculate the effectsizes.

**Comment by strengejacke** [comment]
_datawizard_ refers to `parameters::check_heterogeneity_bias()`, which was moved to _performance_. Once _parameters_ will be updated on CRAN, CRAN checks for _datawizard_ will fail.

Therefore, I suggest that for now, _effectsize_ could use an internal copy of `performance::check_heterogeneity_bias()`, `check_heterogeneity_bias()` will stay in _parameters_ for now and removed from _performance_, and in a later update cycle, we could remove it from _parameters_.

2nd option would be to add `check_heterogeneity_bias()` to both _parameters_ and _performance_, and have a warning message at package startup for some time.

3rd option would be to wait until the next _datawizard_ release cycle, and then submit the other packages then.

**Comment by mattansb** [comment]
:/

The final soloution would be, in this order:

1. Update `performance` with `check_heterogeneity_bias()`
2. Update `parameters` to without `parameters::check_heterogeneity_bias()` and with conditional tests for a version of `effectsize` that is not yet on CRAN.
3. Checks with fail for `datawizrd`, so it will have to be updated even though last update was recent.
4. Update `effectsize`

Wouldn't that solve it?

**Comment by strengejacke** [comment]
> Wouldn't that solve it?

Yes, only "problematic" point is 3.) here. We can hope that CRAN team is forgiving here to "burden" them with another submission of _datawizard_ due to our "bad planning". Maybe, since we have automated checks/tests/submission procedures that relieve the CRAN team, submitting datawizard_ again isn't such a big issue.

**Comment by mattansb** [comment]
Let's do it!

**Comment by strengejacke** [comment]
Some recent changes in _performance_ (really not sure which ones, maybe https://github.com/easystats/performance/pull/362) break _report_:

https://win-builder.r-project.org/incoming_pretest/performance_0.8.0_20210915_135253/reverseDependencies/summary.txt

@DominiqueMakowski @bwiernik Is this expected, or do we need to fix something?

**Comment by IndrajeetPatil** [comment]
Hmm, looks like `report_performance()` can no longer return CIs for adjusted R^2.

**Comment by bwiernik** [comment]
@strengejacke That change is fine--those tests in *report* just need to be update with the new actual values

**Comment by bwiernik** [comment]
I can fix that it report

**Comment by bwiernik** [comment]
@strengejacke 

Question: Currently, in `model_performance()` output, we don't show the CIs for either Bayesian model or for the newly-added CIs for frequentist models. Instead, for the bayesian R2, they are stored in attributes `$r2_bayes` and `$r2_loo`. 

Do we (1) want to show them in the output by default and/or (2) store all of the various r2 CI information as elements under a common `$r2` attribute (bayesian, linear, and multilevel models may all have multiple r2 values).

**Comment by strengejacke** [comment]
> they are stored in attributes $r2_bayes

Is this a new behaviour? If so, this might be the cause for the breaking tests in _report_.

**Comment by bwiernik** [comment]
What's your preferred API structure for them:

```r
$r2
$r2$r2_bayes
# values

$r2
$r2$r2_loo
# values
```

or 
```r
$r2_bayes
# values

$r2_loo
# values
```

**Comment by bwiernik** [comment]
I think I have something that should be backwards compatible (though we will want to update *report* to handle the expanded functionality)

**Comment by strengejacke** [comment]
I'm not decided about the best API structure yet... @DominiqueMakowski any thoughts from your side?

**Comment by strengejacke** [comment]
Should we first try to implement it in _performance_ in a way that _report_ doesn't break, and then if necessary revise the API later?

**Comment by bwiernik** [comment]
That's what the third option should do. 

It has an umbrella `$r2` slots like we had before. Under that it has umbrella `SE` and `CI` slots. Those now have separate labeled slots for the different R2 types. They had named slots before, but only ever had one. So, this should be backwards compatible, if kind of confusing as a structure.

**Comment by bwiernik** [comment]
Yep, this option works. Pushed a commit to *performance*. Might need to update a test or two in *report* for places where adjusted R2 values change in the second decimal place.

**Comment by bwiernik** [comment]
Should model_performance() show CIs for R2 if they are available? By default or as an option? @strengejacke @DominiqueMakowski

**Comment by strengejacke** [comment]
I'd say as an option.

@DominiqueMakowski is report ready for submission? _performance_ will break tests, it will currently return
`"The model's explanatory power is substantial (R2 = 0.62, adj. R2 = 0.61)"`

while the test in _report_ expects
`"The model's explanatory power is substantial (R2 = 0.62, adj. R2 = 0.60)"`

I'm not sure if we can fix _performance_ to actually return the expected adj. R2? Else, _report_ needs to be ready to be submitted after _performance_ is submitted to CRAN.

**Comment by DominiqueMakowski** [comment]
I can submit report whenever needs be, but so the thing to fix is the test's expectation?

**Comment by strengejacke** [comment]
I've fixed the tests and committed all relevant changes. Now testing only with dev-version of _performance_, with other packages from CRAN (via GitHub actions). Let's see if that passes.

**Comment by strengejacke** [comment]
Does anyone understand what this error means?
https://github.com/easystats/report/runs/3618654709

**Comment by IndrajeetPatil** [comment]
Same issue as this: https://github.com/easystats/easystats/issues/169

It occurs and disappears sporadically.

**Comment by strengejacke** [comment]
hm... Since I would like to resolve https://github.com/easystats/parameters/issues/570 before submitting _parameters_, and looking at the results from the _report_ tests, I suggest disabling all tests for _report_ now, and re-enable them in a future update, when all these minor changes (.89 to .95 CI-level, minor fixes to df/se/ci etc.) are properly implemented. What would you say?

**Comment by IndrajeetPatil** [comment]
Sure, we can skip them on CRAN for now BUT we should continue to run these tests on GHA. And once the other updates are on CRAN, we can re-submit CRAN as a hot fix release with all tests turned back on again.

**Comment by DominiqueMakowski** [comment]
It's not like we are not used to failing tests on GH anyway 😅

**Comment by strengejacke** [comment]
ok, if you submit _report_, make sure to **not** use a dev-version number in the DESCRIPTION (i.e. change 0.3.5.1 to something like 0.3.6 or similar).

**Comment by strengejacke** [comment]
Ok, I _think_ that once the GitHub tests pass (https://github.com/easystats/report), you can submit _report_.

**Comment by bwiernik** [comment]
> I'm not sure if we can fix performance to actually return the expected adj. R2? Else, report needs to be ready to be submitted after performance is submitted to CRAN.

The change here in expected values is fine, so the test should be updated. r2_loo() now uses the method from rstantools to get a whole distribution, which we take the median of. The previous method was an approximation for just the center, so the points might vary slightly.

**Comment by strengejacke** [comment]
Thanks for clarification! I was wondering if it would be easier to revert the performance-changes temporarily than fixing all the tests and think about submission-order. ;-) But now since we disable tests temporarily in _report_, I think we can keep the changes in _performance_.

@DominiqueMakowski could you submit _report_ then?

**Comment by strengejacke** [comment]
_performance_ is submitted...

**Comment by IndrajeetPatil** [comment]
It's on CRAN. Should I submit `{datawizard}` now?

**Comment by strengejacke** [comment]
yes, and I think _effectsize_ can be submitted as well... order shouldn't matter.

**Comment by IndrajeetPatil** [comment]
Okay, I will submit it after office hours then.

**Comment by mattansb** [comment]
I'll submit effectsize by tomorrow.

**Comment by IndrajeetPatil** [comment]
I had submitted `{datawizard}` to CRAN, but the reverse dependency check found the following breakage, and I will need to confirm if this is expected. It's not, right?

```r
Dear maintainer,

package datawizard_0.2.1.tar.gz has been auto-processed. The auto-check found problems when checking the first order strong reverse dependencies.
Please reply-all and explain: Is this expected or do you need to fix anything in your package? If expected, have all maintainers of affected packages been informed well in advance? Are there false positives in our results?

*** Changes to worse in reverse dependencies ***
Debian: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.2.1_20211001_205301/reverseDependencies/summary.txt>

Log dir: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.2.1_20211001_205301/>
The files will be removed after roughly 7 days.

Pretests:
Windows: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.2.1_20211001_205301/Windows/00check.log>
Debian: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.2.1_20211001_205301/Debian/00check.log>

Last published version on CRAN:

CRAN Web: <https://cran.r-project.org/package=datawizard>

Best regards,
CRAN teams' auto-check service
Package check result: OK

Changes to worse in reverse depends:

Package: see
Check: examples
New result: ERROR
  Running examples in ‘see-Ex.R’ failed
  The error most likely occurred in:

  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: print.see_performance_pp_check
  > ### Title: Plot method for posterior predictive checks
  > ### Aliases: print.see_performance_pp_check plot.see_performance_pp_check
  >
  > ### ** Examples
  >
  > if (require("performance")) {
  +   model <- lm(Sepal.Length ~ Species * Petal.Width + Petal.Length, data = iris)
  +   pp_check(model)
  + }
  Loading required package: performance
  Error in pp_check(model) : could not find function "pp_check"
  Execution halted
```

**Comment by IndrajeetPatil** [comment]
As far as I can see, this has nothing to do with `{datawizard}` update, since the CRAN checks are failing with the same error even with the CRAN version of `{datawizard}`:

https://cran.r-project.org/web/checks/check_results_see.html

![image](https://user-images.githubusercontent.com/11330453/135674971-2c904640-6daa-4dd9-81dd-e0903f3a17a0.png)

**Comment by bwiernik** [comment]
I don't see why that would have anything to do with datawizard. It's due to the removal of pp_check() from performance (because it clobbered the broader stan pp_check)

**Comment by strengejacke** [comment]
yes, should be unrelated to a datawizard-see conflict. But I'll have to update _see_ anyway, due to the CRAN failures.

**Comment by strengejacke** [comment]
_see_ is on CRAN.

**Comment by IndrajeetPatil** [comment]
Okay, so the revdep issue for `{see}` is now fixed, but I see a new issue for `{correlation}`. 

Does this mean `{correlation}` needs to be updated again? 😰

cc @bwiernik, @DominiqueMakowski   

```r
Changes to worse in reverse depends:

Package: correlation
Check: examples
New result: ERROR
  Running examples in ‘correlation-Ex.R’ failed
  The error most likely occurred in:

  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: visualisation_recipe.easycor_test
  > ### Title: Visualisation Recipe for 'correlation' Objects
  > ### Aliases: visualisation_recipe.easycor_test
  > ###   visualisation_recipe.easycormatrix
  >
  > ### ** Examples
  >
  > # ==============================================
  > # Correlation Test
  > # ==============================================
  > if (require("see")) {
  + rez <- cor_test(mtcars, "mpg", "wt")
  +
  + layers <- visualisation_recipe(rez, labs = list(x = "Miles per Gallon (mpg)"))
  + layers
  + plot(layers)
  +
  + plot(rez,
  +      show_text = "label",
  +      point = list(color = "#f44336"),
  +      text = list(fontface = "bold"),
  +      show_statistic = FALSE, show_ci = FALSE, stars = TRUE)
  + }
  Loading required package: see
  Error in xy.coords(x, y, xlabel, ylabel, log) :
    'x' is a list, but does not have components 'x' and 'y'
  Calls: plot ... plot.visualisation_recipe -> NextMethod -> plot.default -> xy.coords
  Execution halted
```

**Comment by strengejacke** [comment]
Yeah, the whole visualization_recipe-stuff was not very successfully implemented...

**Comment by bwiernik** [comment]
@strengejacke did you fix all of the NextMethod() steps for visualization_recipe()

**Comment by strengejacke** [comment]
I did the changes in _datawizard_, _see_ and _performance_ before submission, and I realized that the `plot()` method for `parameters::cluster_analysis()` was also revised, so I made the changes in _parameters_, too. But I'm not aware in which places all these changes were made, so it's likely I missed something.

**Comment by mattansb** [comment]
effectsize:
> Thanks, on its way to CRAN.

**Comment by IndrajeetPatil** [comment]
`{datawizard}` update is on CRAN.

**Comment by IndrajeetPatil** [comment]
What's next? `{parameters}` or `{modelbased}`?

**Comment by bwiernik** [comment]
*parameters*

Besides *correlation* do any other packages use visualisation_recipe() and need to have plotting fixed?

**Comment by bwiernik** [comment]
*correlation* fixes related to visualisation_recipe() submitted to CRAN

**Comment by IndrajeetPatil** [comment]
Btw, deadline for updating `{statsExpressions}` is 2021-10-19, so I would appreciate if `{parameters}` is updated a week or so before then. That would leave me some time to do more testing, etc.

**Comment by IndrajeetPatil** [comment]
Next up:
`{bayestestR}` and then `{modelbased}`

**Comment by IndrajeetPatil** [comment]
Next up: `{modelbased}` and then we can close this issue 🥵

**Comment by bwiernik** [comment]
And then we can start all over again!

**Comment by IndrajeetPatil** [comment]
![circle-of-life-simba](https://user-images.githubusercontent.com/11330453/139538907-3da92e7a-3a77-49e3-88d7-5102c4ff1cfc.gif)

**Comment by IndrajeetPatil** [comment]
Since the current CRAN version of `{modelbased}` both relies on `[datawizard}` *and* uses visualization_recipe(), I am marking this cycle as complete.
