### ISSUE TITLE
r universe

### ISSUE THREAD

**Issue by mattansb** [easystats/easystats#160]
Thanks to the new [r-universe](https://easystats.r-universe.dev/) (!) here are some changes that come to mind:

1. Replace dev installation on GH and docs (related to #156)

```R
remotes::install_github("easystats/datawizard")
# becomes
install.packages('datawizard', repos = 'https://easystats.r-universe.dev')
```

2. `easystats:::easystats_update` - add option to install from the universe OR from CRAN?
3. For easystats `.onAttach`, should it check the version on r-universe instead of GH / CRAN?

If we start leaning into the r-universe (which I think we should), we need to make sure that the main branches are operational (so no pushing to main, Dom and Daniel!)

**Comment by IndrajeetPatil** [comment]
How is the latter better than the former? It's just more typing and memorizing (a longer URL) for the user.

```r
remotes::install_github("easystats/datawizard")
# becomes
install.packages('datawizard', repos = 'https://easystats.r-universe.dev')
```

What does leaning into it concretely mean for us?

> If we start leaning into the r-universe (which I think we should)

**Comment by IndrajeetPatil** [comment]
> Replace dev installation on GH and docs

I would personally find this most useful when one truly wants to install an entire universe, so what we have on `README` here is perfect, but I am not so sure about changing instructions for downloading _individual_ packages.

https://github.com/easystats/universe

**Comment by mattansb** [comment]
> How is the latter better than the former? It's just more typing and memorizing (a longer URL) for the user.

For the casual user: (1) It doesn't requite to install `remotes` or use a new function, (2) it takes less time to install (for datawizard on my PC 25s vs 9s), and (3) the verbosity of `remotes` when installing can be overwhelming and messy to debug.

> What does leaning into it concretely mean for us?

I think it would mean mostly defaulting to the r-universe when possible:
1. In the installation guides (instead of GH for the dev versions)
2. In `easystats` functions (instead of GH or CRAN)

**Comment by DominiqueMakowski** [comment]
I don't know enough about the r-universe initiative to have an opinion, but it's true that in general I don't find remotes/devtools to have the smoothest experience (@bwiernik also recently brought this up with the `pak` solution). So if r-universe is easier and more reliable, why not?

**Comment by strengejacke** [comment]
Does it install CRAN versions, or latest GitHub? Do we need to commit to both, or are updates to GitHub automatically fetched by runiverse?

**Comment by strengejacke** [comment]
> If we start leaning into the r-universe (which I think we should), we need to make sure that the main branches are operational (so no pushing to main, Dom and Daniel!)

Why?

**Comment by bwiernik** [comment]
It's faster because it serves built packages (is that also the case for Linux?), which is not only faster, but also smoother for new users (won't require Rtools or Xtools to be installed ever--I don't think we usually need them for our packages, but good to eliminate the possibility). `pak` also nicely hides the build vomit, I think serving a built package is better overall. 

For the internal functions, it also means we can stop importing `remotes`. 

The concern about pushing to main/master is that those are always being built and deployed to the universe. If we emphasize that that is a source for cutting edge but still stable versions of the packages, they should always build and work. So commits should always pass R CMD CHECK before being made to main. (This is already the case with installing from GitHub of course)

**Comment by mattansb** [comment]
>  (This is already the case with installing from GitHub of course)

👀

**Comment by strengejacke** [comment]
yeah, that sounds pretty cool! Though I'm not sure if I can change my habit to push to master/main only.

**Comment by bwiernik** [comment]
At least be sure to run devtools::check() before committing 😜

**Comment by strengejacke** [comment]
Anybody an idea how to give r-universe access to the GitHub repo/API, so it can set the [GitHub status](https://github.com/r-universe/easystats/actions/runs/1067046455) after building?

> $messages[[1]]
> [1] "\nGitHub API error (404): \nMessage: Not Found\nRead more at https://docs.github.com/rest/reference/apps#get-a-repository-installation-for-the-authenticated-app\n\nURL not found: https://api.github.com/repos/easystats/insight/installation"

(https://github.com/r-universe/easystats/runs/3160749319?check_suite_focus=true)

**Comment by IndrajeetPatil** [comment]
I gave the r-universe app access to `easystats` repos, so I _think_ this should be fixed now.

**Comment by strengejacke** [comment]
> For easystats .onAttach, should it check the version on r-universe instead of GH / CRAN?

I'd say no, it would lead to permanent updates for users ;-) And, we do not always increase version numbers for our dev-versions.

**Comment by IndrajeetPatil** [comment]
Can this be closed now?

**Comment by bwiernik** [comment]
think so
