### ISSUE TITLE
eating our own (`{datawizard}`) dog food

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#167]
Across packages, in documentation, we use `{dplyr}` + `{tidyr}` workflow for data wrangling that involve the very operations supported in `{datawizard}`.

It will be good to replace these instances using `{datawizard}` functions.

P.S. For those who don't get the issue title, see [this](https://en.wikipedia.org/wiki/Eating_your_own_dog_food).

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by DominiqueMakowski** [comment]
> For those who don't get the issue title

I didn't know it was a legit expression :)

We can replace them whenever we encounter them

**Comment by bwiernik** [comment]
I love realizing that American idioms aren't widespread!

**Comment by IndrajeetPatil** [comment]
Yeah, at least in the Commonwealth nations, we grow up with British spellings, idioms, phrases, etc.

**Comment by bwiernik** [comment]
Yep

**Comment by IndrajeetPatil** [comment]
Okay, so this needs to be done for 4 packages (see above), and unless someone else gets to it first, the respective maintainers should take care of it.

**Comment by IndrajeetPatil** [comment]
Done for all except _bayestestR_. Closing in favor of https://github.com/easystats/bayestestR/issues/507.

**Comment by IndrajeetPatil** [comment]
Thanks, @etiennebacher!
