### ISSUE TITLE
Replace `{dplyr}` with `{poorman}`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#168]
We don't of course import `{dplyr}` anywhere, but we do include it in `Suggests` for testing our `grouped_` functions.

It's a rather heavy dependency to download for CRAN checks, especially when we use it only for testing. I would recommend, we instead use its 0-dependency alternative called `{poorman}` (https://github.com/nathaneastwood/poorman). 

It's designed in a way that simply replacing `dplyr::` with `poorman::` should work!

- [x] correlation (https://github.com/easystats/correlation/pull/216)
- [x] datawizard (https://github.com/easystats/datawizard/commit/ec49cea542728e98af9732f5d0174f5a03df626b and https://github.com/easystats/datawizard/issues/36)
- [x] report (https://github.com/easystats/report/issues/207 and https://github.com/easystats/report/pull/209)
- [x] performance
- [x] insight (https://github.com/easystats/insight/pull/466)
- [ ] bayestestR
- [x] parameters (https://github.com/easystats/parameters/pull/633)
- [x] see (https://github.com/easystats/see/pull/205)

**Comment by strengejacke** [comment]
Yes, that sound's like a good idea.

**Comment by mattansb** [comment]
In most places we can drop dplyr all together - except for places the use `group_by`, which, interestingly enough works across poorman-dplyr!

``` r
mtcars |>
  poorman::group_by(am) |>
  dplyr::summarise(mean(cyl))
#>   am mean(cyl)
#> 1  0  6.947368
#> 2  1  5.076923
```

Cool (:

**Comment by bwiernik** [comment]
Our only other link with dplyr is via ggdist in see Suggests. ggdist uses grouped functions pretty heavily. I'll see if msjkay would be open to changing that one too

**Comment by IndrajeetPatil** [comment]
Re-opening because somehow missed 3 other packages where `{dplyr}` is still being used.

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/easystats/easystats/issues/168
