### ISSUE TITLE
why do github actions struggle so much with `{easystats}` packages?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#169]
We **constantly** run into the following error on github-actions, which I have rarely seen with other dependencies on GitHub:

```r
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/easystats/insight/contents/DESCRIPTION?ref=HEAD'
Calls: saveRDS ... github_DESCRIPTION -> download -> base_download -> base_download_headers
Execution halted
Error: Process completed with exit code 1.
```

Are we doing something non-standard? Why do we keep getting this error? 
Also, why does it disappear as mysteriously as it appear?

Every time this occurs, I keep ignoring it thinking it's only temporary, etc. But at some point, we need to figure out why so that we can avoid it once and for all.

**Comment by DominiqueMakowski** [comment]
> Every time this occurs, I keep ignoring it thinking it's only temporary

You're right, I think we all have a bit of a tendency to burry our heads in the sand when it comes to GA actions. We should maybe rewrite and streamline the ga action template

**Comment by IndrajeetPatil** [comment]
I am going to close this since with the updated GHA, this hasn't happened of late. 

Will reopen if it starts happening again.
