### ISSUE TITLE
Add CITATION.cff to repos

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#170]
now that github has enabled "prefered citations", we should add it in our repos:

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files#citing-something-other-than-software

**Comment by bwiernik** [comment]
Grumble grumble grumble proliferation of redundant standards grumble grumble grumble.

**Comment by mattansb** [comment]
Is there really a need for this?
Github already detects `inst/CITATION` files, and so all repos already have ![image](https://user-images.githubusercontent.com/35330040/134457288-801c2e27-3353-4346-a2f0-0b662fcf7f46.png)

**Comment by DominiqueMakowski** [comment]
yeah if it works then it's good :)
