### ISSUE TITLE
S3 dispatch for Suggested packages

### ISSUE THREAD

**Issue by bwiernik** [easystats/easystats#173]
## Problem

We have several functions throughout the 'verse where we have some messiness of S3 dispatch/function exporting across Suggested packages.

The two that come to mind are:
1. `pp_check()` : Currently, if the *performance* NAMESPACE is loaded after *bayesplot*/*rstanarm*/*brms*, etc., then our exported function clobbers the main `pp_check()` function from *bayesplot*, causing `"stanreg"` models to be sent to the `pp_check.glm()` method in *performance* instead.
2. *see* is a Suggested package to avoid everything depending on the *ggplot2* stack. This presents an issue with the `plot.visualisation_recipe()` method, which lives there. If the *see* NAMESPACE isn't attached, then when `plot(visualisation_recipe_object)` is called, it's dispatched to `plot.default()` and errors. 

## Potential Solution

I'm thinking about solutions to these problems. 

One option that comes to mind is we could conditionally export functions or register methods depending on whether

Per https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Registering-S3-methods, I think this might be allowable in NAMESPACE:

```r
if (!isNamespaceLoaded("bayesplot")) {
  export(pp_check)
}
if (!isNamespaceLoaded("see")) {
  S3method(plot, visualisation_recipe)
}
```

That would only export `pp_check()` if it wasn't already available from another package, and it would only export a `plot.visualisation_recipe()` method if *see* wasn't already attached. In the packages, we could add dummy methods to say "Please load 'see'" or "Please load 'bayesplot'" or whatever.

I don't see anything in the CRAN policies to prohibit this, but I'm not sure how acceptable it would be. We would also have to work around Roxygen's automtic NAMESPACE writing (I don't think it can do this automatically). We could write a custom function to handle that.

## Alternative solutions

Other options for these two cases would be:
1. Add a `pp_check.default()` method to performance that redirects to `bayesplot::pp_check()`. I think this would work? 
2. Ignore the `visualisation_recipe()` issue and just accept that that there is an opaque error message for the rare case where a user (1) calls `visualisation_recipe()` instead of `plot()` directly, (2) then tries to `plot()` that result.
2. Some other structuring of the S3 functions for `visualisation_recipe()`. For example, we could put the `plot.visualisation_recipe()` S3 method back in *datawizard* and have this the object to some function in *see* and return an error if *see* is unavailable. 
3. Move all of the `visualisation_recipe()` functions to *see* rather than individual packages. The fact that these functions related to plotting are spread around the other packages is the source of the problem here. We don't want to Import *see*, but it seems to be clear at this point that trying to keep `visualisation_recipe()` out of *see* is messy. IIRC, @DominiqueMakowski's thinking was that it was convenient to be able to keep the visualisation construction code for our package classes with located near the constructor functions for those classes. That's true, but it leads to these complications, and we already have most of the plot generation functions in *see*.

What do you folks think? I know that there has been a bunch of movement related to `visualisation_recipe()` lately, but I don't know that we have ever had a full discussion together about this function and its impacts on the across-ecosystem API. 

@strengejacke @mattansb @IndrajeetPatil

**Comment by DominiqueMakowski** [comment]
This only inspires me memes

![image](https://user-images.githubusercontent.com/8875533/132076967-7efba1bd-f40d-4726-ba14-baa77be7755f.png)
![image](https://user-images.githubusercontent.com/8875533/132076843-441f796a-5517-4349-b59e-b4d0837fcf0d.png)
![image](https://user-images.githubusercontent.com/8875533/132076888-9d60b4bd-aa6d-4818-bb7e-da42e9ba162c.png)
![image](https://user-images.githubusercontent.com/8875533/132076928-f55e885d-ba10-4b21-9339-573568b59c06.png)



> see is a Suggested package to avoid everything depending on the ggplot2 stack. This presents an issue with the plot.visualisation_recipe() method, which lives there. If the see NAMESPACE isn't attached, then when plot(visualisation_recipe_object) is called, it's dispatched to plot.default() and errors.

Couldn't this be addressed the same way we do for all the other plottings ([using nextmethod dispatch](https://github.com/easystats/bayestestR/blob/master/R/plot.R))?

**Comment by mattansb** [comment]
> pp_check() : Currently, if the performance NAMESPACE is loaded after bayesplot/rstanarm/brms, etc., then our exported function clobbers the main pp_check() function from bayesplot, causing "stanreg" models to be sent to the pp_check.glm() method in performance instead.

This sounds like it shouldn't be happening - wouldn't the `UseMethod` send it to its correct `pp_check.stanreg` function?

**Comment by strengejacke** [comment]
> see is a Suggested package to avoid everything depending on the ggplot2 stack. This presents an issue with the plot.visualisation_recipe() method, which lives there. If the see NAMESPACE isn't attached, then when plot(visualisation_recipe_object) is called, it's dispatched to plot.default() and errors.

Why is that? We usually have `plot.visualisation_recipe()` in the package where we have the related function (i.e. `visualisation_recipe()`, and then this plot-method checks if _see_ is installed, and if so, calls `NextMethod()`. The object should just have multiple classes, with the second one being `.see_visualisation_recipe`, and _see_ has `plot.see_visualisation_recipe()`

**Comment by DominiqueMakowski** [comment]
Yes, we need to add the second class `.see_visualisation_recipe`

**Comment by bwiernik** [comment]
> This sounds like it shouldn't be happening - wouldn't the UseMethod send it to its correct pp_check.stanreg function?

No, the namespace loading order affects which method matches first

**Comment by strengejacke** [comment]
@IndrajeetPatil @DominiqueMakowski can you take care of this change related to `.see_visualisation_recipe`? I think what needs to be done is 

- [ ] to move the current `plot.visualisation_recipe()` to _see_ and rename it to `plot.see_visualisation_recipe()`
- [ ] `plot.visualisation_recipe()` in _datawizard_ just checks if _see_ is installed, and if so, calls `NextMethod()`
- [ ] all functions that return an object of class `visualisation_recipe` need to add another class attribute, `see_visualisation_recipe` .

**Comment by strengejacke** [comment]
(_bump_)

**Comment by strengejacke** [comment]
@bwiernik you addressed the pp_check stuff in _performance_, I made the other changes related to `visualization_recipe()`, so can this issue be closed?
