### ISSUE TITLE
start protecting `main`/`master` branches

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#177]
After https://github.com/easystats/easystats/issues/113 is resolved and `easystats 1.0.0` is released, we should be more conservative about making changes directly to `main`/`master`. 

So it will be a good idea to protect these branches from accidentally pushing unwanted changes. And we should always go through a pull request + code review workflow before committing to these branches. You can, of course, always merge PRs yourself if you think the changes are minor (code styling, spelling checks, etc.). As organization members, we will have those privileges even if branches are protected.

For the uninitiated, you will find the option in repository `Settings`:

![image](https://user-images.githubusercontent.com/11330453/135620203-43e66947-3cd8-4c12-accb-481db33ef5aa.png)

Progress:
- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by mattansb** [comment]
Yes! Done for `effectsize`!

**Comment by IndrajeetPatil** [comment]
I have done this for all repos. All owners still have the right to push directly to the `main` branch without a PR or a code review.

With great power comes bla bla bla.... you know the drill! 😁

**Comment by strengejacke** [comment]
Can we somehow allow @vincentarelbundock to merge w/o reviews (see https://github.com/easystats/insight/pull/591#issuecomment-1186056615)?

**Comment by vincentarelbundock** [comment]
I like to develop in branches anyway, and I'm not taking personal I swear ;)

**Comment by IndrajeetPatil** [comment]
Done!

<img width="1307" alt="Screenshot 2022-07-16 at 23 00 13" src="https://user-images.githubusercontent.com/11330453/179371807-948e5333-1f11-4371-b831-bcb62fe04303.png">

**Comment by IndrajeetPatil** [comment]
<img width="1368" alt="Screenshot 2022-07-16 at 23 00 46" src="https://user-images.githubusercontent.com/11330453/179371814-641c97f8-9969-4b2f-845c-4fb1b949d060.png">

**Comment by IndrajeetPatil** [comment]
I have added the same exception also for _parameters_ and _performance_.
