### ISSUE TITLE
Installation fails with "Error: Missing commas separating Remotes"

### ISSUE THREAD

**Issue by sbibauw** [easystats/easystats#18]
I tried to install `easystats/easystats` today but it fails with following error:

```r
devtools::install_github("easystats/easystats")
# Downloading GitHub repo easystats/easystats@master
# Error: Missing commas separating Remotes: 'easystats/estimate
#	easystats/see
# 	easystats/report'
```

(R version 3.5.3 - Platform: x86_64-apple-darwin18.2.0 (64-bit) - devtools 2.0.2)

**Comment by DominiqueMakowski** [comment]
@sbibauw my bad I pushed it too fast. Should be fixed now. Thanks for reporting!!

**Comment by sbibauw** [comment]
Thank you so much! It works! And thank you for your these absolutely great packages!
