### ISSUE TITLE
r-universe libcurl issues on mac

### ISSUE THREAD

**Issue by bwiernik** [easystats/easystats#180]
I have two students for whom the r-universe repo consistently fails. So, `easystats::install_latest()` fails.

1. If I change the URL to `http://`, it works, so the issue appears to be with R's certificate store access with *libcurl*
2. If I install with the `https://` protocol with `pak::repo_add(); pak::pkg_install()`, it works, so this function seems to use its own store or another verification method.
3. If I try to install with `install.packages()` with `repos` set to another `https://` domain like, `"install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")"`, it works.
4. If I try another r-universe repo, it also fails, so it seems specifically an issue with r-universe repos.

Anyone have any idea how we might be able to fix this?

**Comment by bwiernik** [comment]
@DominiqueMakowski @IndrajeetPatil

**Comment by strengejacke** [comment]
> Anyone have any idea how we might be able to fix this?

Don't buy Apple products :-)

**Comment by DominiqueMakowski** [comment]
If it's an issue specific r-universe, maybe we could ask them perhaps they know of good solutions

**Comment by bwiernik** [comment]
Do you know whom to ask? I couldn't figure that out this afternoon

**Comment by IndrajeetPatil** [comment]
[Maybe](https://jeroen.github.io/user2021/#1) Jeroen himself: https://github.com/jeroen?

**Comment by IndrajeetPatil** [comment]
Can this be closed?

**Comment by bwiernik** [comment]
Yep, it's resolved by updating macOS to a recent version
