### ISSUE TITLE
update `install_suggested()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#181]
A number of packages are missing from respective lists:
https://github.com/easystats/easystats/blob/master/R/install_suggested.R

For example, for `{correlation}`: energy, mbend, rmcorr

**Comment by strengejacke** [comment]
You don't need that PR, as you did the changes to an old function that's no longer used. Now, the CRAN website is crawled and the suggested packages are based on the current CRAN version.

**Comment by IndrajeetPatil** [comment]
Oh, I completely missed this update!

Maybe we should move unused code to some this folder?
https://github.com/easystats/easystats/tree/master/old
