### ISSUE TITLE
have cleaner namespaces

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#182]
Currently, across packages, we have namespace import calls duplicated across multiple files. For example, in [see](https://github.com/easystats/see/commit/4de3d9cd4cb9c54ac5e00f426d744f2ae26b8aaf), we declare `#' @importFrom ggplot2 .data` 8 different times, which means if we ever decide to change it, we need to make this same change in 8 different places.

Ideally, all imports should be declared just in one place, which makes modifying it in the future easier.

Here is a good example of how to do so:
https://github.com/r-lib/usethis/blob/dde46105445384cfe534c7dc8d03b2a6416cee63/R/usethis-package.R#L1-L11

Progress:
- [ ] insight 
- [ ] modelbased
- [ ] bayestestR
- [ ] effectsize
- [ ] parameters
- [ ] performance
- [ ] correlation
- [ ] report
- [ ] see
- [ ] datawizard
- [ ] easystats

**Comment by bwiernik** [comment]
I thought this was a deliberate stylistic choice that all imports used by one of our functions should be declared next to that function?

IMO, the current style is a much safer choice because then the import is only removed once our function code is updated to not use it anymore

**Comment by IndrajeetPatil** [comment]
I would agree that having all imports in one place would be a bad idea if we were in an unstable state of development, where functions might move around a lot, and then the namespace declares should ideally move with them. But we have already moved around the needed functions in the previous cycle and are in a relatively stable state, and so this should not be an issue any more. 

That said, I am fine either way. I personally like having them in one place when close to stable release for reasons mentioned above, but if others feel queasy about it, I am happy to close this.

**Comment by strengejacke** [comment]
We don't use imports anymore, anyway, but directly call `package::function()` instead?

**Comment by strengejacke** [comment]
And otherwise, I think it makes more sense to have (possibly duplicated) imports tied to the code of the function, because if an import is used in multiple functions, you always must keep track if you deleted the last usage of that import or not, and compare it to the global import file.

**Comment by bwiernik** [comment]
Yeah, that's my thinking too.

**Comment by mattansb** [comment]
+1 to @bwiernik and @strengejacke 's points.
