### ISSUE TITLE
update dependency graph

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#184]
Once https://github.com/easystats/see/issues/203 is resolved.

This should no longer have `{rlang}` and `{ggridges}`:
https://github.com/easystats/easystats/raw/master/man/figures/depnetwork-1.png

![image](https://user-images.githubusercontent.com/11330453/140641995-f4dc669e-2928-400a-b203-5a884c134af8.png)

**Comment by mattansb** [comment]
There is actually no need to do anything - the plot should auto re-render by itself.

**Comment by IndrajeetPatil** [comment]
There is something wrong with the render-README GHA, btw. The graph you had prepared was never in README until it [knitted ](https://github.com/easystats/easystats/commit/c0a7f746cb24d5cc35fcfcaeccf313677ae28d7d) it locally on my computer and then pushed it 🤷

**Comment by mattansb** [comment]
🤷‍♂️ Isn't the GHA setup to occasionally build the README? Is it pushing to the correct branch?
