### ISSUE TITLE
create and use `{easystats}`-specific CSS/Sass template 

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#186]
This will give all our package websites a unique "easystats"-look.

And each package will also make it clear that it's part of an ecosystem and would invite users to check out other members:

For an example of such a template, see:
https://github.com/tidyverse/tidytemplate

The new template is here: https://github.com/easystats/easystatstemplate

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
Working on this here: https://github.com/easystats/easystatstemplate

Will ask for a review once I have a draft ready.

**Comment by IndrajeetPatil** [comment]
@easystats/maintainers (cc @etiennebacher) I have made the template repository [public](https://github.com/easystats/easystatstemplate) and, as an example, I am now using this template for building _datawizard_ website.

Can you please have a look at it and see if you have any feedback? Thanks.
https://easystats.github.io/datawizard/index.html

Going for a minimal theme while minimizing the number of customizations in order to not override too many of _pkgdown's_ (usually very sensible) defaults.

**Comment by etiennebacher** [comment]
Looks really cool! I particularly like the dropdown at the right of the sidebar that lists all the other easystats packages

A few bugs or changes I would make:
* list packages alphabetically in dropdown
* dropdown icon not displayed in Firefox (but doesn't appear at all in chrome)

![image](https://user-images.githubusercontent.com/52219252/177114853-a6be75f3-d11e-4db5-b12e-7b8a219f53ef.png)

* the "copy code" icon is a bit too "flashy" for me, I would put the same color as the author links for example

![image](https://user-images.githubusercontent.com/52219252/177115697-4d7e4449-3477-4094-adf1-8dab4e88d5ab.png)

**Comment by strengejacke** [comment]
This is how it looks for me (Chrome):
![image](https://user-images.githubusercontent.com/26301769/177118773-601607c7-7e10-49e0-87aa-222aa950a39c.png)

Edge (almost?) identical:
![image](https://user-images.githubusercontent.com/26301769/177118924-faac52cd-7e17-4a79-92c4-9dd55dd436a4.png)

**Comment by etiennebacher** [comment]
Apparently it's supposed to be an R icon

![image](https://user-images.githubusercontent.com/52219252/177119288-30a3457c-51b0-422a-9c14-9b308ee81173.png)

**Comment by IndrajeetPatil** [comment]
> dropdown icon not displayed in Firefox (but doesn't appear at all in chrome)

This should be fixed now. Can you please check, @etiennebacher? Remember that the webpage maybe cached, so better to check in incognito mode.

**Comment by strengejacke** [comment]
yeah, works for me now.

**Comment by etiennebacher** [comment]
also works for me, thanks

**Comment by IndrajeetPatil** [comment]
@etiennebacher I would prefer to leave the copy button color as it is now. We can revisit that later. I have addressed your other concerns.

Do you think you can take care of adding template to the rest of the packages? The process would be the same as what was done for _datawizard_.

**Comment by etiennebacher** [comment]
Hi @IndrajeetPatil, yes I can take care of this

**Comment by etiennebacher** [comment]
@IndrajeetPatil for *parameters* I couldn't find a way to keep the structure of the articles in the dropdown. Maybe you know how to do it?

**Comment by IndrajeetPatil** [comment]
Sure. You can make a PR with boilerplate changes and then I can have a look.

**Comment by IndrajeetPatil** [comment]
The PR for _parameters_ is yet to be merged but I am still marking this as done. 

@easystats/maintainers Please check the new look of the websites for your package and see if you have any feedback, stylistic or otherwise.

Thanks, @etiennebache, for assisting me on this. 🤗
