### ISSUE TITLE
Use Markdown syntax in roxygen docs: Part 2

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#187]
Follow up to https://github.com/easystats/easystats/issues/77

Super low-priority, so make these changes only as you encounter them while working on something, if you wish.

Another simple change we can make to follow markdown syntax more consistently is while creating (ordered or unordered) lists.

So, go from

```r
#' \itemize{
#'   \item ....
#'   \item ....
#'  }  
```

to

```r
#' - ....
#' - ....
```

The only exception is:

```r
#' \itemize{
#'   \item{\link[=xyz]{pkg::abc()}}
#'   \item{\link[=xyz]{pkg::abc()}}
#'   .... 
#'  }  
```
Doing so will break the internal linking in documentation.

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
Only _insight_ and _bayestestR_ remain now. Someone else can take care of those.

**Comment by IndrajeetPatil** [comment]
_bump_

**Comment by etiennebacher** [comment]
@IndrajeetPatil do you know a package/function to quickly detect all Latex commands in roxygen comments?
