### ISSUE TITLE
don't use em-dash in roxygen docs

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#188]
If you have em-dash, it might look okay in PDF manual, but looks malformed in RStudio help pages:

![image](https://user-images.githubusercontent.com/11330453/140896406-6863196c-21b7-4577-9c7a-7b07826a9197.png)

![image](https://user-images.githubusercontent.com/11330453/140896467-f5b16142-a053-4140-abba-6f1efc2b94d4.png)

So you can replace all such instances in source files by finding `—` and replacing it with `-`. 

Just to highlight the difference between em-dash and en-dash:

![chartoraw](https://user-images.githubusercontent.com/11330453/140896493-a4758f7d-714f-4e04-95ff-4e7001b82519.PNG)

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by mattansb** [comment]
How can I see if I have this in effectsize?

**Comment by IndrajeetPatil** [comment]
Hitting `Ctrl + Shift + F` in RStudio package project, and then search for `—`

![image](https://user-images.githubusercontent.com/11330453/140904694-93c3fe56-3871-4f81-946b-931654511573.png)
