### ISSUE TITLE
README - reward

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#19]
Whoever succeeds in fixing the formatting of the README page (having the logos on one row and the paragraph below) will be rewarded by an enormous amount of

**Comment by strengejacke** [comment]
Can't knit:

> Error: 'summarise_posteriors' is not an exported object from 'namespace:parameters'

**Comment by DominiqueMakowski** [comment]
I've withheld everything in dev for too long I guess

I've pushed every dev branches to master, and added two functions here in easystats, `install_easystats_latest` (install all github's masters) and `install_easystats_dev` (install all devs). That should help to have a working suite before we reach stabilisation.

**Comment by strengejacke** [comment]
well, kind of closed... you can add further `<br />` for more line breaks.
