### ISSUE TITLE
Easystat

### ISSUE THREAD

**Issue by BB1464** [easystats/easystats#191]
after installing the easystats package and then I load the library I still get the following error message when I run
easystats::install_suggested()
Error in .suggested_pkgs() : could not find function ".suggested_pkgs"

Please how can I resolve this?

**Comment by bwiernik** [comment]
What is your goal with installing the suggested packages? That will install a few hundred different stats packages--that function is mostly for our use in testing.

**Comment by BB1464** [comment]
Thank you for your response, I was reading the documentation, and I saw
that that function will help to install additional packages that will
improve the functionality of easystats that is why I choose to run that
function.




Oluwafemi Oyedele
https://statisticalinference.netlify.app/

**Comment by IndrajeetPatil** [comment]
@bwiernik We actually do encourage in the README installing these:

![image](https://user-images.githubusercontent.com/11330453/142653123-1c4ebd1c-ac29-4443-a5ba-c6b937ffbb95.png)

@BB1464 Can you please try:

```r
remotes::install_github("easystats/easystats")
```

And then refresh your R session and try again?

**Comment by BB1464** [comment]
Ok, Thank you, it's work!!!
Oluwafemi Oyedele
https://statisticalinference.netlify.app/
