### ISSUE TITLE
add social media cards 

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#192]
Go to Settings of package GitHub repo, and if you see the following, you need to upload an image with appropriate dimensions:

![image](https://user-images.githubusercontent.com/11330453/143922707-c20018b9-9d22-445f-b5c9-59e5b725accf.png)

The best example to see is `{parameter}` package template image.

![image](https://user-images.githubusercontent.com/11330453/143923136-64a79857-6aba-48dd-a036-469921d513c0.png)

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [ ] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
Great job, @DominiqueMakowski! Cards look perfect!

**Comment by IndrajeetPatil** [comment]
For reference, the cards for **GitHub repo** (and not pkgdown websites) can be checked here:
https://cards-dev.twitter.com/validator

**Comment by mattansb** [comment]
I mean, if Dom's making them.......

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Can you please also add a card for `{datawizard}`, so that this issue can be closed?

**Comment by DominiqueMakowski** [comment]
will do now, and do not hesitate to ping me over and over if i don't reply (99.99% of the time is because I miss or forget it) 😉
