### ISSUE TITLE
Switch to use Bootstrap 5 for pkgdown websites

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#193]
For how to, see as an example:
https://github.com/easystats/easystats/commit/eeb7f0a41c928d97d9ad27831ee60686c0f06803

Also, see the new look of the website. For now, we can stick to these defaults, we can revisit how to customize when we dig into https://github.com/easystats/easystats/issues/186.

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
What does this do?

**Comment by IndrajeetPatil** [comment]
`{pkgdown} 2.0` was just released, and it encourages users to switch to [Bootstrap v5.0](https://getbootstrap.com/docs/5.0/getting-started/introduction/) framework for building websites.

That's what this issue was about. 

There should be a blog post soon by Hadley detailing all the benefits of this switch, so I won't get into that here.

**Comment by IndrajeetPatil** [comment]
Here is the blogpost:

https://www.tidyverse.org/blog/2021/12/pkgdown-2-0-0/

**Comment by pdwaggoner** [comment]
Congrats @IndrajeetPatil and @strengejacke on the contributions to Bootstrap 5!

**Comment by IndrajeetPatil** [comment]
LOL, we didn't contribute to Bootstrap 5! 😅 

I think we are in acknowledgments because we created issues and I had made a couple of PRs. 
It's a really nice thing they (tidyverse and r-lib folks) do where they acknowledge contributors, big and small.

**Comment by pdwaggoner** [comment]
That is nice. And you're in the "list". That counts to me ;)

**Comment by strengejacke** [comment]
I didn't even know it exists...

**Comment by pdwaggoner** [comment]
<img width="821" alt="Screen Shot 2021-12-09 at 8 05 24 AM" src="https://user-images.githubusercontent.com/31326382/145421556-70b0ea76-c327-4279-b541-01362933016c.png">

**Comment by pdwaggoner** [comment]
There you are next to *the* Max Kuhn ;)

**Comment by bwiernik** [comment]
Daniel so productive he doesn't even know when he contributes

**Comment by strengejacke** [comment]
I reverted the change for _parameters_ and _performance_. Using the new theme, this is how pages now render:

![image](https://user-images.githubusercontent.com/26301769/146915303-c233acb4-6e34-487a-857b-e7cc2658fae2.png)

I don't think this makes people think "nice package, much have a closer look". Not sure if the line-width option is now ignored in bootstrap 5, but I would prefer using the new theme first when we have found a solution to this.

**Comment by IndrajeetPatil** [comment]
I think this can be solved by setting in the `_pkgdown.yaml` file:

```yml
code:
  width: 120
```

**Comment by IndrajeetPatil** [comment]
Let me confirm locally.

**Comment by strengejacke** [comment]
Is it just a cache issue, or wasn't the pkgdown site rebuilt in the "old" style?

https://easystats.github.io/parameters

**Comment by IndrajeetPatil** [comment]
No, it's not a cache issue. The differences you are seeing are due to change from `pkgdown 1.0` to `pkgdown 2.0`.

I think the problems we are seeing might be related to [this change](https://www.tidyverse.org/blog/2021/12/pkgdown-2-0-0/#code-display):

![image](https://user-images.githubusercontent.com/11330453/146927515-df2ac71d-128a-4f2e-ae9e-fdab1f0d6b35.png)

Also, I checked locally and this doesn't solve this issue:

> I think this can be solved by setting in the `_pkgdown.yaml` file:
> 
> ```yaml
> code:
>   width: 120
> ```

**Comment by IndrajeetPatil** [comment]
I am opening a new issue because this problem has nothing to do with bootstrap-5 CSS framework.
