### ISSUE TITLE
How to improve printing methods on pkgdown websites

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#197]
`{pkgdown}` recently had `2.0` release, which was a massive release (for important changes, see this [post](https://www.tidyverse.org/blog/2021/12/pkgdown-2-0-0/)).

The new version is creating issues for our custom printing methods. For example, here is an example from `{performance}` [homepage ](https://easystats.github.io/performance/):

![image](https://user-images.githubusercontent.com/11330453/146939978-65aa866d-cc8a-4d43-9ff0-6777705088e5.png)

We need to figure out how to get the previous behavior with the new version. If this is not possible, we need to talk to `{pkgdown}` developers and see if they can provide an option to do so. 

P.S. 
- Note that this is (most likely) not due to switching to Boostrap-5 CSS framework (cf. #193) because `{performance}` no longer [uses it](https://github.com/easystats/performance/blob/4504d3020f8a31785e0ae703a8e8069448a48dc6/_pkgdown.yml#L16-L18).
- I can reproduce this with multiple browsers, so not a browser issue.

**Comment by bwiernik** [comment]
What does it look like before?

**Comment by IndrajeetPatil** [comment]
Hmm, this is what it looked before as well (I recreated this by installing older version of pkgdown from CRAN archives):

![image](https://user-images.githubusercontent.com/11330453/146956953-2affa9a9-2525-4b86-a45b-66b4bc97c040.png)

@strengejacke Can you point to a good example code snippet that respected our printing methods but looks odd now?

**Comment by mattansb** [comment]
I think the problem is not with pkgdown - but over all with wide dfs in `insight::export_table` where rows overflow.

We should consider having `insight::export_table`'s behavior change:

- The `print.data.frame()` behavior, where `getOption("width")` determines how many columns are printed side-by-side vs one on top of the other?
- Or the `print.tibble()` behavior, where `getOption("width")` determines how many columns are shown at all.
- Other...???

**Comment by strengejacke** [comment]
> I think the problem is not with pkgdown

The problem seems to be pkgdown because you cannot allow a scroll bar for lines of length > 80. Whether your `print()` methods should print lines longer than 80 chars is another question. ;-)

**Comment by bwiernik** [comment]
I suggest we use "width" to do the print.data.frame behavior

**Comment by strengejacke** [comment]
> What does it look like before?

Like this: https://easystats.github.io/parameters/articles/model_parameters.html

**Comment by bwiernik** [comment]
Suggested solution appears to be to set the width option in the examples https://github.com/r-lib/pkgdown/issues/1447

**Comment by mattansb** [comment]
But this only solves the pkgdown problem....
I would really like to not get this type of output ☹️:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/35330040/147340611-855658a5-65d9-46f5-ae1f-c6261986d06e.png">

**Comment by bwiernik** [comment]
It's a "both, and" situation

**Comment by bwiernik** [comment]
And for compare performance, I think we also just have too many stats included by default

**Comment by strengejacke** [comment]
``` r
m_lin <- lm(am ~ hp, mtcars)
m_bin <- glm(am ~ hp, mtcars, family = binomial())

performance::compare_performance(m_lin, m_bin) |> 
  print(table_width = 60)
#> # Comparison of Model Performance Indices
#> 
#> Name  | Model |    AIC | AIC weights |    BIC | BIC weights |  RMSE
#> -------------------------------------------------------------------
#> m_lin |    lm | 49.354 |       0.113 | 53.752 |       0.058 | 0.476
#> m_bin |   glm | 45.228 |       0.887 | 48.159 |       0.942 | 0.470
#> 
#> Name  | Sigma |    R2 | R2 (adj.) | Tjur's R2 | Log_loss | Score_log | Score_spherical |   PCP
#> ----------------------------------------------------------------------------------------------
#> m_lin | 0.492 | 0.059 |     0.028 |           |          |           |                 |      
#> m_bin | 1.172 |       |           |     0.072 |    0.644 |    -6.099 |           0.057 | 0.552


performance::compare_performance(m_lin, m_bin) |> 
  print(table_width = "auto")
#> # Comparison of Model Performance Indices
#> 
#> Name  | Model |    AIC | AIC weights |    BIC | BIC weights |  RMSE | Sigma |    R2
#> -----------------------------------------------------------------------------------
#> m_lin |    lm | 49.354 |       0.113 | 53.752 |       0.058 | 0.476 | 0.492 | 0.059
#> m_bin |   glm | 45.228 |       0.887 | 48.159 |       0.942 | 0.470 | 1.172 |      
#> 
#> Name  | R2 (adj.) | Tjur's R2 | Log_loss | Score_log | Score_spherical |   PCP
#> ------------------------------------------------------------------------------
#> m_lin |     0.028 |           |          |           |                 |      
#> m_bin |           |     0.072 |    0.644 |    -6.099 |           0.057 | 0.552
```

<sup>Created on 2021-12-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
@strengejacke Can this be closed?

**Comment by strengejacke** [comment]
yeah, we need to wait for the pkgdown update in order to resolve this issue, however, I'm not sure which setting will control the output width. Maybe vertical scrolling is enabled by default for code chunks, I guess.

**Comment by IndrajeetPatil** [comment]
> we need to wait for the pkgdown update in order to resolve this issue

It's already on CRAN:
https://cran.r-project.org/web/packages/pkgdown/index.html

**Comment by strengejacke** [comment]
ah, cool! and seems to work.
