### ISSUE TITLE
Release cycle 1/2022

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#199]
Ok, I think we can/should push some updates to CRAN. First will be _insight_, which, however, breaks multiple packages and thus requires updates in time. Here's a list of affected packages and whether fixes are prepared.

## "internal" packages
- [x] parameters (prepared for update)
- [x] modelbased (@DominiqueMakowski - I think the main issue related to https://github.com/easystats/insight/issues/469 is fixed (https://github.com/easystats/modelbased/commit/b1e2b7f60a5e4e787f974c346e38658845cacd51), waiting for checks of _modelbased_ to pass. Is there anything else you or @bwiernik need to do before submission?)

## "external" packages
- [x] marginaleffects (@vincentarelbundock, prepared for update)
- [x] statsExpression (@IndrajeetPatil, prepared for update)

See revdep-issues here: https://win-builder.r-project.org/incoming_pretest/insight_0.15.0_20220106_100612/reverseDependencies/summary.txt

**Comment by strengejacke** [comment]
_insight_ is on CRAN - now it's up to you to make sure to safely retain your packages on CRAN :-)

**Comment by vincentarelbundock** [comment]
Thanks for all your work on this!

**Comment by strengejacke** [comment]
Next packages are:

- [ ] parameters
- [ ] effectsize
- [ ] performance
- [ ] see
- [ ] report
- [ ] correlation (?)

**Comment by strengejacke** [comment]
what about _correlation_, @IndrajeetPatil ?

**Comment by IndrajeetPatil** [comment]
Punting it to the maintainer @bwiernik 😉

**Comment by strengejacke** [comment]
I'm not sure, but I _think_ that some of the newer plots (https://easystats.github.io/see/articles/correlation.html) only work with the current GitHub, but not CRAN version of _correlation_, right?

**Comment by IndrajeetPatil** [comment]
`{report}` is going to be archived on the 30th, so the next one should be that one.

**Comment by strengejacke** [comment]
@DominiqueMakowski, that's something for you, right?

**Comment by IndrajeetPatil** [comment]
We are on it: https://github.com/easystats/report/issues/214

There is only issue that needs to be resolved, and then we are good to go.

**Comment by IndrajeetPatil** [comment]
> thanks, package datawizard_0.2.3.tar.gz is on its way to CRAN.

**Comment by strengejacke** [comment]
What about _correlation_, @bwiernik?

_insight_ needs to be updated:

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_insight.html>.
> 
> Please correct before 2022-02-28 to safely retain your package on CRAN.

**Comment by bwiernik** [comment]
I'll get it submitted today

**Comment by bwiernik** [comment]
> Dear maintainer,
> 
> thanks, package correlation_0.8.0.tar.gz is on its way to CRAN.
>  
> Best regards,
> CRAN teams' auto-check service

**Comment by strengejacke** [comment]
_see_ updated on CRAN. Now only _performance_ is missing in this release cycle. Not sure how urgent this is? There are some open issues that would be great to be resolved.

**Comment by strengejacke** [comment]
@DominiqueMakowski will submit _insight_ today (if all checks pass), as requested by CRAN (see https://github.com/easystats/easystats/issues/199#issuecomment-1038805094). This update will include `get_datagrid()`, which is a replacement of `visualization_matrix()`. I suggest using get_datagrid instead of vis-matrix in _modelbased_, because it already fixed some issues and included some improvements over vis-matrix. We probably should use vis-matrix as an alias in _modelbased_, though.

**Comment by bwiernik** [comment]
Great! And no UK/US spelling discrepancies with the name!

**Comment by IndrajeetPatil** [comment]
@strengejacke Only _performance_ update is remaining for this release cycle, right? Are you thinking of submitting it soon?

**Comment by DominiqueMakowski** [comment]
> I suggest using get_datagrid instead of vis-matrix in modelbased, because it already fixed some issues and included some improvements over vis-matrix. 

Yes, I will give it a look tomorrow!

**Comment by strengejacke** [comment]
_modelbased_ is still missing, will be removed from CRAN soon (https://github.com/easystats/modelbased/issues/171)

**Comment by strengejacke** [comment]
> > I suggest using get_datagrid instead of vis-matrix in modelbased, because it already fixed some issues and included some improvements over vis-matrix.
> 
> Yes, I will give it a look tomorrow!

See https://github.com/easystats/insight/issues/509, I would wait with working on this after submitting _modelbased_ to CRAN.

**Comment by IndrajeetPatil** [comment]
@strengejacke _modelbased_ is on CRAN.

**Comment by strengejacke** [comment]
I think we can close this round. I would like to skip _performance_ for this round, because there are too many dependencies with the latest changes in _insight_ and _see_, and - although _performance_ hasn't been updated for a longer time - would wait for April or so (i.e. the next round).

**Comment by IndrajeetPatil** [comment]
Wish not granted, Daniel 😅

https://github.com/easystats/performance/issues/396
