### ISSUE TITLE
Add image banners to all repo 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#20]
https://twitter.com/github/status/1118562875830882304

Let's start by performance as I expect some tweets soon

**Comment by strengejacke** [comment]
This is some of these thechnical things I don't understand due to my advanced age...

**Comment by DominiqueMakowski** [comment]
I'll try adding such banners to the packages tomorrow, so it's nicely displayed when we post links on twitter

**Comment by DominiqueMakowski** [comment]
- [ ] insight
- [ ] bayestestR
- [x] performance
- [ ] parameters
- [ ] report
- [ ] estimate
- [ ] correlation
- [ ] see
- [ ] easystats

**Comment by strengejacke** [comment]
_bump_
