### ISSUE TITLE
Attending the `TODO`s

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#202]
There are almost 100 `TODO` items scattered across our organization's codebase! 👀  

https://github.com/search?q=org%3Aeasystats+TODO&type=code

Some of them seem quite outdated. Please check the TODOs in package(s) you are maintaining and see if some of them can already be removed. 

We can take stock of TODOs once a year like this to make sure that they don't pile up to an insurmountable amount. 

Progress tracker:

- [ ] insight 
- [ ] modelbased
- [ ] bayestestR
- [x] effectsize
- [ ] parameters
- [ ] performance
- [ ] correlation
- [ ] report
- [ ] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by IndrajeetPatil** [comment]
_bump_

**Comment by strengejacke** [comment]
> _bump_

I just added some todo's to _insight_ 😄

**Comment by IndrajeetPatil** [comment]
Haha

It's okay to add new ones. The issue just about making sure that there aren't any outdated, already resolved TODOs.

**Comment by strengejacke** [comment]
btw, I installed a TODO / NOTE highlighter extension, will never miss those again:

![image](https://user-images.githubusercontent.com/26301769/183958518-0c526722-65d6-4d0e-9c69-2d7994aef3f3.png)

**Comment by IndrajeetPatil** [comment]
Yes, I love [it](https://www.linkedin.com/posts/indrajeet-patil-397865174_coding-programming-visualstudiocode-activity-6916741110765682689--oiv?utm_source=linkedin_share&utm_medium=member_desktop_web) as well :)
