### ISSUE TITLE
userR! 2022

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#207]
What would you say, does it make sense to submit an abstract for a regular talk on our ecosystem?

https://user2022.r-project.org/participate/call-for-abstracts/

**Comment by bwiernik** [comment]
Sure

**Comment by IndrajeetPatil** [comment]
Yepp, sounds good.

**Comment by pdwaggoner** [comment]
Yeah!

**Comment by DominiqueMakowski** [comment]
that'd be nice

**Comment by IndrajeetPatil** [comment]
Closing this now, since the abstract submissions are now closed.

@strengejacke Did you end up submitting something about _easystats_?

**Comment by strengejacke** [comment]
no... 😞

**Comment by IndrajeetPatil** [comment]
A few other upcoming options:
