### ISSUE TITLE
Always suggest updating pull request branches

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#212]
Makes it less painful for newcomers to catch up with changes in `main` or `master` if it's taking a while for the PR to be merged: 

![image](https://user-images.githubusercontent.com/11330453/154641993-395e99e2-9921-4a5b-970b-ac6b5f0f6bc7.png)

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by mattansb** [comment]
Oh, that's good!

**Comment by bwiernik** [comment]
Thanks Indra!
