### ISSUE TITLE
docs, roxygen

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#216]
When you look at the help page `?model_parameters.default`, you see that arguments "keep" and "drop" are combined in the description (intended). When you look at `?model_parameters.merMod`, which inherits `@inheritParams model_parameters.default`, these are two separate arguments with identical description. why?

Same btw here:

https://easystats.github.io/parameters/reference/model_parameters.default.html
https://easystats.github.io/parameters/reference/model_parameters.merMod.html

**Comment by IndrajeetPatil** [comment]
I think it's the same as this issue:

https://github.com/r-lib/roxygen2/issues/826
