### ISSUE TITLE
New member: Mattan

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#22]
This issue just to warmly welcome @mattansb to easystats 🎉 

Just to contextualise a bit (we should write down our "mission" somewhere, - once (*if*) we defined it ☺️), easystats is a work in progress project, with quite an open and collaborative spirit. It is mainly focused around building tools surrounding statistical models (currently mainly regressions, - but we hope to expand that), with an ecosystem of packages designed to work together (but supporting different aspects, such as extraction, computation or formatting of things). That being said, the future is yet to be shaped.

Currently, part of what makes easystats what it is is a focus on user experience (and especially non-programmers). We try to put some thoughts into the functions' design, names, argument names etc. to maximize clarity, intuitiveness, and accessibility.

It seems from your packages like your interest lies more in the Bayesian approach. However, feel free to share your other interests, skills, wishes and dreams, so we can spam-ping you in possibly relevant issues 😉.

Also, you might want to "watch" (follow) all the easystats repos, to be notified of what's going on, as we usually work in parallel :) Do not hesitate to comment on things if you have any suggestions or thoughts.

@strengejacke @pdwaggoner

**Comment by mattansb** [comment]
Hi all! Happy to be here!

I'll share a bit about myself - I am a PhD student in neuro-developmental-cognitive psychology (I specialize in EEG and ERP data analysis), at Ben-Gurion University (Israel). I also *enjoy* learning and teaching statistics (my adviser keeps reminding me my PhD is *not* in statistics) and I teach / TA nearly all of the BA/MA stats/research methods courses, in some of which I incorporate `R` use.

Excited about this collaboration! Thanks for having me!

**Comment by DominiqueMakowski** [comment]
Truth is, I've also encountered several senior scientists that didn't get why psychologists or neuroscientists, i.e., non-programmers and non-statistician, would engage and spend so much time in some obscure coding related to some weird statistics. "Just run the ANOVAs and write the paper!". For them, it was kind of like wasting time on a hobby... 

However, times are changing, and it seems that these skills are getting more and more recognized and valued in academia, especially with the rise of the open science movement. Also, do we need to remind the very close historical relationship between history and psychology? So don't worry and keep up doing what you like (as long as it doesn't jeopardize your PhD of course 😅)
