### ISSUE TITLE
Release Cycle "Spring is Coming"

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#221]
The next days, I would like to start to submit some updates, in particular _performance_, that hasn't been updated for a longer time.

- [x] insight
- [x] datawizard
- [x] modelbased
- [x] performance
- [x] see
- [x] bayestestR

_bayestestR_ has only received minor updates, so I don't think it's very urgent, or? Thought it hasn't been updated on CRAN for about 20 weeks now.

Regarding _insight_, please don't add larger features now, to make sure these we don't have "untested" features in the forthcoming update.

**Comment by IndrajeetPatil** [comment]
I think we should also update _parameters_ in this cycle.

Given the significant speed-up in the workhorse function, which is used by thousands of people directly or indirectly thousands of times, if you add all the saved milliseconds, releasing early sums to saving a significant amount of computing time.

**Comment by strengejacke** [comment]
_parameters_ was just submitted to CRAN, and the main benefit related to speed improvement comes from _insighjt_, so we should be ok not submitting _parameters_ now.

**Comment by IndrajeetPatil** [comment]
Perfect!

**Comment by strengejacke** [comment]
I just looked at the past commits and I think, the _complete_ performance improvement is just in _insight_.

**Comment by IndrajeetPatil** [comment]
I think _datawizard_ should also be part of this cycle. 

A _lot_ has changed, and it will be good to get the newer version on the CRAN soon. We can then update its reverse dependencies to the API changes.

**Comment by strengejacke** [comment]
@IndrajeetPatil From _insight_ revdep check, I get for _datawizard_:

```
Last 13 lines of output:
  == Failed tests ================================================================
  -- Failure (test-distributions.R:5:5): distributions ---------------------------
  kurtosis(x)$Kurtosis (`actual`) not equal to -0.3204763 (`expected`).
  
    `actual`: -0.1
  `expected`: -0.3
  -- Failure (test-distributions.R:7:5): distributions ---------------------------
  as.numeric(smoothness(x, "diff")) (`actual`) not equal to 0.919 (`expected`).
  
    `actual`: 1.2
  `expected`: 0.9
  
  [ FAIL 2 | WARN 0 | SKIP 24 | PASS 314 ]
  Error: Test failures
```

However, not sure how this can be related to _datawizard_? Maybe due to having other easystats package versions than those on CRAN?

**Comment by IndrajeetPatil** [comment]
Can you check by setting _datawizard_ to use GitHub version of _insight_ if the tests fail? Or I can do this after office hours.

**Comment by strengejacke** [comment]
The package is downloaded from CRAN (which makes sense for revdep checks), so I'm not sure if it can be tested against GitHub. I'm using `tools::check_packages_in_dir()`.

**Comment by strengejacke** [comment]
> Or I can do this after office hours.

It's not urgent, I think, was just curious how this could happen?

**Comment by strengejacke** [comment]
_insight_ submission, revdep issues:

- [ ] https://github.com/vincentarelbundock/marginaleffects/issues/229
- [ ] https://github.com/easystats/modelbased/issues/178
- [ ] https://github.com/vincentarelbundock/modelsummary/issues/452

**Comment by strengejacke** [comment]
_insight_ is submitted, so please no major changes to the _master_ branch right now.

**Comment by bwiernik** [comment]
Redo the entire *insight* API right now, got it

**Comment by strengejacke** [comment]
![damn you](https://user-images.githubusercontent.com/26301769/159789355-10cdeb5e-dee2-4766-8557-e5fdab16e362.gif)

**Comment by IndrajeetPatil** [comment]
_insight_ and _datawizard_ are on CRAN.

_modelbased_ needs to be updated to fix breakages caused by the _datawizard_ update (cc @DominiqueMakowski).

**Comment by strengejacke** [comment]
_performance_ is on CRAN. _see_ will be submitted the next days, so we have the new `check_model()` features complete.

**Comment by strengejacke** [comment]
Not sure if you would like / we need to submit _correlation_? (I guess not)
So I'm closing this, all package updates are om CRAN now.
