### ISSUE TITLE
`R 4.2`/summer break release round?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#224]
Should we do a new round of releases, either for R 4.2 or for enjoying the summer holidays without headache? 😅

I definitely need newer versions _insight_, _parameters_, and _datawizard_ to update any of my packages. 
And, we anyway need to update _bayestestR_ (https://github.com/easystats/bayestestR/issues/526).
We will additionally need to update _modelbased_ and _performance_ for failing checks:

``` r
easystats::CRAN_checks()
#> insight     2 Notes
#> datawizard  1 Note
#> bayestestR  10 Notes
#> performance 1 Error, 2 Notes
#> parameters  1 Note
#> effectsize  Ok
#> modelbased  1 Error
#> correlation Ok
#> see         Ok
#> report      Ok
```

<sup>Created on 2022-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

What do you think?

It has been at least over a month since the last release for all packages, so shouldn't be an issue from the CRAN side either:

``` r
easystats:::on_CRAN()
#> insight     4.6 weeks
#> datawizard  4.4 weeks
#> bayestestR  26.0 weeks
#> performance 4.4 weeks
#> parameters  7.3 weeks
#> effectsize  13.4 weeks
#> modelbased  4.3 weeks
#> correlation 10.7 weeks
#> see         4.3 weeks
#> report      9.6 weeks
```

<sup>Created on 2022-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

- [x] insight
- [x] datawizard
- [x] parameters
- [x] effectsize
- [x] modelbased
- [x] correlation
- [ ] report

**Comment by strengejacke** [comment]
_bayestestR_ is submitted. _insight_ is ready to be submitted, minor issues (like https://github.com/easystats/insight/issues/497) can be resolved later. _datawizard_ is generally ready to be submitted after _insight_, but we should probably coordinate with @mattansb and check whether we can resolve https://github.com/easystats/effectsize/issues/439 in this submission round (i.e. merge https://github.com/easystats/datawizard/pull/158, prepare _effectsize_ and then submit both _datawizard_ and _effectsize_).

**Comment by IndrajeetPatil** [comment]
Sounds like a plan!

**Comment by strengejacke** [comment]
Errors for _performance_ and _modelbased_ are due to glmmTMB, nothing we need to do from our side. Since _modelbased_ has no changes since the last CRAN update (which was very recently, I think), _modelbased_ can be skipped. _performance_ has no critical issues, so we might update, but it's not very urgent.

**Comment by mattansb** [comment]
I also suggest completing the migration of standardize_parameters to parameters in this round.

**Comment by vincentarelbundock** [comment]
out of curiosity, @strengejacke , do you think insight will be released before the 14th? I got one of those infamous Ripley emails for one of my packages 😓

**Comment by strengejacke** [comment]
Once you respond to https://github.com/easystats/insight/issues/497#issuecomment-1115300085, it's ready to submit.

**Comment by strengejacke** [comment]
> We could already decide on the additional argument now, even if it has no function yet (because we have satterthwaite for now only for predictions)? Then you can better "plan" or anticipate forthcoming changes in insight for your packages?

**Comment by vincentarelbundock** [comment]
> > We could already decide on the additional argument now, even if it has no function yet (because we have satterthwaite for now only for predictions)? Then you can better "plan" or anticipate forthcoming changes in insight for your packages?

I'm fine with following the `insight` release schedule for now. My package is also in very active development, so "planning ahead" and stability of the interaction with `insight` are not a major concern (for now!!!).

**Comment by strengejacke** [comment]
@IndrajeetPatil Running revdep checks, don't have the logs yet, but it seem _insight_ will break _ggstatsplot_ - can you check?

**Comment by IndrajeetPatil** [comment]
Already fixed it :)

**Comment by IndrajeetPatil** [comment]
I will submit both _statsExpressions_ and _ggstatsplot_ to CRAN once _insight_, _parameters_, and _datawizard_ are on CRAN.

**Comment by strengejacke** [comment]
oh no, statsExpression is not yet revdep-checked, so this will break, too? (of course it will, how could it be otherwise...)

**Comment by mattansb** [comment]
@IndrajeetPatil I suggest waiting for effectsize as well (see current PR there).

**Comment by mattansb** [comment]
*effectsize* is ready https://github.com/easystats/effectsize/pull/447 - waiting for *parameters* and *datawizard*

**Comment by strengejacke** [comment]
currently still waiting for _insight_... 🙄

**Comment by IndrajeetPatil** [comment]
@strengejacke The _insight_ (0.17.1) tests for _glmmTMB_ are failing on macOS-arm64:
https://cran.r-project.org/web/checks/check_results_insight.html

Is this a _glmmTMB_ issue?

**Comment by vincentarelbundock** [comment]
> @strengejacke The _insight_ (0.17.1) tests for _glmmTMB_ are failing on macOS-arm64: https://cran.r-project.org/web/checks/check_results_insight.html
> 
> Is this a _glmmTMB_ issue?

This is very weird. The test passes on github and on my computer. Line 24 is just fitting the model. At first glance it doesn't seem to have anything to do with `insight`.

**Comment by IndrajeetPatil** [comment]
Thanks for checking, @vincentarelbundock! 

Maybe it's just a temporary issue that might disappear on its own. Let's see.

**Comment by strengejacke** [comment]
That's a TMB resp. glmmTMB issue.

**Comment by IndrajeetPatil** [comment]
Alright, *datawizard* update is on CRAN.

Next up: _parameters_, and then _effectsize_.

**Comment by IndrajeetPatil** [comment]
_datawizard_ binaries are built for Windows.

**Comment by strengejacke** [comment]
These are not win-builder, but I think that doesn't matter. I guess I need to run tests for _marginaleffects_ on GitHub only, see https://github.com/easystats/parameters/issues/713

**Comment by strengejacke** [comment]
_parameters_ submitted

**Comment by strengejacke** [comment]
Ok, needs some fixing... I suggest that everyone who wants to submit to CRAN, also runs checks with `_R_CHECK_DEPENDS_ONLY_: true`, else you will need to resubmit many times.

**Comment by strengejacke** [comment]
hm, there's a new roxygen bug. When inheriting params from other functions that are comma separated, this no longer works.

e.g. this is an argument in `model_parameters.htest` and was inherited by `model_parameters.BFBayesFactor`, now this no longer works:

```r
#' @param cramers_v,phi Compute Cramer's V or phi as index of effect size.
#'   Can be `"raw"` or `"adjusted"` (effect size will be bias-corrected).
#'   Only applies to objects from `chisq.test()`.
```

**Comment by IndrajeetPatil** [comment]
Yikes.

**Comment by strengejacke** [comment]
Ok, all no-suggest issues should be fixed, running final regular tests again, if all pass, I'll re-submit.

**Comment by IndrajeetPatil** [comment]
Any update on _parameters_ submission, @strengejacke? Did it make it to the reverse dependency check yet?

**Comment by IndrajeetPatil** [comment]
@bwiernik You should have received an email about _correlation_ submission. Hopefully, it passes incoming CRAN checks.

**Comment by bwiernik** [comment]
Done thanks

**Comment by bwiernik** [comment]
*correlation* on its way to CRAN

**Comment by IndrajeetPatil** [comment]
_parameters_ update 😿

![4f15ed2867a62dac1531dd16e302b95b](https://user-images.githubusercontent.com/11330453/169786996-a4f340b5-eae4-4105-a092-8f16fa47e233.gif)

**Comment by strengejacke** [comment]
Yeah, still under manual inspection. Mail from Friday, 11:02am

> Dear maintainer,
>  
> package parameters_0.18.0.tar.gz has been auto-processed.
> The auto-check found additional issues for the *last* version released on CRAN:
  noSuggests <https://www.stats.ox.ac.uk/pub/bdr/noSuggests/parameters.out>
> CRAN incoming checks do not test for these additional issues.
> Hence please reply-all and explain: Have these been fixed?

My reply 21 minutes later:

> Dear CRAN team,
> we also ran the checks with _R_CHECK_DEPENDS_ONLY_=true and all no-suggests issues should be resolved.

There are some packages in the manual inspection queue, maybe they can take of this the next days (https://r-hub.github.io/cransays/articles/dashboard.html).

**Comment by IndrajeetPatil** [comment]
_parameters_ is on CRAN 😮‍💨

@mattansb _effectsize_ is next, right?

**Comment by IndrajeetPatil** [comment]
We should also update _report_ for this cycle; it has been a while since it was updated.

**Comment by IndrajeetPatil** [comment]
*modelbased* is on CRAN.

Next up is _report_, but I think we need to resolve a few issues first before we can submit it.

**Comment by IndrajeetPatil** [comment]
I don't think _report_ will be updated on any time soon, nor is it necessary to do so. Thus, this release cycle is complete.
