### ISSUE TITLE
pkgdown: no arguments in function reference

### ISSUE THREAD

**Issue by etiennebacher** [easystats/easystats#229]
I didn't do a complete list, but in some packages, arguments are not there in function reference. Examples:

* insight:
![image](https://user-images.githubusercontent.com/52219252/171819164-4cf58b01-14ae-48b1-9495-7ebe472ce33f.png)

* parameters
![image](https://user-images.githubusercontent.com/52219252/171819266-602a6a00-9342-4701-b72b-967b377014fe.png)

This is a pkgdown (or GHA) issue because arguments are present in `.Rd` files.

**Comment by IndrajeetPatil** [comment]
I think this issue is already resolved. I can see the arguments for the functions you have snapshotted here.

Probably it was just a temporary issue with _pkgdown_ that had introduced this.
