### ISSUE TITLE
Informative, user-friendly and unified error messages

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#23]
Originally from [here](https://github.com/easystats/bayestestR/pull/79). 

One of the most common error in easystats in the stopping related to the absence of a necessary package. Ideas for a template of this error can be:

`stop("This function requires the package 'X' to be installed. Please install by running 'install.packages(X)' and run the function again ;-)")`

**Comment by mattansb** [comment]
For readability (and usability) I suggest:
``` r
stop("This function requires the package 'X' to be installed.\nPlease install by running 'install.packages(\"X\")' and run the function again ;-)")
#> Error: This function requires the package 'X' to be installed.
#> Please install by running 'install.packages("X")' and run the function again ;-)
```

**Comment by pdwaggoner** [comment]
For my packages, I just copied Hadley Wickham (usually a safe strategy):

`stop("Package \"X\" needed for this function to work. Please install it.")`

**Comment by strengejacke** [comment]
I vote for @pdwaggoner suggestion, as the word "install" only appears once (and not three times in two sentences).

**Comment by mattansb** [comment]
I second that!

**Comment by DominiqueMakowski** [comment]
True true, but I liked the idea of providing directly the install code to run 😬 

maybe:

`stop("Package \"X\" needed for this function to work. Please run 'install.packages(X)'.")`

so the user can simply copy paste the thing? 

That's a super minor thing though, I am also okay with Hadley's holy Word :)

**Comment by pdwaggoner** [comment]
Ha! Hadley's holy word aside, while its a useful place to start, I like the idea of making this our own as well in line with @DominiqueMakowski suggestion. While the assumption could be made that if they're using our packages then they should already know how to install a package, I like the idea of customizing the warning message for our purposes and goals (i.e., making stats in R easy; this makes good sense to me)

**Comment by DominiqueMakowski** [comment]
Now that I think of it, the easiest way would be to offer the possibility to automatically install the thing, similarly to what caret or other packages do.

`"Package \"X\" needed for this function to work. Press ENTER to install or ESCAPE to abort."`

**Comment by strengejacke** [comment]
I think such user interaction is more dangerous than useful. Imagine this happens when running scripts, tests, vignettes, markdowns, ... Scripts are frozen until user does something and no error message or whatever is shown.

I do not recommend such actions. And if users don't know how to install a package, they can ask for help somewhere or maybe they're not our (or R's) target group anyway ;-)

**Comment by DominiqueMakowski** [comment]
Mmmh that's true, although that's why there is the [interactive](https://www.rdocumentation.org/packages/base/versions/3.6.0/topics/interactive) state. Usually, the user is prompted and asked to respond only if interactive() == TRUE. Else, the traditional `stop` would occur. Do you think it's not a sufficient safeguard against potential issues related to user input?

**Comment by strengejacke** [comment]
We _could_ indeed offer this, however, in my experience, in most cases you need to restart the R session because some namespaces are loaded, or installation fails etc. That's why I personally would say a message is enough.

**Comment by DominiqueMakowski** [comment]
> in most cases you need to restart the R session

so true 😩 So yeah now I agree. Still, returning the right install code so that the user can just copy-paste seems useful (I've used that myself quite a lot)

**Comment by IndrajeetPatil** [comment]
I think this can be closed?
