### ISSUE TITLE
Make a "development dashboard" for the easystats ecosystem?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/easystats#231]
Hello, I think it would be nice to have a single page that gathers information about the various bugs / PRs / code coverage, etc. for all easystats packages. I saw that some orgs have created some dashboards for this, in particular:

* [tidyverse dashboard](https://connect.rstudioservices.com/tidyverse/dashboard/tidyverse_dashboard.html)
* [thinkR-open dashboard](https://thinkr-open.github.io/thinkrdashboard/thinkr_dashboard.html) (inspired by the tidyverse one)

I copied the one by thinkR to see what it would look like for easystats. If you want to take a look, you can just clone [this repo](https://github.com/etiennebacher/dashboard) and knit `dashboard.Rmd`. Note that I don't have access to the codecov token so the coverage is not displayed in the output.

What do you think about this?

**Comment by DominiqueMakowski** [comment]
sounds good!

**Comment by strengejacke** [comment]
the examples look nice! I think let's try this, if it's not too much work (for you). :-)

**Comment by strengejacke** [comment]
> Note that I don't have access to the codecov token

@IndrajeetPatil Any ideas?

**Comment by etiennebacher** [comment]
Here's an example: https://etiennebacher.github.io/dashboard/dashboard.html

I removed a lot of things from the dashboard mentioned above because I don't think they're important/interesting, but if you want to add something, let me know.

(I could get the codecov coverage without the token)

**Comment by IndrajeetPatil** [comment]
This looks great, @etiennebacher! Thanks a lot for working on this. 🙂

If others agree, I can create a new repo in the organization and you can push the code to it.

**Comment by etiennebacher** [comment]
Sure, or maybe I can just transfer ownership to easystats (I guess the admin will have to approve this transfer)

**Comment by IndrajeetPatil** [comment]
Sure, if that can work, then that would be even better.

**Comment by etiennebacher** [comment]
Done, I think it worked. You can just modify the details and the link in easystats/dashboard

**Comment by strengejacke** [comment]
So where's the dashboard now?

**Comment by IndrajeetPatil** [comment]
https://github.com/easystats/dashboard

**Comment by strengejacke** [comment]
Yeah, just found it: https://easystats.github.io/dashboard/dashboard.html

**Comment by etiennebacher** [comment]
fyi there's now a tab summarizing all open PRs
