### ISSUE TITLE
Re-assess which soft dependencies in `Suggests` are really needed

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#237]
I feel like we are being a bit too cavalier about which dependencies we are including in `Suggests` just because they are not hard dependencies. But they are still downloaded on CI/CD and on CRAN machines, so we need to scrutinize once if we really need everything that we are currently listing in `Suggests`.

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
I looked at pkgs _insight_, _parameters_, _performance_ and _see_, and I think the suggested packages are fine. Either required for tests, vignettes or functionality.

**Comment by IndrajeetPatil** [comment]
Only _bayestestR_ remains.

Can either @strengejacke or @mattansb please have a look at this? It's the codebase I am the least familiar with.

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by bwiernik** [comment]
For bayestestR;

1. We can replace *ggridges* with *ggdist*
2. Why do we have plotting functions in *bayestestR* itself rather than in *see*?
3. We can replace *GGally* with *posterior*

**Comment by strengejacke** [comment]
- we don't have plotting functions in _bayestestR_, I think it's for the examples (e.g. `?bayestestR::cwi`)
- _ggridges_ seems to be no longer used anywhere
- _bridgesampling_ is used in `.bayesfactor_models_stan_REG`
- for _rstan_, we only use `rstan::summary()` - not sure if _posterior_ can replace this?
- we could rewrite the code in the vignettes to drop _poorman_

**Comment by IndrajeetPatil** [comment]
Created a new [issue](https://github.com/easystats/bayestestR/issues/550) to track this.

The rest of the suggestions have already been taken care of.
