### ISSUE TITLE
Remove `{spelling}` from `Suggests`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#239]
`{spelling}` is a rather heavy dependency in terms of installation time because it relies on compiled code. 

We actually don't need to run the spelling check on every single commit. We can run `devtools::spell_check()` once in a while to see if there are any spelling mistakes and correct them. Additionally, recent versions of RStudio IDE also come equipped with a spell checker. So I don't think this check is worth an additional dependency anymore.

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
@etiennebacher Do you want to take this up?

Should be straightforward.

**Comment by bwiernik** [comment]
If we use the devtools::release() function, that runs spell checks
