### ISSUE TITLE
Bump minimum R version to `3.5`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#240]
This came out of discussion at #200. 

Like _tidyverse_, I think we can support only the last four R releases. This would relieve us of testing packages on GHA on older R versions. 

It has been over 5 years since `R 3.4` came out (2017-04-21), so I think it's fine to not support it and bump the minimum needed R version.

Does anyone see any issues with that?

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
I think 3.5 is ok. Most of the "foreign" packages that depend on our packages have minimum dependency R 3.5 or higher.

**Comment by bwiernik** [comment]
Agreed

**Comment by IndrajeetPatil** [comment]
Note to self: bump the _easystats_ meta-package version after this change and make a note in `NEWS`.
