### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#241]
Currently, we have a mix of `main` and `master` as default branches. In the interest of having standardized workflows, we should stick to one.

So, all repos with `master` as the default branch should rename them to `main` branch.

See this helper function: https://usethis.r-lib.org/reference/git-default-branch.html

Note to self: Make sure `codecov` stays in sync after this change.

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by IndrajeetPatil** [comment]
I have renamed the default branch for _easystats_ repo.

**Comment by IndrajeetPatil** [comment]
Done for _correlation_. Delete local copy and clone again if needed.

**Comment by IndrajeetPatil** [comment]
@easystats/maintainers Please make sure not to restore the `master` branch in repos where `main` is the default branch. Otherwise, things will get really confusing. Just nuke your local clone and clone again to be safe.

**Comment by strengejacke** [comment]
Done this for _performance_ now, let's see if it worked.

**Comment by strengejacke** [comment]
Is it better to create a new branch and name it "main", or just to rename master?

**Comment by IndrajeetPatil** [comment]
I've been renaming the default branch from  `master` to  `main`.

**Comment by IndrajeetPatil** [comment]
<img width="326" alt="Screenshot 2022-06-30 at 09 20 30" src="https://user-images.githubusercontent.com/11330453/176617246-76c66781-4001-4320-9039-c3ef9de5b1bf.png">
<img width="1348" alt="Screenshot 2022-06-30 at 09 21 19" src="https://user-images.githubusercontent.com/11330453/176617255-be2772b4-8bba-47c4-8639-5116d52cc074.png">

**Comment by IndrajeetPatil** [comment]
I have done this for _datawizard_. Please clone again.

**Comment by IndrajeetPatil** [comment]
I have done this for _bayestestR_ and _modelbased_. Please clone again.
