### ISSUE TITLE
What to do with "Contributing to R Packages: A Tutorial"?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#245]
IMHO, this vignette feels completely out of the place as a vignette in this meta-package, given how generic it is:
https://easystats.github.io/easystats/articles/programming.html

I don't think we should be including it here. Of course, we don't want to waste the effort that was put into making it. So, I'd argue that we can polish it up and publish it as a blog post and mention it in our `CONTRIBUTING.md` document.

What do you think?

**Comment by DominiqueMakowski** [comment]
Why not, though I'd say that would require the overhaul of the website first (https://github.com/easystats/blog/issues/50)

**Comment by IndrajeetPatil** [comment]
I don't think modernizing blog should prevent us from posting new blog posts. 

Also, the current look is quite good, and, at any rate, "modernize" is a lofty goal at the moment and so can be dealt with after issues with higher priority have been dealt with.

**Comment by IndrajeetPatil** [comment]
Closed in #246

Tracking in https://github.com/easystats/blog/issues/53
