### ISSUE TITLE
'easystats' installation failed in R 4.2.0

### ISSUE THREAD

**Issue by docbio78** [easystats/easystats#248]
Using the latest version of R 4.2.0 and RStudio 2022.02.3 Build 492 'easystats' intallation fails: 

> install.packages("easystats", repos = "https://easystats.r-universe.dev")

trying URL 'https://easystats.r-universe.dev/bin/windows/contrib/4.2/easystats_0.5.0.zip'
Warning in install.packages :
  URL 'https://cdn.r-universe.dev/0937f909ab694bd06d979638bd7f7b9b/easystats_0.5.0.zip': status was 'SSL peer certificate or SSH remote key was not OK'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://easystats.r-universe.dev/bin/windows/contrib/4.2/easystats_0.5.0.zip'

with R version 4.1.3 it worked.

**Comment by etiennebacher** [comment]
Hello, this is maybe because you installed R 4.2.0 but you didn't install Rtools 4.2 (see [this answer](https://stackoverflow.com/a/72470416/11598948) on StackOverflow), which is necessary. See [here](https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html) to install Rtools

**Comment by docbio78** [comment]
Thanks a lot. Will try that. Still have Rtools 4!. 
Best,
Stefan

Von meinem iPad gesendet

**Comment by bwiernik** [comment]
You shouldn't need RTools to install from that URL. Are you on a Mac by chance? What if you use http instead of https in the URL?

**Comment by docbio78** [comment]
Thanks that was the 'trick' - using 'http' instead of 'https'. Great!
