### ISSUE TITLE
An official website (?)

### ISSUE THREAD

**Issue by pdwaggoner** [easystats/easystats#25]
Hi guys - I have been thinking about the need for a clean, simple interface to send interested users to. The reason for this need, from my perspective is threefold: First, while the Github page is obviously expansive and super useful, its definitely geared more toward developers, or at least people who understand programming more than many users who likely use our packages. Second, though the blog is great, its only a small part of easystats. And third, though many vignettes via `pkgdown` are super helpful, they're package-specific. 

Thus, I felt like we would really benefit from having a central, clean, easy-to-use web presence to which we could point anyone who is interested in the "Easyverse", which would serve as the home base or launching pad (pick your preferred metaphor) for all things-easystats.

With that said, I have pulled together a super simple version of a website with a clean interface (via `blogdown`). 

To take a look to see what you think follow these steps:

1. Download the repo I just created for it: https://github.com/pdwaggoner/easyverse

2. On your own machine in a new R session, simply open the file: `easyverse.Rproj`

3. Once opened and working from within the `easyverse` R project, in the console run: `devtools::install_github('rstudio/blogdown')`

4. Load the latest version of the library: `library(blogdown)`

5. Then finally run: `serve_site()`

It should pop up in the viewer within the session, at which point you can either navigate from within Rstudio, or you can select "Open in a new window" from within the Viewer pane. It should open in a new tab on your default web browser.

Note also, if we go this direction, I think updating our monicker to the "easyverse" (instead of easystats) would be a good idea, as its a bit more all encompassing. Just an idea, though.

Anyway, take a look and let me know what you all think. If you don't like it, truly no hard feelings, as I only spent a few hours developing this template. It's no big deal if you don't like this direction, truly! I just thought it could be a cool thing as we continue to formalize as a group. I would welcome any and all feedback.

**Comment by mattansb** [comment]
As usual, I can't seem to get this to work on my machine... But assuming it is beautiful...

Are you suggesting a website that is has more general blog posts and articals (as opposed to package specific posts / articles)? Maybe similar to @DominiqueMakowski 's [Bayesian LM article](https://easystats.github.io/bayestestR/articles/example1_LM.html)?

**Comment by DominiqueMakowski** [comment]
It works for me! 

Super cool :) Maybe this should be hosted on the easystats/easystats repo. I would maybe prefer a different background color, but that's minor aesthetic details to play with later on. But I think it would be a useful addition to the easyverse: we could also host references with links to the various papers, preprints and stuff (I might be seeing too big on this one haha), as well as a home page with NEWS with a sentence every time there's a release, a blogpost, a publication, an ***event*** or  such :)

**Comment by pdwaggoner** [comment]
Currently traveling a ton for the next several days so forgive the brevity, but yes to all of this! I don’t think you’re thinking too big at all - I think that’s exactly the point of this idea: just a space to host and showcase all things easystats to not only help people out but also provide a home base and cultivate a dedicated cohort of users and so on. I think the sky is the limit! Tons of opportunities here. I’ll dive into this much more and we can continue workshopping and dreaming a bit in the meantime. I want to really showcase and centralize the super cool things easystats is up to and where we are going. This could be a cool start to that!

**Comment by strengejacke** [comment]
_bump_

Do we still think we can manage this? Or is the blog sufficient, or do we simply want the readme as "website" via *pkgdown*?

**Comment by mattansb** [comment]
I think the blog and a pkgdowm would be enough.

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab
