### ISSUE TITLE
Correct README description?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#250]
This is no longer true because, at some point, we seem to also have picked up _scales_ as a hard dependency. 
_ggplot2_ itself includes _scales_ as a hard dependency, so this is not an issue _per se_. But, the description accompanying the dependency network is definitely not correct. So we have two options:

- remove scales from hard dependencies of _see_, or
- correct `README`

<img width="882" alt="Screenshot 2022-06-21 at 17 25 30" src="https://user-images.githubusercontent.com/11330453/174837856-93b5104d-760b-40a8-986b-4d316773701a.png">

**Comment by IndrajeetPatil** [comment]
@strengejacke What do you think?

**Comment by strengejacke** [comment]
If it's only about mentioning _scales_ in the text, I'd do that. (i.e. correct readme)

**Comment by IndrajeetPatil** [comment]
Checking in https://github.com/easystats/see/pull/224 if this really needs to be a hard dependency. I don't think so.
