### ISSUE TITLE
Build release and devel versions of package website

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#251]
We need to start having separate versions of the website for the release and development package versions, so that the users are not confused by why the output they see doesn't match with what's on the website. 

We can only do this after the next release of the package. If we do it now, the release websites will disappear.

The package version to signal development version should follow the form `x.y.z.9000`. Of course, we can continue to keep bumping the version after each significant change (e.g. 9001, 9002, etc.).

I can take care of this. Just need to add the following to `_pkgdown.yml`.

```yml
development:
  mode: auto
```

For more, see:
https://pkgdown.r-lib.org/articles/how-to-update-released-site.html

Progress tracker:

- [ ] insight 
- [ ] modelbased
- [ ] bayestestR
- [ ] effectsize
- [ ] parameters
- [ ] performance
- [ ] correlation
- [ ] report
- [ ] see
- [ ] datawizard
- [ ] easystats

**Comment by strengejacke** [comment]
I would rather use a.b.c.1, not a.b.c.9000

**Comment by IndrajeetPatil** [comment]
I no longer this is worth doing. Our core API is quite stable, so there shouldn't be major discrepancies between release and devel version of the docs. If anything, the docs might just have improved since the last release.
