### ISSUE TITLE
Post-CRAN-vacation release cycle

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#256]
CRAN submission portal will open again on the 6th of August.

We need to follow the following order of submission this time.

- [x] insight
- [x] modelbased
- [x] datawizard
- [x] correlation
- [x] effectsize
- [x] performance
- [x] parameters
- [x] see
- [x] report
- [ ] bayestestR

**Comment by strengejacke** [comment]
I think we should not remove the `data_*()` aliases in _datawizard_ now, it will cause too much packages to be broken - and not only failing tests, but complete functionality will be affected. And this, in turn, will automatically break *all* packages that import our packages. Since we can't predict how long it takes to update all our packages, there might be a longer time where many packages won't work properly.

We should wait one more release-cycle for the removal of function names like `data_to_numeric()` and soft-deprecate those functions instead.

@easystats/maintainers what do you think?

**Comment by etiennebacher** [comment]
> And this, in turn, will automatically break all packages that import our packages

Maybe this is a good time to start using [revdepcheck](https://github.com/r-lib/revdepcheck) in easystats repos? Not after every commit but maybe after each breaking change or just before a new CRAN submission

**Comment by strengejacke** [comment]
I usually do that before submission.

**Comment by IndrajeetPatil** [comment]
@etiennebacher We do use revdepcheck! The issue is not arising because we forgot to do revdepcheck. The issue is that we underestimated how much breakage the _datawizard_ function renaming was going to cause recursively. (Also see #214)

@strengejacke I would personally go for the "rip the band-aid now in one go" approach. Even with these breakages, I can still get _datawizard_ on CRAN. The real question is how long will it take for other dependencies to be updated once this update is on CRAN because non-easystats developers are going to be affected mostly via _parameters_ and _performance_, and to the degree that we can update broken _easystats_ packages on CRAN quickly, they wouldn't get any notification from CRAN. 

But things will be tumultuous for a week or two, for sure.

**Comment by IndrajeetPatil** [comment]
I think there is a good middle ground here. Out of the follwing functions which have been renamed and cause brekage:

We can ship aliases in this release, so that these old names will continue to be available in NAMESPACE:

  - `data_cut()` -> `categorize()`
  - `data_recode()` -> `change_code()`
  - `data_shift()` -> `slide()`
  - `data_reverse()` -> `reverse()`
  - `data_rescale()` -> `rescale()`
  
We stick to these changes, which would lead to some breakage, but nowhere near as much as before:
  
  - `data_to_factor()` -> `to_factor()`
  - `data_to_numeric()` -> `to_numeric()`

**Comment by strengejacke** [comment]
> data_to_numeric() -> to_numeric()

This change will break many of our packages, because `data_to_numeric()` is no longer exported by _datawizard_. This means that our packages will not install, and thereby breaking many other packages (like those from @vincentarelbundock). I know this is temporary, but we can't predict how long it will take until all our other packages are updated, and we can't say how regularly users update their packages.

**Comment by strengejacke** [comment]
I would exactly do the opposite, preserve aliases for those functions we use in our other packages (which are, e.g. `data_to_factor()` and in particular `data_to_numeric()`).

**Comment by vincentarelbundock** [comment]
Yes. I think it is extremely important to NOT rip the band aid off. I am still half on vacation and heading into the start of the semester, so an emergency release may not be possible.

With name changes, we should keep the old function names for at least one year, and go through a full cycle of updates with our packages. Trying to "game" the CRAN release schedule is too risky.

**Comment by vincentarelbundock** [comment]
After all easystats packages have been updated with the new names, the next round of updates can issue a deprecation warning in the aliases. 

This warning is important, but we don't want to start issuing it until all easystats are updated, because otherwise all packages that rely on parameters will become super verbose.

**Comment by IndrajeetPatil** [comment]
> Yes. I think it is extremely important to NOT rip the band aid off. I am still half on vacation and heading into the start of the semester, so an emergency release may not be possible.

But you won't have to do _anything_. 
This is purely _easystats_'s internal breakage. Only _easystats_/_sjverse_ packages currently rely on _datawizard_, and so _datawizard_'s breaking changes affect you only if the _easystats_ packages are not updated.

At any rate, that was just my opinion. I am fine with the backward compatible approach as well.

**Comment by vincentarelbundock** [comment]
Right, I get it. But we also have to start assuming that people will use our functions in their scripts and analyses, not just revdep. And CRAN sequence and error risks are 🙀🙀

**Comment by IndrajeetPatil** [comment]
*datawizard* is on CRAN.

The next ones to be updated should be _correlation_ and _effectsize_ because, IINM, they don't need to wait for _insight_ update to be on CRAN.

> Team, this breaks
> correlation effectsize parameters report see statsExpressions

**Comment by IndrajeetPatil** [comment]
@bwiernik I have prepared and submitted _correlation_ to CRAN. It should pass incoming checks, but we will see.

**Comment by bwiernik** [comment]
Thanks!

**Comment by IndrajeetPatil** [comment]
*correlation* is on CRAN.

**Comment by strengejacke** [comment]
- [ ] https://github.com/easystats/insight/pull/608
- [ ] https://github.com/easystats/parameters/pull/757
- [ ] https://github.com/easystats/performance/pull/465
- [ ] https://github.com/easystats/see/pull/233

**Comment by IndrajeetPatil** [comment]
![Hercules_Statue_(141608279)](https://user-images.githubusercontent.com/11330453/183843918-4f64cfb6-0b08-49db-b16d-d6b17debadda.jpg)

**Comment by IndrajeetPatil** [comment]
*effectsize* is on CRAN.

**Comment by strengejacke** [comment]
all 4 packages on CRAN now... Tomorrow, we should run checks for _report_ relying on CRAN versions (i.e. remove "Remotes" from the description file)

**Comment by IndrajeetPatil** [comment]
We also need to update _modelbased_.

**Comment by strengejacke** [comment]
Yes, I think @DominiqueMakowski is informed and will do after his vacation?

**Comment by IndrajeetPatil** [comment]
Yes, on Sunday, I think. But he also maintains _report_, so it will also be submitted after that.

**Comment by strengejacke** [comment]
And then... _easystats_?

**Comment by IndrajeetPatil** [comment]
YES!

**Comment by IndrajeetPatil** [comment]
We should also update _bayestestR_. It isn't broken, but it has been a while since we updated it.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Did you submit to CRAN any of the remaining packages that need to be updated for this cycle?

**Comment by IndrajeetPatil** [comment]
Next up is _report_ or _bayestestR_?

**Comment by DominiqueMakowski** [comment]
none has been submitted yet, not sure what the order should be, probably bayestestR first

**Comment by strengejacke** [comment]
Doesn't report have a deadline?

**Comment by IndrajeetPatil** [comment]
Yes, it does: 22/08

**Comment by DominiqueMakowski** [comment]
well, then report it is 😁

**Comment by IndrajeetPatil** [comment]
Next up: _bayestestR_

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Are we updating _bayestestR_ in this cycle, or should this issue be closed?

We do have `NOTE`s that we can easily get rid of with an update (https://cran.r-project.org/web/checks/check_results_bayestestR.html):

<img width="1146" alt="Screenshot 2022-08-23 at 15 31 48" src="https://user-images.githubusercontent.com/11330453/186171288-c350be1f-1e37-4b1c-add6-a168c4d0874e.png">

**Comment by IndrajeetPatil** [comment]
_bump_

**Comment by IndrajeetPatil** [comment]
_Bump_

**Comment by strengejacke** [comment]
😂

**Comment by DominiqueMakowski** [comment]
loool sorry sorry I missed this, on it tomorrow!
