### ISSUE TITLE
model_dashboard() performance metrics bug

### ISSUE THREAD

**Issue by viv-analytics** [easystats/easystats#259]
A test of the new model_dashboard() revealed an error message related to performance metrics 

<img width="2441" alt="Screen Shot 2022-08-06 at 22 36 09" src="https://user-images.githubusercontent.com/100348646/183265300-3096b984-378c-4b37-bdc8-6aab9ef39658.png">

`mod <- lm(wt ~ mpg, mtcars)`
`easystats::model_dashboard(mod)`

`sessionInfo()`
> R version 4.2.1 (2022-06-23)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Monterey 12.5
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] report_0.5.1.1      see_0.7.1           correlation_0.8.1   modelbased_0.8.1    effectsize_0.7.0    parameters_0.18.1   performance_0.9.1   bayestestR_0.12.1   datawizard_0.4.1   
> [10] insight_0.18.0      easystats_0.5.1     flexdashboard_0.6.0
> 
> loaded via a namespace (and not attached):
>  [1] sass_0.4.2         jsonlite_1.8.0     splines_4.2.1      bslib_0.4.0        assertthat_0.2.1   highr_0.9          yaml_2.3.5         robustbase_0.95-0  ggrepel_0.9.1      pillar_1.8.0      
> [11] lattice_0.20-45    glue_1.6.2         digest_0.6.29      colorspace_2.0-3   sandwich_3.0-2     htmltools_0.5.3    Matrix_1.4-1       pkgconfig_2.0.3    purrr_0.3.4        xtable_1.8-4      
> [21] mvtnorm_1.1-3      patchwork_1.1.1    scales_1.2.0       emmeans_1.8.0      tibble_3.1.8       mgcv_1.8-40        farver_2.1.1       generics_0.1.3     ggplot2_3.3.6      TH.data_1.1-1     
> [31] cachem_1.0.6       cli_3.3.0          survival_3.3-1     magrittr_2.0.3     memoise_2.0.1      estimability_1.4.1 evaluate_0.15      fs_1.5.2           fansi_1.0.3        nlme_3.1-158      
> [41] MASS_7.3-58.1      tools_4.2.1        lifecycle_1.0.1    multcomp_1.4-19    stringr_1.4.0      munsell_0.5.0      qqplotr_0.0.5      compiler_4.2.1     jquerylib_0.1.4    rlang_1.0.4       
> [51] grid_4.2.1         rstudioapi_0.13    labeling_0.4.2     rmarkdown_2.14     gtable_0.3.0       codetools_0.2-18   DBI_1.1.3          R6_2.5.1           zoo_1.8-10         knitr_1.39        
> [61] dplyr_1.0.9        fastmap_1.1.0      utf8_1.2.2         stringi_1.7.8      Rcpp_1.0.9         vctrs_0.4.1        DEoptimR_1.0-11    tidyselect_1.1.2   xfun_0.31          coda_0.19-4 

###

**Comment by IndrajeetPatil** [comment]
Hi!

Can you please update to the latest GitHub versions of `{easystats}` packages and then try again?

Unfortunately, this functionality currently works only with the GitHub versions, but we are in the process of updating packages on CRAN.

**Comment by viv-analytics** [comment]
Updating via `easystats::install_latest()` does not solve the issue for me.
