### ISSUE TITLE
Improving on the "Text reports" page of the dashboard

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#261]
Currently, after having visited the other pages, when you arrive at the "Text reports" page, it feels like we just forgot to include something on the RHS column. Plus, all that empty space is an eyesore.

How can we improve this page? 
Should we just have a single column so that the `{report}` output takes up the whole page, or something else?

<img width="1438" alt="Screenshot 2022-08-07 at 19 27 58" src="https://user-images.githubusercontent.com/11330453/183303403-94dc7d56-2297-43e6-9b8d-6822c7e2484a.png">

**Comment by strengejacke** [comment]
> Should we just have a single column so that the {report} output takes up the whole page, or something else?

We had this before, but then you have never-ending lines, which is difficult to read. I did this change intentionally.

**Comment by IndrajeetPatil** [comment]
Seems fair enough.

Are there any other details about the model that we can include in the dashboard? 
Maybe `insight::model_info()` in the form of a vertical, multi-column table?

**Comment by IndrajeetPatil** [comment]
Closed by https://github.com/easystats/easystats/pull/266
