### ISSUE TITLE
Do we really need two separate graphs to show download trends?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#262]
I think we can only retain the cumulative downloads chart, which also shows the long-term trends?

<img width="825" alt="Screenshot 2022-08-12 at 15 29 16" src="https://user-images.githubusercontent.com/11330453/184363937-f62621b8-7178-454e-9dcd-10beb939db96.png">

<img width="831" alt="Screenshot 2022-08-12 at 15 29 25" src="https://user-images.githubusercontent.com/11330453/184364101-cd1f6e0f-0d53-4e34-aa73-b68e3d3939aa.png">

**Comment by IndrajeetPatil** [comment]
Those three back-to-back graphs in README reminds me of Caravaggio's painting 🥲

![image](https://user-images.githubusercontent.com/11330453/184364208-e5b4e119-1dba-42da-bdb7-d28b1c2a6879.png)

**Comment by bwiernik** [comment]
Agreed we only need to say how impressive we are once

**Comment by strengejacke** [comment]
Since we have the cumulative downloads as table, I suggest we stick to the upper figure.

**Comment by DominiqueMakowski** [comment]
Yes upper figure is more interesting as it shows "events" like covid, summer and winter vacations, etc. If in the future it gets too crowded we can 1) first remove the background light daily downloads trends, 2) increasing the size of the smoothing window
