### ISSUE TITLE
Leave out function call in condition messages

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#263]
We use error condition in many places, but always include the function call in the error:

https://github.com/search?l=R&q=org%3Aeasystats+stop&type=Code

In all these contexts, I think we should be setting `call. = FALSE`:

https://adv-r.hadley.nz/conditions.html#signalling-conditions

<img width="1211" alt="Screenshot 2022-03-24 at 23 33 22" src="https://user-images.githubusercontent.com/11330453/160021176-95308ad4-4f7e-46be-a504-b500df2d553e.png">

Because, typically, the errors bubble up from somewhere deep in the code, and we can't expect the users to be familiar with our _implementation_. Our error messages tend to be verbose and insightful enough for them to know what went wrong. And, if the user is savvy enough, they can just call `traceback()` and it will show them where the error is originating from.

# Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
I usually always use `call. = FALSE`, except I forget it.

**Comment by IndrajeetPatil** [comment]
Cool. 

Yeah, I think this should already be the case in most places; just need to check if there are any instances where this is not done.

**Comment by IndrajeetPatil** [comment]
You can do this in a single function call:

```r
xfun::gsub_dir(
  "(stop\\()(.*)(\\))",
  "\\1\\2, call. = FALSE\\3",
  ext = "R",
  dir = "R/"
)
```

**Comment by strengejacke** [comment]
> You can do this in a single function call:

I can do what?

**Comment by IndrajeetPatil** [comment]
Sorry, _you_ as in all easystats maintainers who want to do this change in their repos. 😅

I think this is already the case for repos you are manitaining.

**Comment by strengejacke** [comment]
By "do this" you mean search & replace?

**Comment by IndrajeetPatil** [comment]
No. Just run that command in the package root directory, and the needed substitutions will be carried out automatically.

Although, I think that regex is not working as expected when there is already `call. = FALSE` present. Need to modify it a bit.

**Comment by strengejacke** [comment]
Yes, if `call.` is already there, the regex doesn't work (need look-ahead or behind I think). Also not that warnings need to be fixed as well.

How to do in VS Code:

![image](https://user-images.githubusercontent.com/26301769/185054045-e18ff052-ad6f-4312-a3c6-f1d98e97f089.png)

(not sure which regex-style RStudio requires)

**Comment by IndrajeetPatil** [comment]
Yeah, I'd have a look at the regex after work.

**Comment by IndrajeetPatil** [comment]
I am still struggling with this. How can I modify this regex so that it captures both of these possibilities?

That is, I want to specify that the group `, .call = FALSE` may or may not be present.

<img width="528" alt="Screenshot 2022-08-18 at 21 21 51" src="https://user-images.githubusercontent.com/11330453/185477313-46f4f106-9cea-4e01-b346-796cd67288f0.png">
<img width="496" alt="Screenshot 2022-08-18 at 21 22 02" src="https://user-images.githubusercontent.com/11330453/185477317-39961a8d-db97-40db-b570-d25599def1d4.png">

**Comment by bwiernik** [comment]
(\\.call = FALSE)?

**Comment by IndrajeetPatil** [comment]
Thanks. This is a bit different, though, because now groups 3 and 4 collapse into one:

<img width="537" alt="Screenshot 2022-08-18 at 21 44 17" src="https://user-images.githubusercontent.com/11330453/185481350-d9af7ac6-402e-4927-bba3-efb12274bfde.png">

My plan was to use the first three groups and then create the following substitution:

<img width="522" alt="Screenshot 2022-08-18 at 21 50 28" src="https://user-images.githubusercontent.com/11330453/185482316-ba860647-bd1b-4814-ba48-681f79d3d6ad.png">

But, of course, the regex doesn't work when `, .call = FALSE` is not present.
