### ISSUE TITLE
Add "Getting help" page to websites

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#265]
If we include `.github/SUPPORT.md`, it will be included as a separate page titled "Getting help".
For a reference, see: https://dplyr.tidyverse.org/dev/SUPPORT.html

<img width="537" alt="Screenshot 2022-08-21 at 07 38 06" src="https://user-images.githubusercontent.com/11330453/185777213-8c3d132d-e5ed-4cc9-956f-f0d85ec67846.png">

We should definitely include such a document, but I don't know if we should write our own document about how to ask for help or just adapt what is used in the `{tidyverse}` packages:
https://github.com/tidyverse/dplyr/blob/HEAD/.github/SUPPORT.md

# Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
@easystats/maintainers Any thoughts? Should we just use what the _tidyverse_ team is using; only replacing "tidyverse" with "easystats" in their template?

**Comment by mattansb** [comment]
Yup - maybe point them at the repos discussions for questions (instead of the rstudio community).

**Comment by IndrajeetPatil** [comment]
@easystats/maintainers Please do this for the repos that you maintain.

**Comment by etiennebacher** [comment]
I opened PRs for this, I see no reason of not merging them so I close this

**Comment by IndrajeetPatil** [comment]
Thanks, @etiennebacher, for taking care of this! <3
