### ISSUE TITLE
Easystats dependencies: version caps?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#27]
Should we version cap our own packages so it forces the user to update easystats dependencies whenever he updates a piece, to have a fully compatible set?

For instance, the current version of `parameters` relies on the latest `bayestestR`. Should we add a cap in the DESCRIPTION; imports: bayestestR (>= 0.1.6)?

**Comment by mattansb** [comment]
This sounds like an excellent idea.

**Comment by strengejacke** [comment]
yes, when it makes sense, we should do that. I think, at the moment we have a release cycle where each package depends on the latest version of downstream packages. So actually it makes always sense to do that.
