### ISSUE TITLE
Welcome, Rémi!

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#270]
Hello @rempsyc!

Welcome to easystats 🎉!

This is a place for us to learn and eventually sometimes help others (and ourselves) in their conquest of statistics. 

You might wonder what is expected of members? Nothing, we all have busy schedules and other priorities, so no worries on that side. But feel free to comment, give suggestions in issues, retweet easystats tweets and as such whatever you feel comfortable with. You might see us ping specific people from time to time, but we encourage everyone to give their opinion and thoughts, even if not directly pinged (or just reacting with a 👍 or a 😠). We have also given you writing access to the repos, so if you spot any typo or something to improve, you can make a PR to fix (or open an issue if you want to check first).

We'd recommend that you "watch" (follow) all the [easystats repos](https://github.com/easystats), to stay tuned to what's going on, as we usually work in parallel (and chaotically create and move around issues in several places) :)

Easystats, a collection of packages, has a "pyramidal" organization with low-level packages, such as "insight" (named "low-level" because they do not depend on anything than themselves to work), which are cornerstones for other mid-level packages (such as effectsize, parameters and performance), which themselves are used by high-level packages (e.g., report, see) that uses the power and synergy of the whole ecosystem to achieve their purpose. Some packages are also focused on specific features/aspects/data analysis type (e.g., bayestestR, correlation). This is the way it is for now, but who knows what the future has in store!

In addition to your technical expertise, we are looking forward to benefit from your experience in best practices in open science research, and if and how this can be utilized to improve the easystats user experience.

Don't hesitate if you have any questions, and feel free to share any questions thoughts, ideas, suggestions (or memes)!

**Comment by rempsyc** [comment]
Thank you Indra and all of the easystats team! I'm really looking forward to this exciting collaboration. I have tons of ideas that hopefully I'll be able to deploy slowly over the coming months (years). In the meanwhile, _hasta la vista_ baby, and may the force be with us all!

**Comment by strengejacke** [comment]
I'm really glad to welcome you on board!
![excellent-this-makes-me-happy](https://user-images.githubusercontent.com/26301769/186273181-423a6ff1-4c5b-47cb-b2fa-3e2859003c8d.jpg)

**Comment by strengejacke** [comment]
To briefly familiarise you with the most important rules:
![image](https://user-images.githubusercontent.com/26301769/186273343-04f280f0-f45d-4bd2-bf54-688d3c332045.png)

**Comment by bwiernik** [comment]
It's "main" now

**Comment by DominiqueMakowski** [comment]
Haha 

welcome to the team @rempsyc 🥳

**Comment by rempsyc** [comment]
Actually,
![F41B4782-A818-4AFE-835F-5C38CDC12663](https://user-images.githubusercontent.com/13123390/186298349-85d4d5e7-72b3-4cfb-b80a-97b0c9c588cd.jpeg)

**Comment by mattansb** [comment]
Welcome aboard!

**Comment by etiennebacher** [comment]
Welcome @rempsyc!

![image](https://user-images.githubusercontent.com/52219252/186417813-30d795ce-234d-451d-9f2a-60353221df27.png)
