### ISSUE TITLE
About the `{modelsummary}` fork

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#274]
@vincentarelbundock Did you by any chance create this fork in the `{easystats}` org? 

https://github.com/easystats/modelsummary

I just want to make sure that I can delete it without causing any problems for anyone. AFAICT, none of the other @easystats/core-team seem to have forked it.

**Comment by vincentarelbundock** [comment]
WoW. If I did it was absolutely unintentional. Sorry! Feel free to delete.

**Comment by etiennebacher** [comment]
I think I made a fork of modelsummary like 2 weeks ago but I don't know why it appeared in easystats

**Comment by IndrajeetPatil** [comment]
Got it, thanks.

I was wondering why would Vincent fork his own repo 😅
