### ISSUE TITLE
Get rid of NOTEs

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#275]
See https://cran.r-project.org/web/checks/check_results_easystats.html Any ideas?

**Comment by IndrajeetPatil** [comment]
We can import a workhorse function from each package just to get rid of this NOTE.

**Comment by strengejacke** [comment]
Or maybe we don't import them, and once _easystats_ is loaded, we install them if needed? This will only occur once...

**Comment by strengejacke** [comment]
> We can import a workhorse function from each package just to get rid of this NOTE.

But maybe that's an easier solution.

**Comment by etiennebacher** [comment]
Here's how `tidyverse` does: https://github.com/tidyverse/tidyverse/blob/main/R/tidyverse.R
