### ISSUE TITLE
readme not re-rendered?

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#278]
I [fixed a type](https://github.com/easystats/easystats/commit/b118bb9ab09c0bd0aff464e09e8ee4322d396ffb) and hoped that the readme would be re-rendered, but it still shows the typo:

![image](https://user-images.githubusercontent.com/26301769/187542296-87ae84d7-afa4-44d8-889b-e55b64e21d53.png)

**Comment by IndrajeetPatil** [comment]
Nope, README doesn't render itself. It just checks that the rendering still works with the PR. 

There is a cron job that is supposed to render it once a day, and it used to work initially. But then it stopped working:

https://github.com/easystats/easystats/blob/b8246d5fcd1543d2117d56c037402001c61b3e41/.github/workflows/render-readme.yaml#L11-L12

@etiennebacher Any ideas?

**Comment by etiennebacher** [comment]
> Nope, README doesn't render itself. It just checks that the rendering still works with the PR.

No I think it's supposed to automatically render the readme

> @etiennebacher Any ideas?

I'll take a look but I think there's an extra space after `cron:`

**Comment by etiennebacher** [comment]
> I'll take a look but I think there's an extra space after cron:

actually, I don't think this is causing any problem
