### ISSUE TITLE
New member: Indra

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#28]
A warm welcome to @IndrajeetPatil to easystats 🎉

There isn't much left to be said that hasn't already been written somewhere. But long story short, 
easystats is an open and collaborative project *mainly* centred (at least for now) around building tools surrounding statistical models, with a focus on user experience; carefully considering functions' design, names, argument names etc. to maximize clarity, intuitiveness, and accessibility.

Do not hesitate to comment, give suggestions or such whenever you feel comfortable enough. It might be useful to "watch" (follow) all the easystats repos, to be notified of what's going on, as we usually work in parallel :) 

Just to give you some context, the work is currently focused on the following roadmap:

- bayestestR v2 CRAN release
- performance v2 CRAN release
- parameters initial CRAN release

Feel free to share any thoughts, ideas or dank memes ☺️ 

@strengejacke @pdwaggoner @mattansb

**Comment by pdwaggoner** [comment]
Welcome @IndrajeetPatil !

**Comment by IndrajeetPatil** [comment]
Hey everyone!

Thanks a ton for having me on board and looking forward to working together to make data science fun for people! :)
