### ISSUE TITLE
Predicted Values for glm

### ISSUE THREAD

**Issue by tegedik** [easystats/easystats#282]
I saw [this issue](https://github.com/easystats/easystats/issues/280) and encountered an error for `glm` using `easystats::model_dashboard`.

```
df <- carData::Mroz
glmfit <- glm(lfp ~ k618 + wc + hc + inc, df, family=binomial(link="logit"))
easystats::model_dashboard(glmfit)
```
Now, this model returns an error for plot under predicted values tab:

```
Error in if (ncol(vcovmat) < ncol(mm)) {: argument is of length zero
Error in lapply(text_modelbased, function(i) {: object 'text_modelbased' not found
Error in is.ggplot(x): object 'all_plots' not found
```
And for tabular summary:
```
Error in eval(expr, envir, enclos): object 'text_modelbased' not found
```
<img width="1439" alt="Screen Shot 2022-08-31 at 10 25 26 AM" src="https://user-images.githubusercontent.com/16861565/187618699-39c5622a-b611-4998-84ed-f7145bd0d537.png">

I realized that this has to do with the outcome (`lfp`) being a factor. When I convert it into numeric: 
```
df$lfp <- as.numeric(df$lfp) -1
```
The problem disappears:

<img width="1436" alt="Screen Shot 2022-08-31 at 10 31 31 AM" src="https://user-images.githubusercontent.com/16861565/187619658-74e8779f-91ca-4ec8-8fbc-731e2dd9eda1.png">

I don't think this is a serious issue but I want to let you know.

**Comment by strengejacke** [comment]
Minimal reprex:

``` r
library(insight)
library(modelbased)

df <- carData::Mroz
model <- glm(lfp ~ k618 + wc + hc + inc, df, family = binomial(link = "logit"))

grid <- insight::get_datagrid(model, at = "k618", range = "grid", preserve_range = FALSE, verbose = FALSE)
modelbased::estimate_expectation(model, data = grid, verbose = FALSE)
#> Warning in `[<-.factor`(`*tmp*`, ri, value = c(0, 0, 0, 0, 0, 0, 0, 0, 0, :
#> invalid factor level, NA generated
#> Error in if (ncol(vcovmat) < ncol(mm)) {: argument is of length zero
```

<sup>Created on 2022-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
