### ISSUE TITLE
Remove some re-exported functions

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#292]
We had retained or re-exported a number of functions that were moved to a different package in order to not cause a breaking change, since the meta package wasn't on CRAN. For example, `simulate_simpson()` is re-exported from `{correlation}` package, although it lives in `{bayestestR}` package.

Now that we have released the meta package, this should no longer be necessary, and we can remove (some) re-exports.

**Comment by IndrajeetPatil** [comment]
@mattansb You can decide if this is relevant for _effectsize_, but I am closing it because I have done this for other repos.

**Comment by mattansb** [comment]
I think I'll leave them - they shouldn't cause any breakage, and I like them together on the pkgdown site (:
