### ISSUE TITLE
Go back to using `{deepdep}` for dependency visualization in `README`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#293]
Instead of using `{igraph}`, which doesn't look as pretty. WDYT, @mattansb?

Also, at what depth should we be visualizing this? 

``` r
library(deepdep)

plot_dependencies("easystats", depth = 2, show_stamp = FALSE)
```

<img src="https://i.imgur.com/TG9rgKc.png" width="100%" />

``` r

plot_dependencies("easystats", depth = 4, show_stamp = FALSE)
```

<img src="https://i.imgur.com/jgkJRUs.png" width="100%" />

<sup>Created on 2022-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
Also, _easystats_ has 34 direct dependencies!

I am not sure if it's appropriate to include the tinyverse badge in README.

![image](https://user-images.githubusercontent.com/11330453/188303062-494d521b-341e-4ba0-8688-2856e2ffda23.jpeg)

**Comment by strengejacke** [comment]
I don't mind being transparent here because easystats is not meant to be imported by other packages just like tidyverse shouldn't be important by packages.
So it's ok to have so many dependencies

**Comment by mattansb** [comment]
>I don't mind being transparent here because easystats is not meant to be imported by other packages just like tidyverse shouldn't be important by packages.
So it's ok to have so many dependencies

Agree.

I think `depth = 2` is enough
