### ISSUE TITLE
Create new `skip_*()` helpers for tests instead of using `.runThisTest`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#294]
## Preamble

Currently, we use these abstruse and non-descriptive way of skipping tests. 

E.g. [Setup](https://github.com/easystats/parameters/blob/879da44e97560140e36d3ddcb14867aa23ca556f/tests/testthat.R)

```r
if (require("testthat")) {
  library(parameters)
  if (length(strsplit(packageDescription("parameters")$Version, "\\.")[[1]]) > 3) {
    Sys.setenv("RunAllparametersTests" = "yes")
  } else {
    Sys.setenv("RunAllparametersTests" = "no")
  }

  si <- Sys.info()

  osx <- tryCatch(
    {
      if (!is.null(si["sysname"])) {
        si["sysname"] == "Darwin" || grepl("^darwin", R.version$os)
      } else {
        FALSE
      }
    },
    error = function(e) {
      FALSE
    }
  )

  solaris <- tryCatch(
    {
      if (!is.null(si["sysname"])) {
        grepl("SunOS", si["sysname"], ignore.case = TRUE)
      } else {
        FALSE
      }
    },
    error = function(e) {
      FALSE
    }
  )

  if (!osx && !solaris) {
    test_check("parameters")
  }
}
```

And its usage in test:

```r
 .runThisTest <- Sys.getenv("RunAllparametersTests") == "yes"
```

## Issue

These are difficult to understand and maintain. I personally have 0 clue as to what is going on here, or why we are doing this. 
CRAN doesn't even check on Solaris anymore, but we somehow seem to have skipping logic for it, and I don't know why.

Additionally, modifying `testthat.R` file like this is [not considered a good practice](https://github.com/r-lib/usethis/blob/main/inst/templates/testthat.R) by `{testthat}` developers.

```r
# This file is part of the standard setup for testthat.
# It is recommended that you do not modify it.
```

Instead, we should be creating new `skip_*()` helper functions and using them to skip certain tests.

These should be stored in `tests/testthat/helper.R`

## Examples

- To skip on certain R version

```r
skip_if_not_r_version <- function(min_version) {
  if (getRversion() < min_version) {
    testthat::skip(paste("R version at least", min_version, "is required"))
  }
}
```

- To skip in certain locales

```r
skip_if_not_utf8_locale <- function() {
  testthat::skip_if_not(l10n_info()[["UTF-8"]], "Not a UTF-8 locale")
}
```

etc.

## Reference

- https://testthat.r-lib.org/articles/skipping.html?q=special#helpers

## Progress tracker

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
If we can skip depending on whether we use the dev- or CRAN version, we can switch to `skip_*()`. Solaris is still some old code from times when CRAN checked against solaris, too.

**Comment by IndrajeetPatil** [comment]
> If we can skip depending on whether we use the dev- or CRAN version

Sorry, not sure what you mean here. Skip tests based on the dev- or CRAN version of what? Dependencies? 

> Solaris is still some old code from times when CRAN checked against solaris, too.

It has been dropped, so we can remove it now:
https://cran.r-project.org/web/checks/check_flavors.html

**Comment by strengejacke** [comment]
``` r
packageDescription("correlation")$Version
#> [1] "0.8.2.2"

is_dev_version <- length(strsplit(packageDescription("correlation")$Version, "\\.")[[1]]) > 3
is_dev_version
#> [1] TRUE
```

Some tests are only run through GHA, mostly because CRAN requires to stay below a certain time limit for tests (i.e. tests should not run for more than x minutes), and sometimes tests fail on CRAN due to very specific settings.

Thus, `.runThisTest` is a flag whether to skip tests or not, depending on whether these tests are run on CRAN (because we don't have dev-versions on CRAN - except for _effectsize_) or on the dev-version of our packages on GitHub.

**Comment by IndrajeetPatil** [comment]
> Thus, .runThisTest is a flag whether to skip tests or not, depending on whether these tests are run on CRAN (because we don't have dev-versions on CRAN - except for effectsize) or on the dev-version of our packages on GitHub.

Why not just use `testthat::skip_on_cran()` then?

**Comment by strengejacke** [comment]
It's a bit opaque when and how much skipping is done, so I preferred the very clear if-statement, if only parts inside a larger test-file should be skipped. Given the fragile nature of snapshot-tests, I just wanted to be certain. 😄

**Comment by IndrajeetPatil** [comment]
![image](https://user-images.githubusercontent.com/11330453/188499820-3e4618de-a92b-4451-b969-a661ed289aaa.png)

Snapshot tests don't even make 5% of all of our all tests; they shouldn't influence any decisions about this.

**Comment by strengejacke** [comment]
Given the fragile nature of snapshot tests, my trust is not too high, so I wanted to be sure skipping works 😁
No, the main reason is I didn't know how much is skipped. That's why I used runthistest.

**Comment by IndrajeetPatil** [comment]
Finally, done.

![giphy](https://user-images.githubusercontent.com/11330453/231376629-9e481f2f-20c5-40f1-b020-f90051229474.gif)
