### ISSUE TITLE
Add information about R version support

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#295]
Similar to:
https://www.tidyverse.org/blog/2019/04/r-version-support/

This should go into developer-facing vignette.

More importantly, we should test all supported R versions on GHA to ensure that we _actually_ support these R versions. Currently, we don't do this. We support `R >= 3.5`, by test only until `R >= 3.6` to avoid the headache of dealing with missing R packages on this older version.

P.S. TBH, given that `R 3.6.0` was released almost 2.5 years ago (2019-04-26), I wouldn't mind bumping the minimum needed R version to `3.6`.

**Comment by IndrajeetPatil** [comment]
> How many major releases back should we support?

You mean minor, right? (As in `major.minor.patch`). 

I would say four; i.e., `R >= 3.6`.

**Comment by bwiernik** [comment]
Agree that 3.6 (two versions older than r-oldrel) is a good back-support line

**Comment by IndrajeetPatil** [comment]
@strengejacke WDYT?

**Comment by strengejacke** [comment]
Yeah, I agree. Back to 3.6 should be enough.

**Comment by strengejacke** [comment]
Maybe we probably shouldn't make this change to _insight_, as some wider used packages that import _insight_ still support R 3.5?

**Comment by IndrajeetPatil** [comment]
See my response [here](https://github.com/easystats/easystats/issues/304#issuecomment-1248951110).
