### ISSUE TITLE
Create a utils function wrapping stop() and format_message() ?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/easystats#298]
I often forget to use `insight::format_message()` in `warning()` or `stop()`, and writing both functions makes the code less clean. Do you think there should be a function like `insight::stop()` (or with another name) that wraps the two? This would also be the occasion to put `.call = FALSE` by default.

Posting this here because if this idea is accepted, I don't know if this should be an `insight` function or a utils defined in each repo.

**Comment by IndrajeetPatil** [comment]
Yes, I personally like the idea of creating new wrappers around the _insight_ formatting functions specifically tailored for warnings and errors.
