### ISSUE TITLE
Rename CRAN-related functions?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#299]
Proposed* (old -> new):

- `CRAN_checks()` -> `check_status_on_cran()`
- `on_CRAN()` -> `last_updated_on_cran()`

I think such renaming makes sense for a couple of reasons:

- Rarely a good idea to mix lower and upper case in function names.
- The second name makes it really difficult to figure out what this function actually does.

*I couldn't come up with good names that share a common prefix instead of a suffix.

**Comment by strengejacke** [comment]
Yes, we can do that. The choice of names was rather quick and dirty at a time when CRAN release was in a far away future, so I didn't care much about it back then ;-)

**Comment by IndrajeetPatil** [comment]
TBH, I wouldn't mind removing the function to check last updated on CRAN. This is not something that should be user-facing. 

Plus, we do have a dashboard to check this (https://easystats.github.io/dashboard/dashboard.html). Adding how many weeks ago to this column should be easy enough (cc @etiennebacher).

<img width="1433" alt="Screenshot 2022-09-11 at 10 08 59" src="https://user-images.githubusercontent.com/11330453/189518050-ef6a5aa4-e163-409e-a451-23462a148d73.png">

WDYT, @strengejacke?

**Comment by strengejacke** [comment]
Actually, the same probably applies to `check_cran_status()` - we could add that information to the dashboard as well? It was meant as convenient function to quickly get an overview if we can submit updates already, or whether we have errors. Both functions were not intended to be user-facing. We _could_ keep them as internal functions, which are not exported.

**Comment by IndrajeetPatil** [comment]
Sounds good. I am still going to merge the PR, and then we can move these functions to the dashboard.

I see no benefit of keeping them internally, though. Otherwise, we will have two copies of the same functions in two different repos.
