### ISSUE TITLE
Move CRAN information to the dashboard and remove relevant functions

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#302]
As discussed in #299

**Comment by etiennebacher** [comment]
Sorry, still need to remove the functions from easystats

**Comment by IndrajeetPatil** [comment]
This information can now be found in our dashboard: https://easystats.github.io/dashboard/dashboard.html

Thanks, @etiennebacher!

**Comment by IndrajeetPatil** [comment]
@easystats/core-team Make sure that you are watching the dashboard repo: https://github.com/easystats/dashboard

Going forward, this is going to be our way to check ecosystem status.
