### ISSUE TITLE
Check if all soft dependencies in `Suggests` are actually being used

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#305]
[This](https://github.com/easystats/parameters/commit/f5fef1a23e0e82f0eafd7c3d1dcc5bf39bfcbfa4) caught me by surprise. 

Although installing deps on GitHub machines is cheap, we should still be judicious by avoiding including dependencies we don't need. They can create problems (e.g.) during R CMD check on older R versions. 

# Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
Yes, agree. I guess this was an artifact where we probably needed some of the internal data sets, or for testing against some output?

Another question: why does r-universe fail? https://github.com/r-universe/easystats/actions/runs/3072805883/jobs/4964529631

**Comment by IndrajeetPatil** [comment]
Sorry, I don't use r-universe. So no idea.

**Comment by strengejacke** [comment]
> Sorry, I don't use r-universe. So no idea.

But that's even greater than snapshot tests!!! :-)
I think r-universe is a _very_ nice feature for users, especially since we have _easystats_ on CRAN now. No longer need to tell how to complicatedly update single packages, we just need to tell them: "call `easystats::install_latest()` and try again".

**Comment by IndrajeetPatil** [comment]
I am not saying anything about its usefulness, etc.

I am just saying I don't have anything useful to say on this matter.

**Comment by mattansb** [comment]
>  ... we should still be judicious by avoiding including dependencies we don't need. 

Define "need"? 
There are packages that are not used by us, but that we "enhance" and would like to test that we are able to support their models / output / etc...

**Comment by IndrajeetPatil** [comment]
> Define "need"?

They are not used in code, in examples, in tests, in README. They are not used _anywhere_.

**Comment by IndrajeetPatil** [comment]
Okay, I have removed some unnecessary deps across the packages, so this should be fixed for now.

Just keep an eye out for bloated `Suggests` sections, and, once in a while, check if we are actually using all the weak dependencies.
