### ISSUE TITLE
Popularize the usage of the metapackage

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#307]
Should we, in all our vignettes / examples, replace the individual packages loading by e.g. (for parameters):
`library(easystats)  # Load {parameters} and other useful packages`

**Comment by DominiqueMakowski** [comment]
I'm not a fan of start-up messages

**Comment by IndrajeetPatil** [comment]
Nobody is. That's why I was suggesting it only for one release cycle.

If you start doing `library(easystats)` in vignettes and examples, we will have to include `{easystats}` in `Suggests`, and introduce soft circular dependence for the entire ecosystem.

**Comment by IndrajeetPatil** [comment]
The alternative is to include a message encouraging users to use the meta-package in the README of individual package repositories.

**Comment by DominiqueMakowski** [comment]
> we will have to include {easystats} in Suggests, and introduce soft circular dependence for the entire ecosystem

ah you're right

README sounds good then!

**Comment by IndrajeetPatil** [comment]
Can we compose here standardized text to include? So that everyone can just copy-paste it to READMEs.

**Comment by DominiqueMakowski** [comment]
```diff
! Tip: instead of `library(bayestestR)`, use `library(easystats)`, it's the best way to stay updated :)
```

**Comment by strengejacke** [comment]
! Tip: instead of `library(bayestestR)`, use `library(easystats)`. This will load all core-packages and makes all features of the easystats-ecosystem available in your current R session. To stay updated with latest features, use `easystats::install_latest()`.

**Comment by IndrajeetPatil** [comment]
I like Daniel's suggestion. We can afford to be verbose in README.

**Comment by DominiqueMakowski** [comment]
```diff
! Tip: instead of `library(bayestestR)`, use `library(easystats)`.
! This will make all features of the  easystats-ecosystem available. 
! To stay updated, use `easystats::install_latest()`.
```

**Comment by strengejacke** [comment]
yes, looks also good to me!

**Comment by IndrajeetPatil** [comment]
Closing in favour of https://github.com/easystats/easystats/issues/308.
