### ISSUE TITLE
Include recommendation to use meta-package in README

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#308]
As discussed [here](https://github.com/easystats/easystats/issues/307).

Copy-paste the following text in the README in **Installation** section:

```r
> **Tip**
>
> **Instead of `library(datawizard)`, use `library(easystats)`.**
> **This will make all features of the  easystats-ecosystem available.**
>
> **To stay updated, use `easystats::install_latest()`.**
```

**Replace the library name with the correct one.**

# Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard

**Comment by IndrajeetPatil** [comment]
Oh, and don't forget to reknit the `.Rmd` to `.md` because this is not automated.

**Comment by strengejacke** [comment]
Do we have a special formatting for this paragraph?

**Comment by IndrajeetPatil** [comment]
Is this too ugly?

![Screenshot 2022-09-19 at 18 10 38](https://user-images.githubusercontent.com/11330453/191063362-712a60e1-2ded-42e6-8115-2191551ab5de.png)

**Comment by mattansb** [comment]
Looks good to me.

**Comment by strengejacke** [comment]
Should we also add a sentence like: haven't installed "easystats" yet? Type `install.packages("easystats")` in your R console

(or similar)?

**Comment by strengejacke** [comment]
Am I still maintainer of _see_?

**Comment by IndrajeetPatil** [comment]
Yes, but we can change that.

**Comment by strengejacke** [comment]
Yeah, I had [this discussion](https://github.com/easystats/easystats/issues/113#issuecomment-1229157537) in mind. I don't mind being maintainer of _see_, as well, but I think more "equally distributed" maintainer roles look better ;-)

**Comment by strengejacke** [comment]
> Replace the library name with the correct one.

You had `datawizard` in all commits ;-)

**Comment by IndrajeetPatil** [comment]
_merde_

Sorry about that. Did you modify it? If not, I can do it later.

**Comment by strengejacke** [comment]
no, didn't modify yet, currently no R at hand
