### ISSUE TITLE
Simplify conditional expressions in tests 

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#309]
Throughout the ecosystem, for each test, we seem to check if the package itself is installed and if _testthat_ is installed.
For example, 

```r
if (requiet("testthat") && requiet("insight")) { ... }

if (requiet("testthat") && requiet("parameters")) { ... }
```

Why is this necessary? I think we should remove these and simplify the skipping logic.

For example, if _insight_ itself cannot be installed, how could tests even be running? We will never get to the testing stage.
Also, if _testthat_ itself is not available, no tests will be run, so the tests by definition can't fail.

This is complicating conditional skipping, which is already complex enough.

[For example](https://github.com/easystats/parameters/blob/main/tests/testthat/test-model_parameters_robust.R),

```r
if (requiet("testthat") &&
  requiet("parameters") &&
  requiet("sandwich") &&
  requiet("clubSandwich") &&
  requiet("datawizard")) { ... }
```

**Comment by IndrajeetPatil** [comment]
I don't do this once in `{datawizard}`, and there have been no issues whatsoever - either on CRAN or on GHA.

**Comment by rempsyc** [comment]
I was wondering about that too!

**Comment by strengejacke** [comment]
If I run these tests manually, I have to load these packages. So it's also a bit lazyness to not type `library()` multiple times.

**Comment by IndrajeetPatil** [comment]
Huh? 

But `testthat.R` [file](https://github.com/easystats/datawizard/blob/main/tests/testthat.R) _always_ loads libraries.

So you don't need to manually load them either for `devtools::test()` or for `devtools::test_active_file()`.

**Comment by IndrajeetPatil** [comment]
Also, by the same token, you don't need to skip conditional on the availability of the hard dependencies.

So, this

```r
if (requiet("testthat") &&
  requiet("parameters") &&
  requiet("sandwich") &&
  requiet("clubSandwich") &&
  requiet("datawizard")) { ... }
```

should instead just be

```r
if (requiet("sandwich") && requiet("clubSandwich")) { ... }
```

If `{datawizard}` is not installed, `{parameters}` won't be either, and no tests will be run.

**Comment by strengejacke** [comment]
> Huh?
> 
> But `testthat.R` [file](https://github.com/easystats/datawizard/blob/main/tests/testthat.R) _always_ loads these libraries.
> 
> So you don't need to manually load them either for `devtools::test()` or for `devtools::test_active_file()`.

Yes, but I mean if I run a specific test-file manually, not the complete tests. But the main reason for having this is just because it has grown over time, and back some months/years ago, we weren't aware about the skip-functions.

**Comment by IndrajeetPatil** [comment]
Okay, we definitely need to make this change.

Closing in favour of #310.

**Comment by mattansb** [comment]
> I don't do this once in {datawizard}, and there have been no issues whatsoever - either on CRAN or on GHA.

Same for effect size.


> If I run these tests manually, I have to load these packages. So it's also a bit lazyness to not type library() multiple times.

@strengejacke, you can add this at the top of the script:

```R
if (interactive()) {
  library(insight)
  library(testthat)
  library(see)
}
```

**Comment by IndrajeetPatil** [comment]
> Same for effect size.

Unfortunately, not true:
https://github.com/easystats/effectsize/search?l=R&q=require

<img width="553" alt="Screenshot 2022-09-23 at 12 51 20" src="https://user-images.githubusercontent.com/11330453/191945447-0a7dbcec-ba3d-4ce0-b741-3519744b23dd.png">

**Comment by mattansb** [comment]
Um, check again :P

**Comment by IndrajeetPatil** [comment]
Haha, awesome!
