### ISSUE TITLE
New member: Michael

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#31]
Welcome to @humanfactors to easystats 🎉

I am personally happy to have you here in as it seems that you are the first member in my timezone 😁

So for the traditional introduction, easystats is an open and collaborative project mainly centred (at least for now) around building tools surrounding statistical models, with a focus on user experience; carefully considering functions' design, names, argument names etc. to maximize clarity, intuitiveness, and accessibility. Our target audiences are both beginners (to which we provide a way of easily obtaining complex and relevant information) and experts, that can use our specialized packages and incorporate them in their work.

Do not hesitate to tell us a bit more about who you are, what are your interests and what skills (if any) you're are interested to develop. After all, this project is also the occasion for us to experiment and learn ☺️ 

Feel free to comment, give suggestions or such whenever you feel comfortable enough. You might see us ping specific people from time to time, but we encourage everyone to give their opinion and thoughts even if not directly pinged (or just reacting with a 👍).

I can only recommend to "watch" (follow) all the 11 easystats repos, to be notified of what's going on, as we usually work in parallel :)

Just to give you some context, the work is currently focused on the following roadmap:

- performance v2 CRAN release
- parameters initial CRAN release

These two packages are the foundations of the `report` package, which will depend on them. Once they are "stabilized" (especially parameters), we will be able to give `report` the love it deserves and make it available to the world 😉 

Anyway, feel free to share any thoughts, ideas, suggestions or good jokes.

@strengejacke @pdwaggoner @mattansb @IndrajeetPatil

**Comment by humanfactors** [comment]
Hello easystats team, glad to be here in the easyverse! Thank you for the warm welcome @DominiqueMakowski 😊 

**To share a bit about myself**
I’m a research fellow at the Future of Work Institute, Curtin University, in Perth, Western Australia (the most isolated capital city in the world). I submitted my PhD just last week, and am also a new dad! My research is quite interdisciplinary, but mostly falls within the bounds of human factors psychology.

**What drew me to easyverse?**
A passion for research methods, programming and data processing drew me into the _easyverse_. I’ve advocated and educated in the open science space for a few years now, and from my experience at workshops, I’ve seen that computational challenges (e.g., accessibility, reproducibility) remain one of the biggest barriers to broader adoption of reproducible research. This project has got serious potential to encourage a more rapid adoption of open science practices from those new to R and experts alike.

More broadly, however, I also see this ecosystem having the potential to influence education practices, and also simply improving the quality of work-life for any researchers that work with R models (also thankyou @strengejacke `sjPlot` has been a great help). Honestly, a lack of standardisation, constisent naming, and vague documentation in many R packages made me greatly frustrated with R, but I'm now learning to harness the frustration for improvement. So hopefully will be able to help:
> tame, discipline and harness the scary R statistics and their pesky models

and of course (I couldn't put it better myself) to

> carefully [consider] functions' design, names, argument names etc. to maximize clarity, intuitiveness, and accessibility


**Skills?**
I'm not sure how best to describe my skills. I haven't released a package on CRAN before (or even on Github), but I'm comfortable with the Git workflow, unit testing and packaging? My previous packages have generally been small and internal for specific projects. However, I've been wanting to get collaboratively involved with a larger open-source community for a while now.

I'm really interested in the [Rmarkdown](https://github.com/easystats/report/issues/17) issue for the report package, as I've developed a set of utility functions in various projects for a few years now for automating extraction and reporting of models and tests in Rmarkdown. 

-----------------

Thanks for the warm welcome, feel free to ping me at any point. The watching is a good idea, and I look forward to seeing where I can best help out.

Cheers!

**Comment by pdwaggoner** [comment]
Welcome @humanfactors ! Congrats on the newly-minted Ph.D., and also on being a father! I too am a dad of two little girls, and it's likely the best thing in the world. Welcome!

**Comment by DominiqueMakowski** [comment]
Congrats indeed @humanfactors to your 2 new children (I count your thesis as one 😅) 

> I'm really interested in the Rmarkdown issue for the report package

I'll be looking for your input for that when we will start working to update and expand report ☺️
