### ISSUE TITLE
Simplify conditional expressions in tests

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#310]
# Preamble

Discussed and decided in #309

No need to check if any of these packages are available, since, if they weren't, no tests will be run:

- testthat
- the package being tested
- any of the hard dependencies

# Example

For example, in `{parameters}` package, the following

```r
if (requiet("testthat") &&
  requiet("parameters") &&
  requiet("sandwich") &&
  requiet("clubSandwich") &&
  requiet("datawizard")) { ... }
```

should be changed to

```r
if (requiet("sandwich") && requiet("clubSandwich")) { ... }
```

# Progress tracker

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
While doing this change, if you also want to address #86 and https://github.com/easystats/easystats/issues/294 is up to you.

**Comment by strengejacke** [comment]
I think the file `helper_requiet.R` already includes a skip-statement, so we should be even ok doing

```r
requiet("sandwich")
requiet("clubSandwich")
```

right, @vincentarelbundock ?

**Comment by IndrajeetPatil** [comment]
No, it won't skip. We need to define the following helper in `tests/testthat/helper.R`

```r
skip_if_pkg_not_available <- function(package) {
  if (!suppressPackageStartupMessages(require(package, warn.conflicts = FALSE, character.only = TRUE))) {
    testthat::skip(paste("Package", package, "is not available."))
  }
}
```

And use it in tests like so:

```r

test_that("...", {
  skip_if_pkg_not_available("sandwich")
  skip_if_pkg_not_available("clubSandwich")
  ...
})
```

**Comment by vincentarelbundock** [comment]
I do think ˋrequiet` skips when not installed. Why do you say it doesn't?

Also, we don't need to define our own because there is ˋtestthat::skip_if_not_installed()`

**Comment by strengejacke** [comment]
> Also, we don't need to define our own

I think your intention to add the `helper_requiet.R` file was to suppress all the pkg startup messages.

**Comment by IndrajeetPatil** [comment]
> Also, we don't need to define our own because there is ˋtestthat::skip_if_not_installed()`

Yes, but it doesn't load the library. It just checks if the package is installed. So we will need to do `skip_*()` + `library()`, which doubles the work.

The custom skip I am referring to does the both in one fell swoop, so it's a drop-in skip replacement for the current conditional expression.

**Comment by vincentarelbundock** [comment]
My intention was to BOTH load silently and skip if not installed. See here: https://github.com/easystats/insight/blob/main/tests/testthat/helper-requiet.R

**Comment by IndrajeetPatil** [comment]
Ah, sorry, missed that aspect of it then.

But, in that case, we just need to rename the existing `requiet()` to `skip_if_pkg_not_available()` because the former name doesn't clarify that this is skip function.

**Comment by vincentarelbundock** [comment]
So yes, my requiet should do exactly what @IndrajeetPatil was looking for. Ideally we would have a bunch of requiet calls at the top of a script, and no if{}

**Comment by vincentarelbundock** [comment]
> Ah, sorry, missed that aspect of it then.
> 
> 
> 
> But, in that case, we just need to rename the existing `requiet()` to `skip_if_pkg_not_available()` because the former name doesn't clarify that this is skip function.

And your name doesn't clarify that the package is loaded...

But I really don't mind. I just think we should minimize work and strive for consistency.

**Comment by IndrajeetPatil** [comment]
Happy to rename, but any function that is skipping tests should start with `skip_*()`; that's the only expectation I have while naming it.

**Comment by strengejacke** [comment]
`load_quietly_or_skip_if_not_installed()` 😬

**Comment by strengejacke** [comment]
`load_or_skip()`, both indicates that the package is loaded and skipped if not available.

**Comment by IndrajeetPatil** [comment]
`skip_or_load()` 😜

Looks like great content for my slide deck on [naming things](https://indrajeetpatil.github.io/second-hardest-cs-thing/#/title-slide). 😅

**Comment by mattansb** [comment]
`skip_if_not_available_comma_otherwise_load_quietly()`

**Comment by bwiernik** [comment]
`skip_if_not_available_comma_otherwise_load_quietly_please()`

**Comment by strengejacke** [comment]
What about `only_start_testing_when_all_tests_pass()`?

**Comment by IndrajeetPatil** [comment]
@rempsyc Can you please check if this is already fixed for `{report}`? I had intermittently made these changes, but not sure if there are any remaining instances where clean-up is needed.

**Comment by IndrajeetPatil** [comment]
Just checked and removed the remaining instances. All set now. 

Please be careful not to re-introducing unnecessary conditions like the ones mentioned in the top-level comment in the future.

![giphy](https://user-images.githubusercontent.com/11330453/214634041-1649172f-78fa-4854-a64a-5fcaa704379d.gif)
