### ISSUE TITLE
Add package information to Roxygen docs

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#314]
Each package should have a file called `R/{{pkgname}}-package.R`, so that when users run `?pkgname`, they get information about the package.

For example, this is what you see if you do `?insight`

```r
> ?insight
No documentation for ‘insight’ in specified packages and libraries:
you could try ‘??insight’
```

Contrast this with what you get if you do (e.g.) `?dplyr`.

For an example of how to make this change, see [this](https://github.com/easystats/see/commit/48f18bbb1377b24ea65e5e71907ab49a31006523) commit in `{see}` package. You just need to copy-paste content in the `DESCRIPTION` to this file; the rest `{roxygen2}` will take care of.

Oh, one thing I forgot in that commit is include the tag `#' @keywords internal` so that `{pkgdown}` builds don't fail.

# Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
Sorry, should have mentioned that you need to load it first.

```r
library(dplyr)
?dplyr
```

**Comment by strengejacke** [comment]
Doesn't work straightforward for _parameters_ and _performance_, as we also have the aliases `parameters()` and `performance()`. So it only works for `?'parameters-package'`.

**Comment by IndrajeetPatil** [comment]
Ah, good point.

> So it only works for ?'parameters-package'.

Yeah, that should be enough.

**Comment by IndrajeetPatil** [comment]
Thanks a ton, @etiennebacher! 💕
