### ISSUE TITLE
Next release cycle

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#315]
I need to update `{ggstatsplot}` before 2022-10-21, but before I can do that, `{effectsize}`, and `{correlation}` need to be updated.

So the order can be something like this:

- [x] _correlation_ (since it requires no other updates, and it's urgent because Bayesian correlations are failing; cf. https://github.com/easystats/correlation/issues/269)
- [x] _effectsize_

And then I can update both _statsExpressions_ and _ggstatsplot_.

**Comment by strengejacke** [comment]
_parameters _ is fairly recent, why do we need an update here? Same probably for _insight_.

**Comment by IndrajeetPatil** [comment]
Because ggstatsplot currently relies on development version of statsExpressions, which itself relies on development versions of parameters and effectsize, which in turn relies on development version of insight.

CRAN doesn't mind the next update being after 7 days, so shouldn't be an issue.

**Comment by strengejacke** [comment]
But there's nothing new in the _parameters_ dev version ❓

**Comment by strengejacke** [comment]
And it seems that _effectsize_ works with CRAN _insight_.

**Comment by IndrajeetPatil** [comment]
Ah, okay. Sorry, forgot that you updated them this week.

Okay, then only _effectsize_ and _correlation_ need to be updated.

**Comment by mattansb** [comment]
Alright, I'm on it (:

**Comment by IndrajeetPatil** [comment]
@strengejacke I'd also recommend that we updated the meta-package and get rid of all these NOTEs. We shouldn't wait to get an email about this 🙃

https://cloud.r-project.org/web/checks/check_results_easystats.html

**Comment by IndrajeetPatil** [comment]
@bwiernik I have submitted _correlation_ to CRAN, so you should have received an email about submission.

**Comment by IndrajeetPatil** [comment]
Thanks, @bwiernik! Okay, _correlation_ update is now on CRAN.

**Comment by strengejacke** [comment]
@easystats/core-team Should we start having a "backup branch" from the very latest CRAN release? E.g. I did this for _parameters_ and _performance_: https://github.com/easystats/parameters/tree/release_0_19_0_branch

In this case, the breakage of _ggstatsplot_ and _statsExpressions_ could be resolved by updating _correlation_. But what if _parameters_ had to be submitted to CRAN now? We had some breaking changes in the current dev, defuncting and removing functions (e.g. https://github.com/easystats/parameters/commit/7f3f874cb9c50aca7d24eab0469cb9216b0ccc9d). It _could_ be that we cannot submit an emergency update from this branch w/o complications. But we can add a patch to the release branch and submit from there (which I did here: https://github.com/easystats/parameters/commit/4021698368464f7c3160060edbaad542780abac5, but wasn't necessary because updating _correlation_ was enough).

**Comment by strengejacke** [comment]
> @strengejacke I'd also recommend that we updated the meta-package and get rid of all these NOTEs. We shouldn't wait to get an email about this 🙃
> 
> https://cloud.r-project.org/web/checks/check_results_easystats.html

Yes, we could do that. Though I would _love_ to have at least one vignette at least in a first, preliminary version (https://github.com/easystats/easystats/pulls).

**Comment by IndrajeetPatil** [comment]
_effectsize_ is also on CRAN.

**Comment by IndrajeetPatil** [comment]
> Though I would love to have at least one vignette at least in a first, preliminary version

I think we should make a release soon, because vignettes are unlikely to be ready anytime soon. 

I don't think the release schedule should be tied to it. Likewise, I'd like to get the current devel version on CRAN ASAP because it has breaking changes. The longer we wait, the more likely it becomes that the users will use the functions that have already been removed.

**Comment by strengejacke** [comment]
agree. but which breaking changes we have?

**Comment by IndrajeetPatil** [comment]
```md
## Breaking Changes

- The minimum needed R version has been bumped to `3.6`.

* Following functions have been removed since they are not expected to be of
  any relevance for the users:

  - `CRAN_checks()`
  - `on_CRAN()`
```

**Comment by strengejacke** [comment]
ah yes, these have been moved to the dashboard, right?

**Comment by IndrajeetPatil** [comment]
Yepp

**Comment by strengejacke** [comment]
I think it takes some days until builds for win-builder checks are ready, since _easystats_ relies on the latest package versions. Will submit in the beginning of December.
