### ISSUE TITLE
Mimic and get builds to pass for CRAN's "noSuggests" check in CI/CD

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#317]
# Preamble

I have added a new GHA to all repos called `R-CMD-check-hard`. This workflow is designed to mimic the "noSuggests" check CRAN/BDR run once in a while. It only directly installs "hard" dependencies, i.e. `Depends`, `Imports`, and `LinkingTo` dependencies. Notably, `Suggests` dependencies are never, except for _testthat_, _knitr_, and _rmarkdown_, are installed. 

Package builds should not fail under this check. That is, all usages of suggested packages in examples, tests, and vignettes should be conditional. This will be a good preventative practice to protect against the threat of archival just because one of our suggested packages gets archived.

The workflow file can be seen [here](https://github.com/easystats/workflows/blob/main/.github/workflows/R-CMD-check-hard.yaml).

# Progress tracker:

The task here is to get this check to succeed.

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
`{effectsize}` check already succeeds 🥹

It definitely gets **"The most well-maintained package in _easystats_"** award!

**Comment by mattansb** [comment]
![](https://media.tenor.com/lUa8W5x5WukAAAAS/funny-animals-monkey.gif)

**Comment by etiennebacher** [comment]
> mimic the "noSuggests" check CRAN/BDR run once in a while

Do you know how often they run this check? I'm surprised we never had an error related to this "noSuggests" check in `datawizard` (although there are failures when we run it on GHA).

**Comment by IndrajeetPatil** [comment]
Oh, maybe I didn't phrase it properly. The actual CRAN check would produce an error only if any of the suggested packages is no longer available. That has never been the case for _datawizard_. All of our suggests have always been present on CRAN. We are just pretending that they might be archived and making sure that that scenario still won't create any problems for us. Just to be future proof.

**Comment by etiennebacher** [comment]
Ah ok, got it now, thanks

**Comment by IndrajeetPatil** [comment]
Thanks a lot, @etiennebacher, for taking care of this!

**Comment by IndrajeetPatil** [comment]
@etiennebacher Can you please have a look at _performance_?

**Comment by strengejacke** [comment]
It's mostly due to the new checks from https://github.com/easystats/performance/pull/511, so we have to skip this test when required packages are not available: `test-check_outliers.R`

**Comment by IndrajeetPatil** [comment]
We have already taken care of this 🙃 💪

https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2022/11/14
