### ISSUE TITLE
can you *see* the 100 🌟🥇 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#32]
today `see` was the first of our packages reaching 100 stars ⭐️ 🎉 

I like to believe it's only the start :)

The project is only 10 times bigger (89% CI [9.2, 10.7], p < .01)  than what was originally thought. And that is thank to all of you for being part of this small team and contributing one way or another.

And there is still much to be done for an *easyfuture* 😉 

@strengejacke @pdwaggoner @mattansb @IndrajeetPatil @humanfactors

**Comment by DominiqueMakowski** [comment]
(((Although much could be theorized about the apparent [discrepancy](https://github.com/easystats/easystats#cumulative-downloads) between the number of CRAN downloads and Github stars... 😁)))

**Comment by IndrajeetPatil** [comment]
Woohoo!!! Congrats! 💯

**Comment by mattansb** [comment]
AWESOME!!! 😎

**Comment by humanfactors** [comment]
Glad to see the community and interest growing! I look forward to developing my more serious contributions over time 😊 Well done all 🐱‍💻✨🎉🎉
