### ISSUE TITLE
Make sure website builds successfully in "noSuggests" mode

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#325]
This is a follow-up on https://github.com/easystats/easystats/issues/317.

The `R-CMD-check-hard` workflow made sure that every `{easystats}` package is using its soft dependencies conditionally. But what it misses is running the same check for "website-only" vignettes (e.g. see [this](https://github.com/easystats/bayestestR/tree/main/vignettes/web_only)).

I've added a new `pkgdown-no-suggests` workflow that makes sure that all soft dependencies are being used conditionally, even in vignettes which are not run on CRAN. 

# Progress tracker:

- [x] insight 
- [ ] modelbased
- [ ] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [ ] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by mattansb** [comment]
Why do we need this? This is messing up some pkgdown hack I had going on (linking to related functions from across easystats)...

**Comment by IndrajeetPatil** [comment]
The idea is to use soft dependencies conditionally even if we are not shipping some vignettes to CRAN. In addition to following the best practice, the advantage is that we are future proof. That is, if we decide to ship such vignettes to CRAN once again, we will still pass "noSuggests" workflow on CRAN.

That said, feel free to delete this workflow if you don't find it useful. It's the least important of our workflows.

**Comment by mattansb** [comment]
Ah got it. 
Then my options are to add correlation as a dep to effectsize, but I don't see the need for that, so I'm deleting the workflow from effectsize (:

**Comment by IndrajeetPatil** [comment]
Can you point me to the hack you are using?

**Comment by mattansb** [comment]
https://github.com/easystats/effectsize/blob/f79d9dca45261af89d9cf1a94463514d66687909/_pkgdown.yml#L41-L55

**Comment by IndrajeetPatil** [comment]
@etiennebacher Would you have time to help out with this issue? There are only 3 packages remaining now.

**Comment by etiennebacher** [comment]
Seems that this workflow works fine for these packages?

https://github.com/easystats/bayestestR/actions/workflows/pkgdown-no-suggests.yaml
https://github.com/easystats/modelbased/actions/workflows/pkgdown-no-suggests.yaml
https://github.com/easystats/report/actions/workflows/pkgdown-no-suggests.yaml

**Comment by IndrajeetPatil** [comment]
Strange. Not sure what changed that these are now working successfully.

At any rate, nothing more to do here then. :)
