### ISSUE TITLE
Make sure all examples run successfully or are not run when necessary

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#326]
I have added a new GHA workflow to make sure that all examples run successfully, even the ones that are not supposed to be run or tested on CRAN machines by default. This is because these examples are actually executed in a special check, which is run once in a while by [BDR](https://www.stats.ox.ac.uk/pub/bdr/donttest/). Even if this were not the case, we should still make sure that examples execute successfully.

The examples that fail should use

 - `if (FALSE) { ... }` (if example is included only for illustrative purposes and isn't supposed to be run as is; dummy code, e.g.)
 - `try({ ... })` (if the intent is to show the error)

The new workflow helps find such failing examples that need to be modified.

# Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
@etiennebacher Do you think you will have time to help me out with this one? Only three packages are remaining now.

**Comment by etiennebacher** [comment]
Looks like it works already for modelbased?

https://github.com/easystats/modelbased/actions/workflows/check-all-examples.yaml

I won't have much time in the next few days, let's see at the end of the week

**Comment by IndrajeetPatil** [comment]
Only two remain then.

> I won't have much time in the next few days, let's see at the end of the week

Thanks, that would be great.

**Comment by IndrajeetPatil** [comment]
Only _bayestestR_ remains now.
