### ISSUE TITLE
About the new `R-CMD-check-devel-easystats` workflow

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#329]
## Preamble

In the book [Accelerate](https://www.amazon.de/-/en/Nicole-Ph-D-Forsgren/dp/1942788339), the authors demonstrate that the key difference between high-performing vs low-performing software teams is the ability to make a release at the drop of a hat.

For us, this translates to making sure that the `main`-branch is always in sync with the rest of the development version of `easystats`, and being ready to make a CRAN release with the latest commit on the `main`, without having to worry whether the reverse `easystats` dependencies have already been updated for any potential breaking changes. 

For example, `{datawizard}` relies on `{insight}`, and so this check would make sure that the latest commit on `{datawizard}`'s `main`-branch plays nicely with the latest commit on `{insight}`'s `main`-branch. This is currently [the case](https://github.com/easystats/datawizard/actions/workflows/R-CMD-check-devel-easystats.yaml).

This is also important because we provide `easystats::install_latest()` function, which assumes that all packages are in sync with each other, and it would be good to have an objective check for this.

## Workflow 

To make sure that all packages are in sync with each other, I have created and added a new `R-CMD-check-devel-easystats`, which runs `R CMD check` on the given package using the development versions of `easystats` packages. It's run once every day at midnight. So you just need to make sure that this workflow isn't failing. If not daily, at least check once a week.

## Progress tracker

There is no progress tracker here, since making sure that this check pass is a continuous process. This post is meant merely to inform you of this check.

**Comment by etiennebacher** [comment]
I don't understand something here. Basically, unless I misunderstood, you want every package to run checks with the latest versions of their dependencies to see if something breaks. But that delegates the "check responsibility" to the downstream packages. Why would this be more efficient than running revdepcheck once a day in the upstream packages (e.g `{insight}`)?

To take an example, `{ìnsight}` is used in all `easystats` packages, so if there's a breaking change that affects all packages, each of these packages will have to find why there's an error and this will lead to the change in `{insight}`. Isn't it more efficient to run `revdepcheck` in `{insight}` once a day before pushing the code to `main`? (I suppose we can restrict the reverse deps we want to check to `easystats` packages).

**Comment by IndrajeetPatil** [comment]
Yes, this might also be another way to go about this. 

But I would maintain that it's not our responsibility to check at every commit that every non-_easystats_ dependency is working as expected. This is something that we need to do only when we are ready for a CRAN release. 

For example, currently, _insight_ has only about two dozen reverse dependencies. In 10 years, this might be grow to 100. It's not possible for us to check and inform every day about any breaking change that might have surfaced that day because we may choose to revert that change before CRAN release.  We only wish to guarantee that the _easystats_ ecosystem is internally coherent at every commit to the default branch. 

There is also technical limitation: we use the free version of GHA, which allows jobs to run for certain time, and with enough reverse dependencies, we will exceed this time.

**Comment by etiennebacher** [comment]
> But I would maintain that it's not our responsibility to check at every commit that every non-easystats dependency is working as expected.

Agreed, that's why I suggested to limit the revdep checks to the `easystats` packages (which I'm not sure is possible but I guess it should be)

**Comment by IndrajeetPatil** [comment]
AFAIK, it's not possible with _revdepcheck_ to restrict checks only to certain packages. 

If you can figure out a way to the contrary, then happy to switch to the suggested approach.

**Comment by IndrajeetPatil** [comment]
I have changed the frequency for this workflow: it will now be run only once a week.

I don't think we are developing actively enough to waste CI/CD cycles on a daily basis.
