### ISSUE TITLE
Workflow to ensure that there are enough example to explain functionality

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#331]
## Preamble

In order to make sure that we have enough examples in the documentation that showcases our public API, I have added a new workflow. It makes sure that there are examples to cover at least half of the functionality the package offers. That is, it makes sure that the code coverage through examples is over 50%. I think that's a reasonable threshold to adopt, at least to start with.

For an example, see [this](https://github.com/easystats/datawizard/actions/runs/3688906640/jobs/6244256089) run in `{datawizard}` (which currently has 57% code coverage via examples).

## Tip

One issue might be that you do have examples, but they are not run on CRAN because they take too much time. This means, `{covr}` won't be able to run these examples. A way around this is to skip the examples only on CRAN.

Change any of the following patterns 

```r
#' @examplesIf FALSE && ...
```

or 

```r
#' @examples
#' \donttest{}
```

with

```r
#' @examplesIf identical(Sys.getenv("NOT_CRAN"), "true") && ...
```

## Progress tracker:

- [x] insight 
- [x] modelbased (67%)
- [x] bayestestR
- [x] effectsize (60%)
- [x] parameters
- [x] performance
- [x] correlation (53%)
- [x] report (60%)
- [x] see (50%)
- [x] datawizard (57%)
- [x] easystats

**Comment by IndrajeetPatil** [comment]
Note that it's not important to spend time actively increasing this code coverage, as long as it's over 50%. Examples are just one way, although the most user-facing way, to demonstrate functionality - the other ways being README and vignettes.

**Comment by rempsyc** [comment]
I know some say examples shouldn't be too long ("for that see the vignette"), but I personally love it. It's the number one factor they will help me understand or use what I need when using a package/function. It's fast and convenient and you don't need to go hunting for the info. Way to go!

**Comment by IndrajeetPatil** [comment]
@strengejacke Please have a look at this issue to see what the code coverage through examples workflow is about.

**Comment by strengejacke** [comment]
I think this check is often pretty useless. E.g., `insight::model_info()` examples have a coverage of ~4%. Not sure why, I guess it is because we have dozens of methods for the different model classes. So the only way to repeat example coverage would be copying the same line dozens of times, each time using a different model class? That would not add anything to the previous / existing examples and not increase understanding on a user-level, I guess.

**Comment by IndrajeetPatil** [comment]
> I think this check is often pretty useless. 

You can just delete the workflow files you don't find useful (they are [here](https://github.com/easystats/insight/tree/main/.github/workflows)) for repos you maintain. 

> So the only way to increase example coverage would be copying the same line dozens of times, each time using a different model class? That would not add anything to the previous / existing examples and not increase understanding on a user-level, I guess.

It is likely that the coverage is so low because you are skipping a lot of examples on CRAN using `\donttest`. Those won't be counted while computing code coverage. I have included a tip in my top-level comment on how to sidestep this issue, if you are interested.

**Comment by IndrajeetPatil** [comment]
E.g. [here](https://github.com/easystats/see/commit/134097f57d5264c6ccf6584c332b85e96bf55d41) is how I increased code coverage through examples for `{see}` without adding any new examples.

**Comment by strengejacke** [comment]
> It is likely that the coverage is so low because you are skipping a lot of examples on CRAN using `\donttest`. Those won't be counted while computing code coverage. I have included a tip in my top-level comment on how to sidestep this issue, if you are interested.

Hm, not sure. See https://easystats.github.io/insight/reference/model_info.html, where the first example is fully run (and there's not much more about `model_info()`), yet the example code coverage is < 5%:
![image](https://user-images.githubusercontent.com/26301769/209167940-7c4fb5d1-9244-4c77-80f3-61943e0d929e.png)

**Comment by strengejacke** [comment]
Or `link_inverse()` is ~1%, although 1 out of 5 methods is shown in the examples, so from my naive understanding it should be ~20%?

**Comment by IndrajeetPatil** [comment]
If you want to reproduce this locally, run the following in the package root directory:

```r
library(covr)
coverage <- covr::package_coverage(type = "examples", quiet = TRUE)
report(coverage)
```

Then you can see exactly which lines are covered by examples while computing code coverage.

**Comment by IndrajeetPatil** [comment]
This should be fixed for all repos now. I have modified the workflow to ensure that dontun and donttest examples are also run.

**Comment by strengejacke** [comment]
> If you want to reproduce this locally, run the following in the package root directory:
> 
> ```r
> library(covr)
> coverage <- covr::package_coverage(type = "examples", quiet = TRUE)
> report(coverage)
> ```
> 
> Then you can see exactly which lines are covered by examples while computing code coverage.

Ok, then the title is a bit misleading. "Workflow to ensure that there are enough example to explain functionality" is something different than code coverage from examples. In case of _insight_, _parameters_ or _performance_, I'd say we don't need this workflow, because even examples that explain the API 100% may only have a code coverage of < 5%, because we have methods for many classes, that all work in the same manner (from a user/API perspective), but still need _tests_ for each class.

**Comment by IndrajeetPatil** [comment]
Sounds good.

Feel free to delete it for those repos. 

For all high-level, user-facing packages, I would personally prefer to have at least 50% codebase covered through examples. 

(For personal package repos, I use a threshold of 90 or 95.)

**Comment by strengejacke** [comment]
And when will ever this "FreeADFunObject" error go away? 😢

**Comment by IndrajeetPatil** [comment]
We should create an issue glmmTMB repo and ask for help. 

It's really bugging us across the repos.

**Comment by IndrajeetPatil** [comment]
I had already created issue about this here as a reminder:

https://github.com/easystats/parameters/issues/823

**Comment by IndrajeetPatil** [comment]
On a second thought, I think it makes sense to also include vignettes while computing code coverage through examples.

That is, the workflow now checks that combined examples across manual and vignettes cover at least 50% of the code.
A fly in the ointment is that vignettes which are `.Rbuildignore`-ed (an idiom we have adopted to avoid running time-consuming vignettes on CRAN) won't count since they are not visible to `{covr}`.

@strengejacke I will leave it up to you to decide whether you want to add back the workflows you had deleted from repos you maintain.
