### ISSUE TITLE
Why do we explicitly load datasets?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#333]
For example, the following two lines of code are currently seen in [91 files](https://github.com/search?q=org%3Aeasystats+data%28iris%29&type=code) and [136 files](https://github.com/search?q=org%3Aeasystats+data%28mtcars%29&type=code), resp.:

```r
data(iris)
data(mtcars)
``` 

It is not at all necessary to load these datasets (in examples or vignettes or tests or etc.), as can be seen from this reprex:

``` r
length(iris)
#> [1] 5
length(mtcars)
#> [1] 11
```

<sup>Created on 2022-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So I am wondering why are we doing this?

**Comment by rempsyc** [comment]
Agreed! I always found it weird when I saw this in easystats code. That's only useful if you've overwritten that object earlier, but in reprexes, test, examples, this isn't necessary.

**Comment by mattansb** [comment]
I do this to protect the current use of the file against any previous uses that may have modified it.

``` r
mtcars$cyl <- ordered(mtcars$cyl)
str(mtcars) # cyl is an ordered factor
#> 'data.frame':    32 obs. of  11 variables:
#>  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
#>  $ cyl : Ord.factor w/ 3 levels "4"<"6"<"8": 2 2 1 2 3 2 3 1 1 2 ...
#>  $ disp: num  160 160 108 258 360 ...
#>  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
#>  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
#>  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
#>  $ qsec: num  16.5 17 18.6 19.4 17 ...
#>  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
#>  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
#>  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
#>  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...

data("mtcars")
str(mtcars) # cyl is numeric
#> 'data.frame':    32 obs. of  11 variables:
#>  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
#>  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
#>  $ disp: num  160 160 108 258 360 ...
#>  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
#>  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
#>  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
#>  $ qsec: num  16.5 17 18.6 19.4 17 ...
#>  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
#>  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
#>  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
#>  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...
```

<sup>Created on 2022-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
> I do this to protect the current use of the file against any previous uses that may have modified it.

But isn't one playing with fire by doing so? 
Wouldn't it be better if we got into the habit of first assigning the dataset a new name and then modifying this copy to not worry about such issues?

```r
df <- mtcars
df$cyl <- ordered(df$cyl)
```

**Comment by mattansb** [comment]
What is "dangerous" by doing this?
We maintain the familiar name of `mtcars` instead of an arbitrary `df` or `dat` name...

**Comment by IndrajeetPatil** [comment]
> We maintain the familiar name of mtcars instead of an arbitrary df or dat name...

You can name it `mtcars2` if you want to have a familiar name 🙃

It's not dangerous, it's just that you are probably introducing dependencies which can be extremely hard to debug. 

In a lot of tests, esp. in _parameters_ and _bayestestR_, we do superassignment (`<<-`), which means tests are no longer hermetically sealed, as they should. 

Doing `` iris$`Sepal Width` <<- iris$Sepal.Width `` in [one test file](https://github.com/easystats/parameters/blob/83c505d2280159914f19eeb55390279d58489d8a/tests/testthat/test-backticks.R#L6) will change the `iris` dataset for _all_ test files.

This means you need to remember to load the original `iris` dataset every single time you use it in a different file, and anytime you need to remember anything is every time you are just waiting for someone to forget it. And when they do, it's going to be one hell of a painful debugging session because there is nothing in your current test file to tell you that iris was changed by some other test file. The same goes for examples and vignettes.

**Comment by IndrajeetPatil** [comment]
This situation should be a better with #358 resolved.
