### ISSUE TITLE
Code coverage checks inaccurate?

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#336]
I wonder why https://app.codecov.io/gh/easystats/parameters/blob/main/R/5_simulate_model.R shows 0% coverage, while we have tests for this file (https://github.com/easystats/parameters/blob/main/tests/testthat/test-simulate_model.R), which should actually cover quite a lot of that function.

**Comment by IndrajeetPatil** [comment]
Are you by any chance skipping these tests on non-Windows systems?

We compute code coverage on [Ubuntu](https://github.com/easystats/workflows/blob/6b87b4b8ebae5c795f20a27116c5b05d8e382d75/.github/workflows/test-coverage.yaml#L10), so if some tests are skipped on this OS, they will not contribute towards code coverage.

**Comment by strengejacke** [comment]
yeah, that makes sense. There are some tests that are only run on specific OSes, because there are slightly different results (maybe RNG is not consistent across R versions / OS types?)

**Comment by strengejacke** [comment]
Not exactly sure how to address this, best would be to use the same system for writing tests that is used by code coverage, but I don't have Ubuntu at hand. We _could_ rely on the test results from GHA and use those in tests that should be run on one OS only (like: enabling the tests that currently run on Windows only for Linux, GHA shows the expected Linux results, and we copy those into the test and make the tests conditional on Linux).

**Comment by IndrajeetPatil** [comment]
Are the results across operating systems so different that a threshold can't cover possible values? 

In general, we shouldn't be skipping tests on any of the major OS when we can use a reasonable threshold to cover the range of possibilities.

The only time we are forced to segregate test results by OS is for snapshot tests, and we are already doing that in report.

**Comment by IndrajeetPatil** [comment]
I think one way we can solve this issue for all repos is by running the code coverage always on Windows, if that's our preferred OS.

**Comment by IndrajeetPatil** [comment]
I have switched to Windows for computing code coverage now. So there should be some improvement in coverage across all repos. 

There are no more caveats, the coverage you see if the coverage you have. So you can proceed accordingly.
