### ISSUE TITLE
New workflow to format code and re-document

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#337]
## Preamble

In this issue, I just wanted to mention that I have implemented a new GHA [workflow](https://github.com/easystats/workflows/blob/main/.github/workflows/styler.yaml) to format code and to re-document Roxygen docs in a PR and commit changes in the PR itself.

Note that this workflow will work only for PRs. Our `main` branches are protected, so GHA can't commit to these branches. Even if GHA could commit to `main`, I wouldn't want any non-human agents to have the permissions to push to `main`. 

I think having this automated would mean we don't need to worry about remembering to format or document.

## Example

For an example of this behaviour, see [this](https://github.com/easystats/datawizard/pull/342) PR in `{datawizard}`.

## Feedback needed

I would like to know if you would want this workflow for the repos you are maintaining. 

I am asking for feedback this time because, unlike all of our existing workflows, this is the first workflow that can commit changes. This means that if you commit some changes, and GHA then commits some changes, you will have to pull the changes first, and resolve a merge conflict if you have already made some other changes that you wish to push in the PR. 

cc @easystats/core-team

**Comment by mattansb** [comment]
What will happen if I override a change this has made? Will it re-do that styling choice?
(As we've seen, styler sometimes does a poor job styling roxygen content..)

**Comment by IndrajeetPatil** [comment]
> What will happen if I override a change this has made? Will it re-do that styling choice?]

Yes, it will re-do the same changes.

The only way you can prevent styler from changing some code is by including the following annotations:

```r
# styler: off

# code that you don't want to be styled by `{styler}`
...

# styler: on
```

Then `{styler}` will just skip styling this code and your custom formatting will be preserved.

**Comment by IndrajeetPatil** [comment]
It might be easier to just add the workflow to all repos so that the maintainers can see if they find it useful and delete otherwise.
