### ISSUE TITLE
styling convention

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#34]
Is there a styling convention `easystats` packages are following?

I personally follow `tidyverse` style guide in my packages (https://style.tidyverse.org/) and use `styler` (https://github.com/r-lib/styler) package to stylize code.

**Comment by strengejacke** [comment]
Yes, we do have:
https://github.com/easystats/easystats/blob/master/README.md#convention-of-code-style

Just say if these are unclear.

**Comment by IndrajeetPatil** [comment]
Got it. 

I see none of the `easystats` conventions conflicting with `tidyverse` style so I will be using `styler`-stylized code in my `PR`s.

**Comment by DominiqueMakowski** [comment]
yes, we use styler too. our conventions are currently mainly about names :)
