### ISSUE TITLE
New `R-CMD-check-strict` workflow to check for any `NOTE` in `R CMD Check`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#344]
## Preamble

It's a good idea to make sure that `R CMD Check` not only produces `0 WARNINGS` and `0 ERRORS`, but also `0 NOTES`. Presence of any `NOTE` triggers costly manual inspection during CRAN submission. 

So I have added a new GHA workflow `R-CMD-check-strict`, which is run only on Ubuntu using R-devel, and fails on a `NOTE`.

## Progress tracker

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
Thankfully, half of the packages already pass this check!

**Comment by IndrajeetPatil** [comment]
Only _bayestestR_ remains now. I am not sure why a couple of tests are failing, so someone else will need to fix this, and then this issue can be closed.

**Comment by strengejacke** [comment]
You [removed _rstan_](https://github.com/easystats/bayestestR/commit/cc3164bd82488103d502c0667e20cf956ab0167f) from the DESCRIPTION, which makes checks fail.

**Comment by IndrajeetPatil** [comment]
Can you point to me where rstan is needed? 

I don't see a single example, test, or vignette being run conditionally on _rstan_ being available. This is why I removed it. Every dependency, even if indirect, should be explicitly mentioned somewhere so that others don't have to do any guesswork.

<img width="616" alt="Screenshot 2023-01-11 at 20 44 17" src="https://user-images.githubusercontent.com/11330453/211902806-e6f70929-d563-4034-9c1b-97f7743cd8fc.png">

**Comment by strengejacke** [comment]
time to switch to a better IDE ;-)
![image](https://user-images.githubusercontent.com/26301769/211903199-53845fa9-b5f4-48da-92e9-759eb846fbf9.png)

**Comment by IndrajeetPatil** [comment]
LOL 🤦‍♂️

**Comment by strengejacke** [comment]
Also works with whole word/match case in VSCODE
![image](https://user-images.githubusercontent.com/26301769/211903495-544dd797-d45a-4181-bca5-ec8009d48965.png)

**Comment by IndrajeetPatil** [comment]
Thanks, I have added _rstan_ back in, and am also running the respective tests conditionally now.

**Comment by strengejacke** [comment]
I'm not sure whether this test is too strict. There are notes which are almost unavoidable, see:
https://github.com/easystats/performance/actions/runs/3947835709/jobs/6757124726

Furthermore, CHECK-README either needs to install missing packages or also be more relaxes in this regard, see:
https://github.com/easystats/performance/actions/runs/3947835712/jobs/6757124487

**Comment by strengejacke** [comment]
Same for spelling, I think an "error" is not appropriate here:
https://github.com/easystats/performance/actions/runs/3947835711/jobs/6757124278

**Comment by IndrajeetPatil** [comment]
> I'm not sure whether this test is too strict. There are notes which are almost unavoidable, see:

If you don't want builds to fail on a `NOTE` that CRAN might accept, include the following in the `DESCRIPTION` file:

```dcf
Config/rcmdcheck/ignore-inconsequential-notes: true
```

> Furthermore, CHECK-README either needs to install missing packages or also be more relaxes in this regard, see:

We should never be setting `tidy = TRUE`. We already use `{styler}` package to format code. Furthermore, we don't need to additional use `{formatR}`, which is what will be used if `tidy = TRUE`.

> Same for spelling, I think an "error" is not appropriate here:

If the builds don't fail, you are NEVER going to fix the spelling mistakes. Trust me.

**Comment by strengejacke** [comment]
> Trust me.

![image](https://user-images.githubusercontent.com/26301769/213213649-a0123cbf-a961-46da-aef2-350d0c970e98.png)

**Comment by strengejacke** [comment]
Are we no longer testing on R-devel?

**Comment by IndrajeetPatil** [comment]
We are, but we run strict workflows on R-devel (i.e. 0 NOTEs):

https://github.com/easystats/workflows/blob/04d439696b54675d23850b4d43a439fc67abd9d9/.github/workflows/R-CMD-check-strict.yaml#L23-L24
