### ISSUE TITLE
GHA should fail for oldrelease

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#353]
[Package ape](https://cran.r-project.org/web/packages/ape/index.html) was recently updated on CRAN, which claims to depend on R3.2. However, in function `rtt()`, it uses the code `lm.fit(X, y) |> r.squared()`, which fails on older R version, but it seems to be loaded by GHA for checking, and thus, checking on R-oldrelease fails (see https://github.com/easystats/insight/actions/runs/4238000514/jobs/7364587207#step:7:11744).

How to deal with this? @IndrajeetPatil any ideas?

**Comment by IndrajeetPatil** [comment]
Hmm, the package passes checks on R-oldrel in [CRAN's daily checks](https://cran.r-project.org/web/checks/check_results_ape.html), so seems to work.

But I am ignoring it before `R 4.1` in our [own workflows](https://github.com/easystats/workflows/commit/cbeb1a0edb9e263643ee071c9f4480c534fefe2a).

**Comment by strengejacke** [comment]
R oldrel is 4.1 or so. In our GHA, we check back to 3.6. and ape states R3.2 and higher, so some of our workflows failed.

**Comment by strengejacke** [comment]
> But I am ignoring it before R 4.1 in our own workflows.

That's good, thanks!
