### ISSUE TITLE
Release Cycle Spring 23

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#355]
I think we could submit some updates to CRAN. In particular, _insight_, _parameters_ and _performance_ are on my list, maybe also _datawizard_ and _see_? What about other packages? Is there any need for those, too?

@easystats/maintainers 

- [x] insight
- [x] datawizard
- [x] report
- [x] bayestestR
- [x] parameters
- [x] performance
- [x] see
- [x] correlation
- [x] effectsize

**Comment by etiennebacher** [comment]
The last update of *datawizard* was mid-december and there are 5/6 new functions and other improvements and bug fixes, I think it should be updated soon (sometimes in the next month)

**Comment by strengejacke** [comment]
Yes, would be great, as I plan an R course (introduction into data wrangling and analysis) using easystats.

**Comment by strengejacke** [comment]
@DominiqueMakowski I think we should also update _bayestestR_ (after _insight). I could fix some bugs, and it got some improvements / new features the past months, so an update would be great.

**Comment by strengejacke** [comment]
@etiennebacher _insight_ is on CRAN, go ahead with _datawizard_

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Can we please update _bayestestR_ on CRAN soon? I can't update my packages before then.

**Comment by strengejacke** [comment]
Ok, if there's no need to wait, then you can submit. I think I need to wait for _bayestestR_ first, will check.

**Comment by DominiqueMakowski** [comment]
I am ready to push bayetestR, should I @strengejacke ?

**Comment by strengejacke** [comment]
Yes, from this PR: https://github.com/easystats/bayestestR/pull/593
That's the one we submitted to winbuilder and that should be ok to submit.

**Comment by IndrajeetPatil** [comment]
Okay. I will submit _see_ today after fixing a few pending issues.

**Comment by IndrajeetPatil** [comment]
We also need to make a new release of correlation because some changes to easycorrelation visualization recipes are required in _see_ vignettes. I can still update see on CRAN because we are not shipping vignettes to CRAN, but would be good to have for good user experience.

cc @bwiernik

**Comment by IndrajeetPatil** [comment]
*see* update is on CRAN.

**Comment by strengejacke** [comment]
What's the current submission state of _datawizard_? Once 0.7.1 is on CRAN, I can go on with _parameters_ and _performance_.

**Comment by etiennebacher** [comment]
Need to run revdep just in case but I can resubmit tonight or tomorrow depending on how long it takes

**Comment by strengejacke** [comment]
What's going on with _correlation_? https://cloud.r-project.org/web/checks/check_results_correlation.html @easystats/maintainers

**Comment by IndrajeetPatil** [comment]
cf. https://github.com/easystats/easystats/issues/355#issuecomment-1481710611

**Comment by IndrajeetPatil** [comment]
Everything should already be fixed on GitHub. It's just a matter of submitting it to CRAN.

**Comment by IndrajeetPatil** [comment]
*parameters* 0.20.3 is on CRAN.

**Comment by strengejacke** [comment]
All but effectsize are now updated. @mattansb is there any need/plan to update effectsize, or do you like to submit later?

**Comment by mattansb** [comment]
I have no such plans, and I'd rather put it off if it isn't necessary at this time.

**Comment by strengejacke** [comment]
Yes, not necessary.
Then we are through with this round. 🙂
