### ISSUE TITLE
Avoid test coupling

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#358]
While working on https://github.com/easystats/insight/pull/738/files, I noticed that changing one test file led to test failures in other files when I didn't touch either the source code or these other test files. This happens because our tests are not hermetically sealed. Our tests are coupled due to super-assignment and running code outside `test_that()` calls.

To understand what I mean, let's say these are your two test files:

```r
# `tests/testthat/test-1.R` file
test_that("bla works", {
  m <<- stats::lm(wt ~ mpg, mtcars)
  expect_length(m, 12L)
})

# `tests/testthat/test-2.R` file
test_that("blu works", {
  expect_length(m, 12L)
})
```

If you now run all tests, this is what you will see:

```r
✔ | F W S  OK | Context
✔ |         1 | 1                         
✔ |         1 | 2  
```

Note that, in an ideal testing scenarios, test-2 should know nothing about what happened in test-1, and yet it somehow knows about object `m`. This kind of coupling makes debugging extremely hard when things go wrong, especially in the CI/CD context. 

The solutions here are simple: 

- avoid running code outside `test_that()`, and/or
- instead of using generic names (e.g. `m`, `m1`), use more informative and distinctive names (e.g. `m_AER`, `m_ivreg`)

That way, even with super-assignment, it will be difficult for any coupling to occur between test files.

This might already be the case for some of the packages that don't need to use super-assignment.

## Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
This is exactly why tests that pass in serial run fail in parallel; tests are coupled and need to be run in a certain order, which is a big no-no when it comes to unit testing:

https://github.com/easystats/insight/actions/runs/4491935017/jobs/7901107298?pr=745

**Comment by IndrajeetPatil** [comment]
I have created a new workflow [`check-random-test-order`](https://github.com/easystats/workflows/blob/main/.github/workflows/check-random-test-order.yaml) and added it to all repos to check if there is any coupling that is introducing order effects. If this workflow passes for your repo, you can check the list above.

**Comment by strengejacke** [comment]
Can we somehow find out what the exact issue is when that workflow is indicating a failure? Currently, it just names the failing file, but it's not obvious what the problem might be...

**Comment by strengejacke** [comment]
E.g. here: https://github.com/easystats/parameters/actions/runs/4572379258/jobs/8071564619
I renamed models to unique names and moved code inside the `testthat()` function, but issues still exists... ❓

**Comment by IndrajeetPatil** [comment]
> Can we somehow find out what the exact issue is when that workflow is indicating a failure? Currently, it just names the failing file, but it's not obvious what the problem might be...

Yes, I have already adjusted the workflow yesterday to show the exact errors. So, if you push a new commit, you should see the exact errors.

**Comment by IndrajeetPatil** [comment]
Also, if you want to recreate the failures locally, you can just run the code included in the [workflow](https://github.com/easystats/workflows/blob/ea1e932f1a55b216548c3c1dcd5c0b4dcf6a45e4/.github/workflows/check-random-test-order.yaml#L46-L90). Keep in mind that a different seed is chosen in each run to randomize the order in which tests are executed.

**Comment by strengejacke** [comment]
> E.g. here: https://github.com/easystats/parameters/actions/runs/4572379258/jobs/8071564619 I renamed models to unique names and moved code inside the `testthat()` function, but issues still exists... ❓

Strange, this workflow was started ~ 1 hour ago, or am I missing something?

**Comment by IndrajeetPatil** [comment]
> > E.g. here: https://github.com/easystats/parameters/actions/runs/4572379258/jobs/8071564619 I renamed models to unique names and moved code inside the `testthat()` function, but issues still exists... ❓
> 
> Strange, this workflow was started ~ 1 hour ago, or am I missing something?

Oh, I know what the problem is. The tests in question aren't failing, they are producing errors. That is, the code in `test_that()` doesn't even run successfully. I will fix the workflow to also show error and not just test failures.

**Comment by strengejacke** [comment]
>  The tests in question aren't failing, they are producing errors.

Due to random test order? Else, the test would fail in "usual" order, too, or not?

**Comment by IndrajeetPatil** [comment]
Yes, due to random test order.

The key warning that might explain why this happens is the following:

```r
Found more than one class "mcmc" in cache; using the first, from namespace 'cplm'
Also defined by 'BayesFactor'
```

**Comment by IndrajeetPatil** [comment]
Only one test is failing now (in `test-lme.R`).

**Comment by IndrajeetPatil** [comment]
@rempsyc The tests in _report_ are also coupled. My hunch is that the recommended clean-up in #363 _might_ solve this issue.

**Comment by IndrajeetPatil** [comment]
Thanks in part to the test suite clean-up, the tests no longer seem to be coupled, but this is something we will have to actively maintain as we add new tests and dependencies.
