### ISSUE TITLE
New member: Jacob

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#36]
A very warm welcome to @jacob-long to easystats 🎉, creator of awesome and popular packages such as [panelr](https://github.com/jacob-long/panelr) and [interactions](https://github.com/jacob-long/interactions).

It is our pleasure to have you there :)

A bit about us, easystats is an open and collaborative project mainly centred (at least for now) around building tools surrounding statistical models, with a focus on user experience; carefully considering functions' design, names, argument names etc. to maximize clarity, intuitiveness, and accessibility. Our target audiences are both beginners (to which we provide a way of easily obtaining complex and relevant information) and experts, that can use our specialized packages and incorporate them in their work.

As for what is expected of members? Nothing! But feel free to comment, give suggestions in issues or such whenever you feel comfortable enough. You might see us ping specific people from time to time, but we encourage everyone to give their opinion and thoughts even if not directly pinged (or just reacting with a 👍)

I can only recommend to "watch" (follow) all the 11 easystats repos, to be notified of what's going on, as we usually work in parallel :)

As for a "roadmap context" (where we're currently at), we just released parameters on CRAN, and hard work is currently done to extend its support. General improvements and fixes are brought to `insight`, and the next planned CRAN release will be hopefully `estimate` (for which you might want to share your expertise and opinion, since it has similar features to your `interactions` ☺️).

Anyway, feel free to share any thoughts, ideas, suggestions or memes.

Welcome to you, easyjacob 🙌 

@strengejacke @pdwaggoner @mattansb @IndrajeetPatil @humanfactors

**Comment by IndrajeetPatil** [comment]
Welcome, @jacob-long!

**Comment by mattansb** [comment]
Welcome aboard @jacob-long !

**Comment by strengejacke** [comment]
🥂

**Comment by pdwaggoner** [comment]
Welcome @jacob-long !

**Comment by humanfactors** [comment]
Hello @jacob-long  - looking forward to working with you :)

**Comment by jacob-long** [comment]
Thanks for the welcome everyone! :bowtie:
