### ISSUE TITLE
Evaluate example and vignettes conditionally if they require internet access

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#362]
Follow up on: https://github.com/easystats/easystats/issues/322 (in which we skipped tests conditional on internet access)

Vignettes that require internet access:
https://github.com/search?q=org%3Aeasystats+download_model+language%3ARMarkdown&type=code&l=RMarkdown

Evaluate if `curl::has_internet()` is `TRUE` and all required deps are available.

Examples that require internet access:
https://github.com/search?q=org%3Aeasystats+download_model+language%3AR+path%3A%2F%5ER%5C%2F%2F&type=code

## Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
@easystats/maintainers I have fixed this issue for all relevant repositories.

For future reference, every time you add a test, a vignette, an example, etc. that requires internet access, please evaluate conditional on such access. It's our responsibility to make sure that things fail gracefully when in offline mode.

At some point, I should get to work on https://github.com/r-lib/actions/issues/658 and then this should become part of our CI/CD.

**Comment by rempsyc** [comment]
Just a note: I've had an issue with CRAN where testing for internet access was not enough, because internet was working but the resource (API, website) itself was failing. In this case it also needs to fail gracefully. It was a real nightmare but the trick was using a tryCatch and return NULL with a message.

**Comment by IndrajeetPatil** [comment]
I think Daniel has already done that: https://github.com/easystats/insight/commit/28955f4f71a93dd0f0ad96df2fe6a3648e81ab8c
