### ISSUE TITLE
Use `.R` file extension instead of `.r`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#365]
Here is where they reside:

```r
> fs::dir_ls("Documents/GitHub/", glob = "*.r", recurse = TRUE)
Documents/GitHub/datawizard/R/data_peek.r
Documents/GitHub/datawizard/R/data_write.r
Documents/GitHub/datawizard/R/recode_into.r
Documents/GitHub/insight/R/get_df_ml1.r
Documents/GitHub/insight/R/get_df_residual.r
Documents/GitHub/parameters/R/p_function.r
Documents/GitHub/parameters/R/parameters-package.r
Documents/GitHub/parameters/tests/testthat/test-printing-stan.r
Documents/GitHub/parameters/tests/testthat/test-printing.r
Documents/GitHub/parameters/tests/testthat/test-printing2.r
Documents/GitHub/performance/WIP/docs_check_outliers_iforest.r
Documents/GitHub/performance/tests/testthat/test-mclogit.r
```

The relevant git command: https://git-scm.com/docs/git-mv

**Comment by IndrajeetPatil** [comment]
The point is to follow conventions and be future-proof. 

A lot of tools assume the extension for R scripts to be .R and so you will be in for a surprise or will have to spend a lot of digging into when the said tool works only for some files but not for others.

**Comment by strengejacke** [comment]
VSCode by defaults adds a lower case `.r` to new files:
![image](https://user-images.githubusercontent.com/26301769/229568211-74b31ab3-c52a-400d-9030-553b4765a904.png)

**Comment by IndrajeetPatil** [comment]
I think this is resolved by now?

**Comment by IndrajeetPatil** [comment]
Still not resolved:

```r
> fs::dir_ls(getwd(), glob = "*.r", recurse = TRUE)
/Users/indrajeetpatil/Documents/GitHub/datawizard/R/data_peek.r
/Users/indrajeetpatil/Documents/GitHub/datawizard/R/data_write.r
/Users/indrajeetpatil/Documents/GitHub/datawizard/R/recode_into.r
/Users/indrajeetpatil/Documents/GitHub/parameters/R/p_function.r
/Users/indrajeetpatil/Documents/GitHub/performance/WIP/docs_check_outliers_iforest.r
```

**Comment by IndrajeetPatil** [comment]
Thanks, @strengejacke! 

Commits 6e09435dc978454436faf0d33230d1d69b1ce8ee, ae7df24b9dce7207e361dd7906fc241743fb90f1, e2ac6eb0f93ffa32078ac6082a4d0399117687e2, a8092dd9505f462e6d453fbf8f4046e340eb0279 fix it.
