### ISSUE TITLE
Figure out why total download counts are not included in the README table

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#369]
Instead, `{emmeans}` download counts are included:

<img width="1028" alt="Screenshot 2023-07-11 at 11 21 53" src="https://github.com/easystats/easystats/assets/11330453/057e61cd-c7d3-4f9e-b364-e431a1e41307">

To reproduce, just knit the README.

**Comment by etiennebacher** [comment]
Comes from `easystats_pkgs <- available.packages(repos = "https://easystats.r-universe.dev")`

For some reason, `emmeans` is in `easystats` R-universe: https://easystats.r-universe.dev/builds

![image](https://github.com/easystats/easystats/assets/52219252/05f4ffde-718f-451b-8afd-4a0e75b27822)
