### ISSUE TITLE
Personalize message upon library(easystats)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#37]
![image](https://user-images.githubusercontent.com/8875533/64918149-e3672a00-d7cc-11e9-8ec7-5f62bea6e55b.png)

Would be nice to have something less verbose like "easystats successfuly loaded!" rather than these red messages

**Comment by strengejacke** [comment]
I have revised the startup a bit. In `needed` are those packages that are out of date, which I want to print in a different color. I'm working on the coloring later.

**Comment by strengejacke** [comment]
It's not less verbose, but more informative. And red version number indicates outdated  pkg.

![Unbenannt](https://user-images.githubusercontent.com/26301769/64926323-6eabe400-d7fc-11e9-8a96-0b2373321dfc.png)

**Comment by strengejacke** [comment]
![b1](https://user-images.githubusercontent.com/26301769/64926801-54750480-d802-11e9-8390-1ac2ecba3b4b.png)

![b2](https://user-images.githubusercontent.com/26301769/64926805-576ff500-d802-11e9-9b2b-7b2ff100c2e9.png)

![b3](https://user-images.githubusercontent.com/26301769/64926806-5a6ae580-d802-11e9-8e27-98bb30bc3507.png)

![b4](https://user-images.githubusercontent.com/26301769/64926807-5ccd3f80-d802-11e9-860e-86395f0cfb66.png)

**Comment by DominiqueMakowski** [comment]
Wow, awesome!!! Seems very pro 👌 

questions:
- Is it possible to conditionally display the "red = needs update", i.e., if there is an outdated package, then add something like `Update packages in red with 'easystats_update()'`
- Maybe replace the `*` by ticks (tidyverse uses: `crayon::green(cli::symbol$tick)`)? But needs `cli` AND might look to tidyverserian 😁

**Comment by strengejacke** [comment]
![b1](https://user-images.githubusercontent.com/26301769/64933677-8445fb80-d846-11e9-8aec-ca986360e86f.png)

![b3](https://user-images.githubusercontent.com/26301769/64934201-70e85f80-d849-11e9-82d8-3112c5f2dc45.png)

**Comment by strengejacke** [comment]
in the most recent commit, I also checked if dev-versions are installed, else the function to load all libs would fail.

**Comment by strengejacke** [comment]
And I just copied the unicode for the two symbols, we don't need to import _cli_ here.

**Comment by strengejacke** [comment]
I think we can use the "warning" sign instead of cross, else it would rather look like failed to attach, what is not the case.

**Comment by strengejacke** [comment]
![Zwischenablage-1](https://user-images.githubusercontent.com/26301769/64934436-1cde7a80-d84b-11e9-9411-afff634d1fb1.png)

**Comment by pdwaggoner** [comment]
This looks great guys! Great idea and well executed

**Comment by pdwaggoner** [comment]
However, I got this note when trying...

<img width="506" alt="Screen Shot 2019-09-16 at 8 51 17 AM" src="https://user-images.githubusercontent.com/31326382/64963634-34bff980-d85f-11e9-8880-d5845fca3caf.png">

**Comment by strengejacke** [comment]
easystats is _only_ available from GitHub, and probably ever will. CRAN teams does not want to have packages which solely purpose is to load and check other packages (no idea how tidyverse made it to CRAN, maybe they setup this rule later).

**Comment by pdwaggoner** [comment]
I just looked at the course code and it looks pretty straightforward, with this as the on attach start up message:

```{r}
.onAttach <- function(...) {
  needed <- core[!is_attached(core)]
  if (length(needed) == 0)
    return()

  crayon::num_colors(TRUE)
  tidyverse_attach()

  x <- tidyverse_conflicts()
  msg(tidyverse_conflict_message(x), startup = TRUE)
}

is_attached <- function(x) {
  paste0("package:", x) %in% search()
}
```

Here's how they organized the package: https://cran.r-project.org/web/packages/tidyverse/tidyverse.pdf 

Not sure if this is valuable...

**Comment by DominiqueMakowski** [comment]
CRAN or not CRAN, I am closing this issue as it has been addressed ☺️
