### ISSUE TITLE
De-attach packages before update

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#38]
I am not sure if this is addressable, but update doesn't seem to work after loading:

![image](https://user-images.githubusercontent.com/8875533/65007975-4d511200-d93a-11e9-8499-84e8164b359f.png)

Maybe we can *force* the installation?

**Comment by strengejacke** [comment]
I guess we might do this with `detach()`:
https://stackoverflow.com/questions/6979917/how-to-unload-a-package-without-restarting-r
