### ISSUE TITLE
Use `\donttest` instead of `\dontrun` tag for skipping examples on CRAN machines

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#380]
Because examples using `\dontrun` are not executed by `examples()` in any context, it's hard to detect such examples relying on suggested dependencies and use such deps conditionally. This is not going to create any issues, but it does make such example not-future-proof since if we ever decide to run such examples conditionally, they will fail in the extra "noSuggests" check.

Use `\donttest` instead, which achieves the same purpose but is executed by `examples()`and so we can detect any non-conditional usage of optional deps.

For an example, check how this [commit in `{see}`](https://github.com/easystats/see/commit/f40c7dbe58bf052de8a999190a509e5705e90544) unearthed failures in [noSuggests workflow](https://github.com/easystats/see/actions/runs/6221140897/job/16882539493).

## Progress tracker

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by IndrajeetPatil** [comment]
All usages can be seen in search results here: https://github.com/search?q=org%3Aeasystats+dontrun&type=code

**Comment by etiennebacher** [comment]
From [this section](https://r-pkgs.org/man.html#footnotes) in "R packages" about the use of `\dontrun`:

![image](https://github.com/easystats/easystats/assets/52219252/b2e5e78b-cb99-48d1-9d82-0a400e1768b7)

If we used `\dontrun` because the examples take a long time or provoke a warning/error, using `\donttest` will still run those on CRAN checks. Isn't that a problem?

**Comment by IndrajeetPatil** [comment]
I think this shouldn't be an issue because `R CMD check` still won't execute `donttest` examples. These examples are executed in a special check: https://www.stats.ox.ac.uk/pub/bdr/donttest/, where it won't be checked how long it takes to run the examples.

And, even if that were to be an issue, we can always just set `#' @examplesIf identical(Sys.getenv("NOT_CRAN"), "true")` for such examples and retain `donttest` so that our CI/CD will still run these examples, even if CRAN machines don't.

Does that make sense?

**Comment by etiennebacher** [comment]
Yes this should work I guess

**Comment by bwiernik** [comment]
Agreed. I think the only place where dontrun makes sense is if we wanted to demonstrate "this will produce an error". I don't think that applies to us anywhere

**Comment by IndrajeetPatil** [comment]
Even to show the error, `try()` is preferable since one can also see the expected error message.
