### ISSUE TITLE
Next meta-package CRAN release

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#381]
It has almost been a year since the last CRAN release of the meta-package. It'd be good to do another release to get users on-board with the newest CRAN releases of all component packages.

**Comment by IndrajeetPatil** [comment]
WDYT, @strengejacke?

**Comment by strengejacke** [comment]
Yes, I can submit an update

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by strengejacke** [comment]
I just submitted _performance_, and then would like to submit _parameters_, and _see_ also has some new features. Should we wait for those before submitting _easystats_, so we can bump to the latest versions here?

**Comment by IndrajeetPatil** [comment]
Yes, that sounds reasonable to me.

**Comment by IndrajeetPatil** [comment]
*see* update is on CRAN
