### ISSUE TITLE
Going workflow green

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#384]
@easystats/core-team I have added a [new tab](https://easystats.github.io/dashboard/dashboard.html#workflow-status) to our dashboard to check the status of all workflows which are run for each commit and which should ideally be green (see [this](https://indrajeetpatil.github.io/preventive-r-package-care/#/preventive-care-for-r-packages) if you are wondering why?).

Current state of the board (`2023-09-29 12:40:50 CEST`):

<img width="1424" alt="Screenshot 2023-09-29 at 12 15 20" src="https://github.com/easystats/easystats/assets/11330453/a59926e7-70e4-4d87-b2c1-e28d00db61d5">

_bayestestR_ and _modelbased_ in particular are in dire need of our love and attention. 🥹

**Comment by DominiqueMakowski** [comment]
mmh indeed indeed, I'll take a look in particular at modelbased

(nice tab tho!)

**Comment by IndrajeetPatil** [comment]
I think we have done as much as we can here.
