### ISSUE TITLE
Surprising behaviour of tests on Windows in some specific contexts

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#385]
For meta-package tests, I have tried a lot of things and yet haven't been able to figure these out.

- Tests [fail](https://github.com/easystats/easystats/actions/runs/6351456125/job/17252713373) when run in random test order, even though there is only one test file. 

- Tests run forever while computing code [coverage](https://github.com/easystats/easystats/actions/runs/6351456126/job/17252713696). Indeed, this workflow stops after 6 hours, just because that's the maximum time allotted by GitHub Actions.

These behaviours are observed only on Windows, but not always, e.g. not during the [R CMD check](https://github.com/easystats/easystats/actions/runs/6351456124/job/17252713922). My hunch is that this has to some environment variables which are set for R-CMD-check workflow, but not for code coverage workflow.

**Comment by IndrajeetPatil** [comment]
@easystats/maintainers Any ideas?

**Comment by etiennebacher** [comment]
I can't reproduce the failure for tests in random order but I suspect that the definition of test failure and test error doesn't work when there's only 1 test and that this test is skipped (I don't know why, it's the only thing I can think of). Btw, what's the difference between failure and error for `testthat`?

Removing the `reporter = "silent"` argument would probably give more info on this

**Comment by IndrajeetPatil** [comment]
> Btw, what's the difference between failure and error for _testthat_?

- Failure: Actual value doesn't match with expected value
- Error: Test code itself couldn't be run successfully

So the random test order workflow is now passing. It was failing because Pandoc wasn't installed for this workflow, and _flaxdashboard_ seems to require it.

I still don't understand why code coverage workflow is stuck in infinity.

**Comment by etiennebacher** [comment]
I think `covr` doesn't take into account the `skip_` calls. Locally, I tried to put all kind of `skip_` in the test file. `devtools::test()` correctly skips all of them, but `covr::package_coverage()` stil returns the same percentage as if there were no skips. So maybe it stays stuck forever in one of the interactive tests?

**Comment by IndrajeetPatil** [comment]
Thanks! That was indeed the issue. Skipping these tests during code coverage fixes that workflow. I will investigate which is the offending test and why it gets stuck.
