### ISSUE TITLE
Running tests on 2 cores only

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#389]
I got a note from CRAN submission, Uwe explained:

> But for future submissions:
>   Running R code in 'testthat.R' had CPU time 2.7 times elapsed time
> suggests you are using more than 2 cores, and myou must not use more 
than 2 by default.

@IndrajeetPatil any idea if we can limit tests to using 2 cores only?

**Comment by IndrajeetPatil** [comment]
Which CRAN submission is this? For easystats?

**Comment by strengejacke** [comment]
_performance_

**Comment by strengejacke** [comment]
They accepted the submission, but wanted to note for future submissions. Not sure if this is in general a setting across our easystats packages?

**Comment by IndrajeetPatil** [comment]
I think this is relevant only to `performance::check_outliers()`. Can you please check that we are not running any tests or examples that use more than 2 cores?

**Comment by strengejacke** [comment]
> Can you please check that we are not running any tests or examples that use more than 2 cores?

How do I check this? And why did this note not occur three days ago when I submitted _performance_ 0.10.7?

**Comment by IndrajeetPatil** [comment]
testthat docs say that it will use 2 cores by default:

https://github.com/r-lib/testthat/blob/f060ccec365e1343ae926c53c215a423b295d7a8/vignettes/parallel.Rmd#L29
