### ISSUE TITLE
Consistency of arguments across packages, in particular `by`, `group` and `group_by`.

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#404]
We have

- `insight::export_table(group_by)`
- `datawizard::data_partition(group)`
- `datawizard::data_tabulate(by)`
- `datawizard::means_by_group(group)`
- `report::report_sample(group_by)`

to name a few. I think we should just use one of the three verbs to indicate grouping, to be more consistent across our easystats packages. What would you suggest?

- [x] insight (https://github.com/easystats/insight/pull/872)
- [x] bayestestR
- [x] correlation
- [x] datawizard (https://github.com/easystats/datawizard/pull/502)
- [x] effectsize
- [x] modelbased
- [x] parameters
- [x] performance (https://github.com/easystats/performance/pull/721)
- [x] report
- [ ] see

**Comment by DominiqueMakowski** [comment]
And we sometimes have `at` as well...

I think I like `by`, it's concise + it's also in-line with the recent tidyverse evolution `.by`

**Comment by strengejacke** [comment]
In `parameters::model_parameters()`, should we also rename `keep` and `drop` into `select` and `exclude`? These argument do not select variables, but regression coefficients, but their intention is similar: to select a subset of data. WDYT?

**Comment by DominiqueMakowski** [comment]
I'm not sure, I have the feeling that there should be distinct arguments for columns and for rows

**Comment by strengejacke** [comment]
ok, makes sense. Better for me, so I don't need to touch this ;-)

**Comment by strengejacke** [comment]
What about `bayestestR::estimate_density()`? There's also an `at` argument.

**Comment by bwiernik** [comment]
> What about `bayestestR::estimate_density()`? There's also an `at` argument.

Probably worth changing this one

**Comment by strengejacke** [comment]
@DominiqueMakowski and then for _modelbased_, we rename all `at`s into `by`s, too, right?

**Comment by DominiqueMakowski** [comment]
Yes

**Comment by strengejacke** [comment]
What about `visualization_matrix()`? 🙈

**Comment by strengejacke** [comment]
Ah, that's only in _modelbased_. I confused it with `visualization_recipe()`.
