### ISSUE TITLE
Use `{pak}` for downloading suggested dependencies?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#413]
When it comes to package installation, IMO, `{pak}` is a game-changer because of its intuitive UI, beginner-friendly UX, and performance. 

We could rewrite our helper to install suggested easystats dependencies to utilize it:

```r
install_suggested <- function(package = "easystats") {
  insight::check_if_installed("pak")
  if (package == "easystats") {
    package <- easystats:::.packages_on_cran()
  } 
  pak::pkg_install(package, dependencies = TRUE)
}
```

This way, we also don't need to invest too much effort into figuring out the dependency graphs ourselves; `{pak}` will take care of it and will fail gracefully and with informative error message.

**Comment by strengejacke** [comment]
> This way, we also don't need to invest too much effort into figuring out the dependency graphs ourselves

I don't think we have too much effort, in particular, since we need to figure out the dependencies for `show_suggested()` anyway. The question is if the benefit from using `pak` outweighs the installation of several additional packages? It produces a lot of output that is either redundant or doesn't provide more useful information to casual users than the base `install.packages()`.

**Comment by IndrajeetPatil** [comment]
>  The question is if the benefit from using pak outweighs the installation of several additional packages?

What other packages? `{pak}` has 0 additional, non-default deps.

> a lot of output that is either redundant or doesn't provide more useful information

I disagree: it gives a lot of useful information, like the size of packages, if a cached copy is being used or a new copy is being downloaded, etc.

On Unix-like OS, it informs about which system-level dependencies are required and are missing.
On Windows, it gracefully solves the "locked DLL" problem. 
And much more.

Have you used this package?

**Comment by strengejacke** [comment]
> I disagree: it gives a lot of useful information, like the size of packages, if a cached copy is being used or a new copy is being downloaded, etc.

My argument was it doesn't provide much useful information for *casual R users*, or: the target-group we have in mind when designing the easystats-packages. If you regularly teach R introductions, you'll see what is confusing to R users (and therefore redundant), and what is missing. If users want to install packages, the only thing they want to see is "all packages installed", and not more.

I haven't tested the package without having installed all the suggested packages, but I bet that the output would look rather different if you haven't installed the other dependencies as well.

**Comment by strengejacke** [comment]
> On Windows, it gracefully solves the "locked DLL" problem.

If we can have that feature *without* the redundant console output, that would be a game changer indeed.

**Comment by bwiernik** [comment]
You can always sink() the console output if you want to avoid it and there's not another silent option
