### ISSUE TITLE
New member: Jonas

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#42]
It is my pleasure to welcome the king of the [*reductio ad lineari modelum*](https://lindeloev.github.io/tests-as-linear/), the twitter [dinosaur](https://twitter.com/jonaslindeloev), the great @lindeloev to easystats 🎉

Here we are, in what is probably the best open, collaborative and fun project and community since Human evolution itself. It's centred (at least for now) around building tools surrounding statistical models, with a focus on user experience; carefully considering functions' design, names, argument names etc. to maximize clarity, intuitiveness, and accessibility. Our target audiences are both beginners (to which we provide a way of easily obtaining complex and relevant information) and experts, that can use our specialized packages and incorporate them in their work. In sum, *make R stats fun again!* 😁 

As for what is expected of members? Nothing! But feel free to comment, give suggestions in issues or such whenever you feel comfortable enough. You might see us ping specific people from time to time, but we encourage everyone to give their opinion and thoughts even if not directly pinged (or just reacting with a 👍 or a 😠)

I'd recommend to "watch" (follow) all the [11 easystats](https://github.com/easystats) repos, to stay tuned to what's going on, as we usually work in parallel :)

As for a "roadmap context", We are currently working at stabilizing the current packages that are on CRAN, as well as aiming to release estimate and correlation soon, to then be able to finally ship the last piece of the current puzzle, report. Feel free to share any thoughts, ideas, suggestions or fun facts.

 Glad to have you onboard ☺️ 

@pdwaggoner @mattansb @IndrajeetPatil @humanfactors @jacob-long

**Comment by strengejacke** [comment]
Welcome, and great to have you on board!

**Comment by mattansb** [comment]
> *reductio ad lineari modelum*

Brilliant!

Welcome @lindeloev !

**Comment by pdwaggoner** [comment]
Welcome @lindeloev !

**Comment by IndrajeetPatil** [comment]
Welcome, @lindeloev!! Glad to have your expertise on board.

**Comment by humanfactors** [comment]
Welcome! Looking forward to working with you :)

**Comment by lindeloev** [comment]
Wow, thank you, everyone! I accept my new title without hesitation, @DominiqueMakowski!

This is a great project and I look forward to collaborating. Here's a great quote from Whitehead (1911) why projects like this matter:

> Civilization advances by extending the number of important operations which we can perform without thinking about them.

**Comment by jacob-long** [comment]
Welcome @lindeloev! Loved your "common statistical tests are linear models" and I've been looking forward to using it in my teaching.

**Comment by lindeloev** [comment]
Thank you @jacob-long, let me know if you can think of any improvements.

Closing this issue now since I'm already a three days old member - the "new" has been fixed ;-)
