### ISSUE TITLE
Get `{circus}` on CRAN and start using lazy-loaded datasets?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#420]
In the current approach, we need to make expensive HTTP calls to download a model and use them in examples, vignettes, and testing. (We also don’t do it smartly, e.g. caching downloaded models, but that's not the biggest of worries.) More importantly, this makes our tests and docs dependent on internet access availability. It also means that the users can’t employ the familiar way of loading datasets, which are typically shipped in a data package and lazy-loaded. 

I understand why we wanted to do this when the ecosystem was changing fast, and we wanted to be flexible to rapidly add or update needed models, instead of having to update the CRAN package every single time. But now that the ecosystem is more stable and we aren’t modifying circus too frequently, I think we could get this package on CRAN and start using it.

What do you think?

**Comment by IndrajeetPatil** [comment]
cc @easystats/core-team

**Comment by etiennebacher** [comment]
Isn't `circus` too big to be on CRAN? I don't know other packages that are data-only.

> It also means that the users can’t employ the familiar way of loading datasets, which are typically shipped in a data package and lazy-loaded.

I thought those were for testing purposes only and so shouldn't be made available to the users?

**Comment by strengejacke** [comment]
I think _circus _ doesn't contain any data sets, only compiled (Stan) models, to reduce the time needed to run tests.

**Comment by strengejacke** [comment]
> Isn't circus too big to be on CRAN? I don't know other packages that are data-only.

I though that, too, but... the current setting just seems to be to build the docs:

![image](https://github.com/easystats/easystats/assets/26301769/cb690870-b0e1-4a15-b69f-b45c3671a289)

**Comment by etiennebacher** [comment]
> I think circus doesn't contain any data sets, only compiled (Stan) models, to reduce the time needed to run tests.

Then I understand even less the need to put this on CRAN, it's clearly for internal use only. Also this would remove the need for connection in tests but we'd still need internet to install the package anyway in each CI workflow, right?

**Comment by strengejacke** [comment]
Correction, we indeed have a few data sets (e.g. SPSS), to test `data_read()` for example (these data sets are small, we _could_ move them to _datawizard_ if needed). But in 99% of all cases, we use it for pre-compiled models.

**Comment by strengejacke** [comment]
Including all "data" *slightly* increases the package size:

![image](https://github.com/easystats/easystats/assets/26301769/ad1d1b52-5879-4914-850c-074925c8adc2)

**Comment by etiennebacher** [comment]
Wait, is this 170MB or 170KB?

**Comment by strengejacke** [comment]
MB

**Comment by etiennebacher** [comment]
Yeah ok so even if we wanted to put that on CRAN, I know some packages negotiate with them when > 5MB but that seems a little bit too much

**Comment by strengejacke** [comment]
The data folder is uncompressed 189 mega bytes. Since there are only a few larger CSV files, compression doesn't save much.

**Comment by strengejacke** [comment]
Yes, I don't think we can/should put this on CRAN given the very large file size.

**Comment by IndrajeetPatil** [comment]
Okay, 170 MB concludes this whole line of thought 😅 

@etiennebacher Yes, this package is not end-user-facing, but since our documentation does refer to `download_model()` in a few places, I thought it would be nice to reduce one level of indirection.
