### ISSUE TITLE
Money? 💰

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#43]
I'm just putting this there, but it would be super cool to have some money to 1) organize some kind of workshop to gather ourselves and spread the news and 2) to be able to decently pay some intern or student to contribute (there are many areas that could be easily improved in the context of a training, such as documentation, testing etc.) and 3) get filthy rich of course

If you hear of any grant call to which we could apply do let it know ☺️

**Comment by IndrajeetPatil** [comment]
This looks like an excellent opportunity:

https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/

**Comment by DominiqueMakowski** [comment]
> We encourage proposals supporting multiple open source software projects.

Indeed!

>  The EOSS-4 application process is a two-step process: Letter of Intent (LOI) and Full Application (if invited).

> Award period and start date: Awards will be for **two years** (24 months) in duration with a start date of no earlier than September 1, 2021.

March 30; deadline for letter of intent:

> The application (Letter of Intent) consists of the following sections (called tasks in the grants portal): Applicant Details, Equal Opportunity & Diversity, Organization Details, Proposal Details.

> Amount Requested: Enter total budget amount requested in USD, including indirect costs; this number should be between **$100k and $400k** total costs over a two-year period

It could be used to fund a fulltime positions, like a postdoc (or two)

**Comment by DominiqueMakowski** [comment]
@strengejacke @mattansb

**Comment by mattansb** [comment]
Looks really interesting!
They're looking for bio-related stuff, do we count?
(post docs all the way! 🤑)

**Comment by DominiqueMakowski** [comment]
## Letter of Intent (March 30)

- [ ] Decide on who's the main applicant (does it have any impact?)
- [ ] Write **letter of intent**
  - [ ] Proposal title (max. of 75 characters)
  - [ ] Proposal Purpose: One sentence (max. 255 characters)
  - [ ] Amount Requested
  - [ ] Proposal Summary/Scope of Work: A short summary of the application ​(max. 500 words)
  - [ ] Landscape Analysis (max. 250 words)
  - [ ] Open Source Software Projects: List max. 5 software with short description (max. 100 words) for each

**Comment by IndrajeetPatil** [comment]
I will be happy to be the main applicant if you guys don't mind. I can definitely take up a postdoc to work with me. 

Should we set up a Google doc or something to work on the document collaboratively, or should we do it on GitHub itself? 
I am fine by either of those options.

**Comment by mattansb** [comment]
I wouldn't mind being that post doc 😂

> Should we set up a Google doc

Sounds good.

**Comment by IndrajeetPatil** [comment]
Oh? Would you like to be the main applicant then? Fine by me.

**Comment by strengejacke** [comment]
We have to think about the topic of the proposal. They focus on biomedical research, and our packages do not fit into this narrow scope. We may provide tools where biomedical research also benefits from, but our ecosystem is not explicitly dedicated to that field.

One thing that comes to my mind is that people in biometrics still often use SPSS/Stata, and that the ease of transition to R is rather hard - and this is what easystats aims at. Another point could be to focus on specific methods, and here I mainly see bayestestR as a potential package that could be useful. But I have no good overview of the current state of Bayesian methods in biomedical research.

I personally doubt that our chances are good.

**Comment by strengejacke** [comment]
>  Decide on who's the main applicant (does it have any impact?)

Personally, for the CV. Else, I think the applicant should be located at a University, and maybe at least be a post-doc?

**Comment by mattansb** [comment]
> Oh? Would you like to be the main applicant then? Fine by me.

Must be still my fever talking.... :P

**Comment by DominiqueMakowski** [comment]
I think we might have a stronger application if the main applicant has something close to a permanent position (which would be Daniel?), of course then it's a matter of CV stuff but in regards to that I don't think it matters a lot: in the end probably the four of us can be listed as PIs since we are responsible for the project (it explicitly states that the sole purpose of having a main applicant is for contact; given the "open source / collaborative" friendliness of the grant it makes sense). Then if we recruit someone I don't know how it works; do they have to move to somewhere? How are the wages computed etc. etc. but that's details that are irrelevant for the first milestone (the letter by the end of the month)

**Comment by bwiernik** [comment]
A couple of things to think about with grants:

1. Any time you officially subcontract to another institution, they take another cut of indirect costs, so this would really need to be a single institution grant for this size.
2. So, folks outside the institution would need to be hired as contractors or consultants, rather than as students, postdocs, or co-PIs
