### ISSUE TITLE
easystats package

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#45]
Currently, to make automatic updates work in the easystats package, we don't import the packages. However, this causes troubles for people who have not already installed all easystats packages (including GitHub only packages) _before_ running the easystats package. This is probably the situation for most users.

I would suggest it's more useful to import packages and only to say which packages are out of date and should be updated manually after restarting the R session?

**Comment by DominiqueMakowski** [comment]
I agree, I encountered some issues too on the easystats installation part in a recent lab R workshop

**Comment by strengejacke** [comment]
I can't install the package right now, because _estimate_ relies on function in _parameters_ that obviously have been removed.

**Comment by DominiqueMakowski** [comment]
the Dev branch is your ally

**Comment by strengejacke** [comment]
I thought the Dev branch is to have stable master branches. When I commit to master, it works :-P

**Comment by strengejacke** [comment]
I updated the _easystats_ package, so it checks all CRAN check pages of our packages and warns if there are warnings or errors in the checks, so we're quickly aware of it. As currently all packages are OK, I'll post a screenshot from my _strengejacke_ package:

![image](https://user-images.githubusercontent.com/26301769/71681264-7fbd3880-2d8c-11ea-8905-fb57c72d9cf5.png)

![image](https://user-images.githubusercontent.com/26301769/71681297-91064500-2d8c-11ea-9999-ec7ffa948477.png)

**Comment by DominiqueMakowski** [comment]
Didn't even know it could do that

**Comment by strengejacke** [comment]
![image](https://user-images.githubusercontent.com/26301769/72542260-207b2000-3884-11ea-8d11-52183d216e4a.png)
