### ISSUE TITLE
Code Conventions and Versioning

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#5]
# Convention of code-style

Following conventions apply to the easystats-ecosystem, to ensure that function and argument names as well as element names for return-values follow a consistent pattern across all packages.

**Importing other packages**

- No full import, only selective import of functions
- Use base-R wherever possible (reduce dependencies)
- Make sure R-version requirements are not too strict

**Helper-functions**

- Own re-implementation of helper-functions, if it's not too much effort (e.g. I typically use own functions to check if a string starts / ends with a pattern, or if an object (list, data frame) contains an element with a given name (like `tibble::has_name()`), to reduce dependencies.

**Function names**

- Lower case, underscore separated if more than one verb
- Common prefix for functions that focus on specific "tasks" or workflows (e.g. **insight**, `get_*()` to get data, `find_*()` to find information, or **performance**, `performance_*()` to compute measures of model quality, `check_*()` to check model assumptions...)
- Internal functions (that are not exported, like the previously mentined helper-functions) should always start with a `.` (e.g., `.do_some_internal_stuff()`).

**Argument names**

- lower case, underscore separated if more than one verb

**Element / Column names** (for returned data frames)

1) First letter of the column name is capital, unless (6) applies (_example:_ `Parameter`)
2) First letter of nouns is capital, unless (6) applies (_example:_ `ROPE_Percentage`, `Prior_Scale`)
3) Using underscore rather than camelCase to separate words (_example:_ `CI_high`)
4) Multiple words: common/main part first and adjective/specifier/variational part after (_example:_ `Median_standardized`, `ROPE_percentage`)
5) Abbreviations: all uppercase (_example:_ `ESS`, `MCSE`, `ROPE`)
6) Keep conventions for reserved words (_example:_ `p`, `pd`, `Rhat`)
7) Adjectives / verbs: all lower case, unless (1) applies (_example:_ `high` or `low` in `CI_high` or `CI_low`)

**Comment by strengejacke** [comment]
**Importing other packages**

- No full import, only selective import of functions
- Use base-R wherever possible

**Helper-functions**

- Own re-implementation of helper-functions, if it's not too much effort (e.g. I typically use own functions to check if a string starts / ends with a pattern, or if an object (list, data frame) contains an element with a given name (like `tibble::has_name()`).

**Function names**
- lower case, underscore separated if more than one verb?

**Argument names**
- lower case, underscore separated if more than one verb?
- lower case, dot separated if more than one verb?

**Comment by DominiqueMakowski** [comment]
I would opt for the underscore separation both for functions and arguments... Also working with other langs such as python or julia, this dot separator thing in R always felt a bit weird to me :)

For the rest, sounds perfect!

**Comment by strengejacke** [comment]
What about versioning? I almost never use different branches and have not much experience with this. I think this is something I should start learning and applying for the projects / packages we plan. Or should we work with pull requests, or both? What is better in which situation?

**Comment by DominiqueMakowski** [comment]
I had many tentatives working with branches, more or less successful ^^, including a feature-based workflow and a dev-branch workflow, and had better results with the second. Basically, the idea would be to have a maste, and a dev branch to which we upload our commits (the dev is our working branch), and from time to time we merge dev into master, updating the version number

**Comment by strengejacke** [comment]
Ok, let's try it with dev-branches.

**Comment by strengejacke** [comment]
I updated accoding to https://github.com/easystats/parameters/issues/44
