### ISSUE TITLE
CRAN task views

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#50]
Two of our packages that are on CRAN are already in task views (effectsize, parameters). We may think of recommending "bayestestR" for the Bayes task view as well?

**Comment by DominiqueMakowski** [comment]
That's great!!

We should definitely suggest bayestestR. If I understand, we'd have to email the maintainer of the Bayes list (https://cran.r-project.org/web/views/Bayesian.html). Do you think we should send something like "Hey, we'd like to bring your attention to the bayestestR package which you might find relevant for the Bayes task view"? Sounds a bit self-promoting but guess we gotta do what we gotta do 😁

**Comment by mattansb** [comment]
Hey, `bayestestR` maintainer, how this going? :P

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/l1J9ONVbGklf6UN0Y/giphy.gif)

**Comment by strengejacke** [comment]
_bump_ 😬

**Comment by mattansb** [comment]
*bump* 😬

**Comment by strengejacke** [comment]
bayestestR is in the task views now.

**Comment by IndrajeetPatil** [comment]
`effectsize` is also in view for Meta Analysis 😄
