### ISSUE TITLE
library(easystats) fails without internet?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#51]
right now I tried loading easystats without internet, and had this error:

```r
> library(easystats)
Warning: unable to access index for repository https://cran.r-project.org/src/contrib:
  cannot open URL 'https://cran.r-project.org/src/contrib/PACKAGES'
Error: package or namespace load failed for ‘easystats’:
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: `[.data.frame`(easystats_versions, , c("package", "local"))
  error: undefined columns selected
```
Can someone confirm?

**Comment by strengejacke** [comment]
Yes, I think `utils::available.packages()` is the reason - it downloads a list of current CRAN packages, to do the update-checks. Maybe we can surround with `tryCatch()`?

**Comment by strengejacke** [comment]
I just realized that it _should_ work already... Have you updated the latest easystats-package from GitHub?

**Comment by strengejacke** [comment]
Yes, just checked. It also works when you'r offline.
