### ISSUE TITLE
website templates

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#54]
Any idea why code blocks in the [paramters-website](https://easystats.github.io/parameters/) have a dark background, while for [performance](https://easystats.github.io/performance/) these are light? Though they both have defined the same css-template in the yaml-file? Or is it not related to the yaml?

**Comment by DominiqueMakowski** [comment]
Because performance doesn't have [this file](https://github.com/easystats/parameters/blob/master/pkgdown/extra.css)

**Comment by strengejacke** [comment]
ah, got it!
