### ISSUE TITLE
Error while installing easystats

### ISSUE THREAD

**Issue by atnplab** [easystats/easystats#55]
I have this error message

Errore: Failed to install 'easystats' from GitHub:
  Failed to install 'insight' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/prettyunits/R/prettyunits.rdb' is corrupt
Inoltre: Warning message:
In paste0(" (", pretty_dt(elapsed), ")") :
  internal error -3 in R_decompress1

I used devtools as you suggest here.
How can I solve this?

Thanks

**Comment by strengejacke** [comment]
This looks to me as if the package _prettyunits_ is broken. Try to remove and reinstall, does that help?

**Comment by atnplab** [comment]
Yes thanks, this fixed the problem
