### ISSUE TITLE
New member: Leo

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#57]
There was a time when I did not, even in my wildest dreams, think of becoming someday fluent in programming. A long and forgotten time in which people didn't said "what a nerd" 🤓 

But then @LeoDutriaux (https://twitter.com/LDtrx) came and he initiated me to python, and by doing so changed my life. So it is now my very pleasure to welcome my former PhD buddy to easystats, in which he is looking to improve his R skillz (as he was more a pythonista 'til now 😁). 

Welcome to our community 🎉 , a place for us to learn and eventually sometimes contribute to the community. 

As for what is expected of members? Nothing, we all have busy schedules (and a life), so it's normal not to be super active. But feel free to comment, give suggestions in issues, retweet easystats tweets and such whenever you feel comfortable enough. You might see us ping specific people from time to time, but we encourage everyone to give their opinion and thoughts even if not directly pinged (or just reacting with a 👍 or a 😠)

I'd recommend to "watch" (follow) all the 11 [easystats repos](https://github.com/easystats), to stay tuned to what's going on, as we usually work in parallel :)

We have a "pyramidal" organization with low-level packages, such as "insight" (named "low-level" because they do not depend on anything than themselves to work), which are cornerstones for other mid-level packages (such as parameters and performance), which themselves are used by high-level packages (e.g., report) that uses the power and synergy of the whole ecosystem to achieve their purpose. Some packages are also focused on specific features/aspects/data analysis type (e.g., bayestestR, correlation, ...). This is the way it is as for now, but who knows what the future has in store for easystats!

Speaking of future, for a "roadmap context", the priority is for now to push the 2 currently remaining easystats to CRAN, namely *correlation* and *report*. The former is pretty ready and awaits the complementation of a new CRAN updates cycle from the others, and *report* is in a major state of re-doing (see the dev PR). Aside from that, there is plenty of things left to be done, such as improving documentation, testing, blogging, etc. etc. 

Feel free to share any questions thoughts, ideas, suggestions or fun facts!

@strengejacke @pdwaggoner @mattansb @IndrajeetPatil @humanfactors @jacob-long @lindeloev

**Comment by LeoDutriaux** [comment]
Hello everybody!
Glad to become part of this adventure!!

**Comment by humanfactors** [comment]
Welcome to the team! Look forward to working with you <sup>(in the paraphrased words of Dom)</sup> _to make stats easy again_.
