### ISSUE TITLE
Missing functions psycho package

### ISSUE THREAD

**Issue by goesjon** [easystats/easystats#58]
Hello everybody,

I do not find the functions "analyze" and "get_contrasts" of the "psycho" package anymore. My code looks like the following (taken from this tutorial: https://www.r-bloggers.com/how-to-do-repeated-measures-anovas-in-r/):

> library(psycho)
Note: Many functions of the 'psycho' package have been (improved and) moved to other packages of the new 'easystats' collection (https://github.com/easystats). If you don't find where a function is gone, please open an issue at: https://github.com/easystats/easystats/issues
[by the way: that is why I opened this issue here]

> library(tidyverse)
> summary(df)
> library(lmerTest)
> fit <- lmer(Subjective_Valence ~ Emotion_Condition + (1|Participant_ID), data=df)
> anova(fit)

> results <- analyze(fit)
Error in analyze(fit) : could not find function "analyze"

> results <- get_contrasts(fit, "Emotion_Condition")
Error in get_contrasts(fit, "Emotion_Condition") : 
  could not find function "get_contrasts"

How can I use these functions again? Are there any functions replacing the missing functions? Why do functions suddenly disappear? 

Help would be very much appreciated. 

Thank you very much. 

Best regards

Jonathan

**Comment by strengejacke** [comment]
@DominiqueMakowski I think you're most likely the only one who can answer this...

**Comment by DominiqueMakowski** [comment]
@goesjon thanks for asking ☺️ 

- While `analyze()` is to be implemented in the [report](https://github.com/easystats/report) package, it is not entirely there yet. Hopefully, that package will be fixed and ready in the next few days (see [progress](https://github.com/easystats/report/pull/50))
- `get_means()` and `get_contrasts()` have been moved to a dedicated package, [modelbased](https://github.com/easystats/modelbased). See [here for the contrasts](https://easystats.github.io/modelbased/articles/estimate_contrasts.html)
- If that doesn't do the trick, here (https://github.com/neuropsychology/psycho.R/issues/115) are some workarounds to get the older psycho version.

Let me know how if you have any issues.

**Comment by goesjon** [comment]
Hello @DominiqueMakowski 

thank you very much for the quick response. 

The function "estimate_contrasts()" of the "modelbased" package works great (instead of "get_contrasts()" function of the "psycho" package). I am not able to try the "analyze()" function of the "report" package yet, since I have troubles installing the "report" package: 

Error: Failed to install 'report' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’
[another try]
Error: Failed to install 'report' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘vctrs’

I report here as soon as I have news regarding the installation of the "report" package. 

Thank you very much for your help! 

Best regards

Jonathan

**Comment by DominiqueMakowski** [comment]
@goesjon The report package should be back to being useable hopefully soon (it is broken now indeed). I'll let you know, and in the meantime, do check out [these alternatives](https://github.com/neuropsychology/psycho.R/issues/115)

**Comment by goesjon** [comment]
Hello,

you can install the "report" package as follows (see also https://github.com/easystats/report):

install.packages("devtools")
devtools::install_github("easystats/report")

The function "report()" works great instead of the function "analyze()".  

Thank you very much for your help. Issue closed.
