### ISSUE TITLE
Popularisation, Promotion and Dissemination 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#6]
Related to #4, but for future reference; once we'll have something valuable, we could also think about the different modes of dissemination. We both have blogs connected to R-bloggers, so that's a start. Maybe we could create, in the future, a "collaborative" blog for easystats. Hopefully, if the project takes off, we might have something interesting to publish 😁

**Comment by strengejacke** [comment]
Yes, sounds good! We may post "appetizers" once we have one or two packages in a well developed state, but not on CRAN, and then once packages hit CRAN, we can regularly blog about them...

**Comment by strengejacke** [comment]
Do you have experiences with rmarkdown templates and creating presentations with rmarkdown? I use rmd only sometime for automated reports, but maybe it makes sense to have a template for some presentations that relate to easystats?

**Comment by DominiqueMakowski** [comment]
Mmh I use a lot of rmarkdown for automated reports (and all the supplementary materials of my papers), but never used it for presentations... Might be a good time to try out. This way, some of the content could also be re-used for the README page and such.

I'll try to look into the "presentations with rmarkdown" in the next few days. However, I believe a very few slides stating the goal, the "philosophy"/vision, the future packages/directions and some features demonstration (if we have) should be good enough :) This will be the occasion for us to formulate and clarify our ideas so it can only do good.

**Comment by strengejacke** [comment]
Could _insight_ be a package that is suitbale for publication in JOSS (https://joss.theoj.org/)? We have an elaborated test-suite, functions are well documented, aim of the package is quite clear. Would this be enough (scope of package) for publication? Or isn't it worth the effor?

**Comment by DominiqueMakowski** [comment]
Guess it could be! In the end, I guess I would be thrilled to see a general publication of easystats and how it contributes to good practices accessibility in general, possibly in a more traditional journal. However, I don't think that this end-goal prevents the standalone publications of its components, especially in JOSS, so sure!

What do you think about trying the ropensci path (i.e., validation by [ropensci](https://ropensci.org/) which can be automatically associated with a JOSS publication)? They seem to be a bit more cherry picky regarding the scope and the role of the package in the ecosystem, but I guess it could be worth a try?

**Comment by strengejacke** [comment]
I don't know very much about ropensci, so I can't say what this exactly means for us. In the end, it would be nice to have something citable from a journal that at least has an ISSN. But I think this is more important for mid- or high-level packages. Citing _insight_ will maybe not often occur, if it's a low-lvl package that is imported in other packages rather than directly used by end-users. But it's a more visible reference having a publication associated with the package, that's why I was thinking about it. We can try ropensci as well.

**Comment by DominiqueMakowski** [comment]
Totally agree. Since ropensci might require a bit more work (and complaint about the broken travis), I think it makes sense from what you said to go directly to JOSS.
