### ISSUE TITLE
update citations for packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#61]
This is relevant when there is not a _JOSS_ paper:
A number of packages have gained new authors but that is not reflected in the citation files and README information.

**Comment by strengejacke** [comment]
We could / should think about citation and listed authors and contributors. I think it's a different role being a "contributor" (and listed in the DESCRIPTION and thus on CRAN), or an "author" (and thus being one of the authors in the citation of a package). But you're right, we mostly updated the DESCRIPTION files, but didn't look at the citation files.

**Comment by IndrajeetPatil** [comment]
Are there any plans to update the _JOSS_ paper for `insight`?

**Comment by strengejacke** [comment]
Update in how far? There have been no changes to the insight paper...

**Comment by IndrajeetPatil** [comment]
Got it. 

I meant updating it to highlight some new functionality added to the package since its initial release. But it is not substantial enough, I can understand that it might not make sense to update the paper.

**Comment by strengejacke** [comment]
Ah, ok, I understand. Well, there have been some new additions, but I'm not sure if it makes sense to update the JOSS paper, in a way of having a version 2 of it. Is it common to update papers along with the associated software?

**Comment by IndrajeetPatil** [comment]
Hmm, apparently _JOSS_ doesn't recommend doing this:
https://github.com/openjournals/joss/issues/423#issuecomment-402332608

So, nope, no revision to this paper 😿

**Comment by IndrajeetPatil** [comment]
We need to add `parameters` paper here:
https://github.com/easystats/easystats/tree/master/publications

**Comment by IndrajeetPatil** [comment]
I think I've updated `CITATION` files everywhere and also updated `README` to print them for ease of use.
