### ISSUE TITLE
sticking to 80 character margin 

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#62]
Changing all packages to stick to such a limit will take a lot of time. But, at least in the future, it will be nice if we can stick to the 80-100 character margin. This will make it easy to read the documentation and also work with code (indeed `goodpractices` package flags anything over 80 as a lint, although we don't have to follow that strict of a limit). 

This is a real pain in the neck when I am working on a smaller laptop and need to keep scrolling to the right because the documentation is not restricted to this 80-character limit.

![margin](https://user-images.githubusercontent.com/11330453/76105344-14ceee80-5fd5-11ea-9c61-97eded2e5266.png)

**Comment by strengejacke** [comment]
I think @DominiqueMakowski is a fan of "one liner paragraphs", I believe he has turned on soft-wrapping or so. But I personally try to wrap at ~ 80 chars, and have that margin visible in RStudio - tho I'm not 100% consistent here.

**Comment by strengejacke** [comment]
@DominiqueMakowski please confirm you're obeying to this rule now, so we can close this issue.

**Comment by DominiqueMakowski** [comment]
activates auto-wrap:
![](https://media.giphy.com/media/1zRd5ZNo0s6kLPifL1/giphy.gif)

**Comment by DominiqueMakowski** [comment]
okay I can try but I still hate it this convention and look for its future demise 😈 

altho note than in Python new recommendations suggest 100 char instead of 80, because you know Daniel that most people nowadays use flat screens that have a wide ratio, so 100 char usually fits

**Comment by strengejacke** [comment]
Blame @IndrajeetPatil for this issue ;-)

**Comment by IndrajeetPatil** [comment]
Haha, I think 100 is also fine ;)

**Comment by IndrajeetPatil** [comment]
By the way, for the existing `NEWS.md` files, where this rule is never followed. You can just install https://github.com/lorenzwalthert/stylermd and run `tidy_file` on the entire file and it will clean it up nicely.
