### ISSUE TITLE
Next CRAN release cycle

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#63]
_insight_ and _see_ were updated on CRAN the past days. Next package will be _sjPlot_ next week, followed by _parameters_ (by the end of next week / week after next).

Maybe then _performance_, but this is not really urgent. However, I'd like to use the latest _parameters_ for a mixed models lecture I'm giving by the end of March.

**Comment by DominiqueMakowski** [comment]
*correlation* probably this week, just needs some [edits](https://github.com/easystats/correlation/pull/40#issuecomment-594988616) (will try to look at it asap)

**Comment by strengejacke** [comment]
Yeah, that'd be nice to have our next package on CRAN.

**Comment by strengejacke** [comment]
sjPlot and parameters are on CRAN now.
