### ISSUE TITLE
printing methods should return original input

### ISSUE THREAD

**Issue by mattansb** [easystats/easystats#65]
- [x] insight
- [x] bayestestR
- [x] parameters
- [x] performance
- [x] effectsize
- [x] modelbased
- [x] correlation
- [x] see

----

I think I've brought this up before, but I think it's a good practice to have `print` methods return the original object:

```R
print.bar <- function(x, ...){
  orig_x <- x
  
  {...} # manipulate x however you need to and print it
  
  invisible(orig_x)
}
```

Right now:
``` r
corr_sum <- summary(correlation::correlation(iris))
p_corr_sum <- print(corr_sum)
#> Parameter    | Petal.Width | Petal.Length | Sepal.Width
#> -------------------------------------------------------
#> Sepal.Length |     0.82*** |      0.87*** |       -0.12
#> Sepal.Width  |    -0.37*** |     -0.43*** |            
#> Petal.Length |     0.96*** |              |


all.equal(corr_sum,p_corr_sum)
#> [1] "Component \"Petal.Width\": Modes: numeric, character"               
#> [2] "Component \"Petal.Width\": target is numeric, current is character" 
#> [3] "Component \"Petal.Length\": Modes: numeric, character"              
#> [4] "Component \"Petal.Length\": target is numeric, current is character"
#> [5] "Component \"Sepal.Width\": Modes: numeric, character"               
#> [6] "Component \"Sepal.Width\": target is numeric, current is character"



model <- lm(mpg ~ wt + cyl, data = mtcars)
mp <- parameters::model_parameters(model)

p_mp <- print(mp)
#> Parameter   | Coefficient |   SE |         95% CI |     t | df |      p
#> -----------------------------------------------------------------------
#> (Intercept) |       39.69 | 1.71 | [36.18, 43.19] | 23.14 | 29 | < .001
#> wt          |       -3.19 | 0.76 | [-4.74, -1.64] | -4.22 | 29 | < .001
#> cyl         |       -1.51 | 0.41 | [-2.36, -0.66] | -3.64 | 29 | 0.001
p_mp
#> NULL
```

etc...

**Comment by DominiqueMakowski** [comment]
Altough if you try to catch the output of a printing function, I'd expect almost a string like output (or a dataframe for tables with strings so that it corresponds exactly to what the printing outputs). 

I.e., rather than returning the original object (which I don't see the usecase, because if it's to be used in a chain, one can always print and skip using `%T>%`), I'd return the printed dataframe (i.e., a formatted one)?

**Comment by mattansb** [comment]
I agree. At the very least, these two should give the same result:

```R
print(x)
print(print(x))
```

But this does seem to be the common practice

```R
View(tibble:::print.tbl)

View(stats:::print.htest)

View(emmeans:::print.summary_emm)
```

(Do you actually use `%T>%`? 🤨)

**Comment by DominiqueMakowski** [comment]
> (Do you actually use %T>%? 🤨)

I do I do, although I have to google it for 2min EVERYTIME I want to use it cause I can never remember that it's a T 😅

**Comment by DominiqueMakowski** [comment]
Following what @profandyfield mentioned, we could indeed return the output of `parameters_table()` in the print functions, as it'd be a rather expected behaviour and a very useful feature (I've been using `parameters_table()` a lot when working with Rmds, but bypassing it for something like `kable(print(results))`  would definitely increase the clarity).

**Comment by strengejacke** [comment]
Not sure, `parameters_table()` returns a data frame, there's no own `print()` method, where we could capture / return anything?

**Comment by DominiqueMakowski** [comment]
But most of the print methods use `parameters_table()`, so they could invisibly return its output?

**Comment by strengejacke** [comment]
The output is the data frame, there is no print method.

**Comment by strengejacke** [comment]
Or did you mean the other print methods? I'm still not sure what should be returned in which print method...

**Comment by mattansb** [comment]
I think it would be easier to have `print` return the original input, rather than try and figure out what the output of different methods of different objects should be...

I'm gonna start on bayestestR and effect size.

**Comment by mattansb** [comment]
Sometimes `print`s are in their own separate file, sometimes together with the function that makes the object... Why is life so hard???

**Comment by strengejacke** [comment]
I think I prefer a methods-file, while @DominiqueMakowski prefers keeping functions and methods together in one file.

**Comment by mattansb** [comment]
Alright I think that's it.
Should I add this to the [Convention of code-style](https://github.com/easystats/easystats#convention-of-code-style)?

**Comment by strengejacke** [comment]
yes, why not?

**Comment by DominiqueMakowski** [comment]
> I think I prefer a methods-file, while @DominiqueMakowski prefers keeping functions and methods together in one file.

It depends, if a method is specific to a function (almost only used by it) than I prefer in the same file, if a method is very generic and used by many functions, then a separate file 🤷‍♂️

**Comment by strengejacke** [comment]
We should add that to our code-conventions. ;-)

**Comment by mattansb** [comment]
I prefer them in separate files always 🤷‍♂️

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/SZugp2K9LkL6w/giphy.gif)
