### ISSUE TITLE
get_contrasts and analyze functions

### ISSUE THREAD

**Issue by fatconeyno1** [easystats/easystats#67]
Hi,

get_contrasts and analyze functions are used to be in "psycho" package. They are not in psycho nor easystats package. Where can I find them?

Thanks,
Jiexin

**Comment by strengejacke** [comment]
@DominiqueMakowski I guess this one can be best answered by you...

**Comment by DominiqueMakowski** [comment]
@strengejacke thanks, @fatconeyno1 contrasts and means have been moved to the [modelbased](https://github.com/easystats/modelbased#contrast-analysis) package.
