### ISSUE TITLE
Trend figure

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#68]
[This figure](https://github.com/easystats/easystats/blob/master/man/figures/unnamed-chunk-6-1.png) becomes a bit confusing with all the text on it. What would you say if we remove the text annotations? (and maybe thinnen the loess-lines a bit...)

**Comment by mattansb** [comment]
Agree - I would also remove the linear trend line (:

**Comment by DominiqueMakowski** [comment]
agree - also instead of loess smooth trend instead of loess which can get a bit wild, maybe we could try a rolling average with with a window of 7/14 days (to essentially flatten out the high-frequency weekly cycles that we have)

**Comment by strengejacke** [comment]
> a rolling average 

never heard of such a model before, but sounds interesting ;-) you mean the mean by week / 14 days?
