### ISSUE TITLE
Next release cycle

### ISSUE THREAD

**Issue by mattansb** [easystats/easystats#69]
I'd like to push for a release of `effectsize` soon. Would that be possible?
I think this would also call for `parameters` to be updated as well.

Anything else?

**Comment by DominiqueMakowski** [comment]
bayestestR? 🤔

**Comment by mattansb** [comment]
Oh right 😅
So we need, in this order:

- [ ] `bayestestR`
- [ ] `parameters`
- [ ] `effectsize`

Maintainers - assemble!

**Comment by DominiqueMakowski** [comment]
I'll submit bayestestR tomorrow then!

**Comment by strengejacke** [comment]
bayestestR is quite recent, or not? Or are there any dependencies that require a bayestestR update?
_parameters_ was just submitted to CRAN, should work with current CRAN and latest GitHub version.

**Comment by DominiqueMakowski** [comment]
bayestestR got on CRAN about a month ago (2020-04-20)

**Comment by mattansb** [comment]
parameters is also on CRAN more than a month (2020-04-08)

**Comment by strengejacke** [comment]
`easystats::on_CRAN()` should be green in best case or at least yellow. If red, and no request from CRAN, might be too early ;-)

Yes, parameters is now 6-7 weeks on CRAN, and I submitted yesterday.

**Comment by mattansb** [comment]
I didn't know we have that function! Awesome!

Also didn't you submitted - sneaky!
Then I'll submit effectsize once parameters is available (:

**Comment by strengejacke** [comment]
_parameters_ is on CRAN.

**Comment by mattansb** [comment]
Will submit effectsize tomorrow

**Comment by mattansb** [comment]
effectsize is on its way to CRAN.

**Comment by DominiqueMakowski** [comment]
that was fast
