### ISSUE TITLE
Not available on CRAN?

### ISSUE THREAD

**Issue by xiaoweiz** [easystats/easystats#70]
```r
> install.packages("easystats")
Warning in install.packages :
  package ‘easystats’ is not available (for R version 3.6.2)
```

**Comment by strengejacke** [comment]
No, CRAN policies state that packages which purpose is just to load other packages should not be submitted to CRAN.

Hence, you can only install via GitHub (but you need to install report from GitHub first, I think, but not sure).

**Comment by xiaoweiz** [comment]
Understood. Thanks. But the installation instruction on this repo should be revised accordingly. 
<img width="958" alt="Screenshot 2020-05-24 at 9 07 53 PM" src="https://user-images.githubusercontent.com/4540215/82754914-c296b000-9e02-11ea-952c-8620420de426.png">
