### ISSUE TITLE
Backwards compatibility 

### ISSUE THREAD

**Issue by mattansb** [easystats/easystats#71]
How far back should we try to support + set as `Depends: R (>= ___)`?

One issue is that continuous integration (on travis or github) often fails to test anything on older version of R due to issues with loading suggested packages into such testing environments. 
So in some instances backwards comp will be "blind" and will depend on users with older systems bringing things to our attention.

**Comment by DominiqueMakowski** [comment]
Here's the dates of the versions:

R 4.0.0 (April, 2020)
R 3.6.3 (February, 2020)
R 3.6.2 (December, 2019)
R 3.6.1 (July, 2019)
R 3.6.0 (April, 2019)
R 3.5.3 (March, 2019)
R 3.5.2 (December, 2018)
R 3.5.1 (July, 2018)
R 3.5.0 (April, 2018)
R 3.4.4 (March, 2018)
R 3.4.3 (November, 2017)
R 3.4.2 (September, 2017)
R 3.4.1 (June, 2017)
R 3.4.0 (April, 2017)
R 3.3.3 (March, 2017)
R 3.3.2 (October, 2016)
R 3.3.1 (June, 2016)
R 3.3.0 (April, 2016)

I'd say 2 years (3.5) seems fair

**Comment by strengejacke** [comment]
In my experience, since more and more people are using R, there are a lot of people using are "occasionally", i.e. every fews months when they write a paper or so. This means, probably 1-3 times a _year_. Those who started working with R 3.3 or R 3.4 still have R 3.3 or R 3.4 installed (and probably also their packages are from that state.

**Comment by strengejacke** [comment]
However, I also think that we could require R 3.5 for our packages. Hopefully, those who work with "outdated" R version have some assistance for updating ;-)

**Comment by strengejacke** [comment]
Any final decision on this? I'd say, R >= 3.5 is fine now.

**Comment by mattansb** [comment]
I agree with @DominiqueMakowski -2 years (which now would be 3.5.1) is quite fair (:

**Comment by IndrajeetPatil** [comment]
I vote for >= 3.5 as well!

**Comment by mattansb** [comment]
2 years - is now `R 3.5.2`...

**Comment by strengejacke** [comment]
?

**Comment by IndrajeetPatil** [comment]
I think @mattansb is arguing that the minimum R requirement for `easystats` packages can be bumped to `3.5.2` over the current `3.2`:

<img width="970" alt="Screenshot 2020-12-05 at 16 48 15" src="https://user-images.githubusercontent.com/11330453/101247405-c2645f00-3719-11eb-888c-49237fd6e04d.png">

**Comment by mattansb** [comment]
Yup

**Comment by mattansb** [comment]
> `Dependence on R version '3.5.2' not with patchlevel 0`

So it is not advisable to specify a dependence on R that is patchlevel (third number) specific. So sticking to 3.5 (until April 2021!)

**Comment by strengejacke** [comment]
closing in favor of #98
