### ISSUE TITLE
"Critical" updates

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#72]
Just FYI...

@DominiqueMakowski @mattansb @IndrajeetPatil Due to errors in the [panelr-package](https://cran.r-project.org/web/checks/check_results_panelr.html) _insight_ and _parameters_ have failing tests, thus needed to be updated on CRAN. I contacted the maintainer of the _panelr_ package, who told me he would probably be not able in time to fix his package - that would have resolved the insight and parameters problems. So I removed the tests for now and submitted to CRAN.

_parameters_ has just landed (v0.8.0), _insight_, however, has some strange check issues for Debian:

```
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers

Flavor: r-devel-linux-x86_64-debian-gcc
Check: dependencies in R code, Result: NOTE
  
   *** caught segfault ***
  address 0x7f57b7274008, cause 'invalid permissions'
  
  Traceback:
   1: dyn.load(file, DLLpath = DLLpath, ...)
   2: library.dynam(lib, package, package.lib)
   3: loadNamespace(p)
   4: withCallingHandlers(expr, message = function(c) if (inherits(c,     classes)) tryInvokeRestart("muffleMessage"))
   5: suppressMessages(loadNamespace(p))
   6: withCallingHandlers(expr, warning = function(w) if (inherits(w,     classes)) tryInvokeRestart("muffleWarning"))
   7: suppressWarnings(suppressMessages(loadNamespace(p)))
   8: doTryCatch(return(expr), name, parentenv, handler)
   9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
  10: tryCatchList(expr, classes, parentenv, handlers)
  11: tryCatch(suppressWarnings(suppressMessages(loadNamespace(p))),     error = function(e) e)
  12: tools:::.check_packages_used(package = "insight")
  An irrecoverable exception occurred. R is aborting now ...
  Segmentation fault
```

Not sure what this means, couldn't find any hints on the web and also ask on the r-devel-mailinglistm with no success. CRAN team is aware and will inspect. If you have any ideas, or can check on Debian, let me know :-)

**Comment by DominiqueMakowski** [comment]
Very weird indeed

**Comment by IndrajeetPatil** [comment]
Have no idea. But sometimes CRAN checks fail temporarily, so this might be one of those cases. 
We can wait and see if CRAN can reproduce this.

**Comment by strengejacke** [comment]
Both on CRAN now.
