### ISSUE TITLE
Problems with the package installation in R version 4.0.2

### ISSUE THREAD

**Issue by JulianGaviriaL** [easystats/easystats#74]
Hello,

When trying to install easystats package from github:
```
install.packages("devtools")
devtools::install_github("easystats/easystats")
```

I get the following error message:
```
ERROR: package installation failed
Error: Failed to install 'easystats' from GitHub:
  Failed to install 'performance' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** using staged installation
E> ** R
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error: object 'format_p' is not exported by 'namespace:insight'
E> Execution halted
E> ERROR: lazy loading failed for package 'performance'
E> * removing 'C:/Users/gavirial/AppData/Local/Temp/RtmpQ1WPv1/Rinst48a86786776a/performance'
E>       -----------------------------------
E> ERROR: package installation failed
```
Is there any alternative for installing this package in R version 4.0.2 in windows PC? 

Thanks in advance.

**Comment by strengejacke** [comment]
If your packages are not "synched" from CRAN, you may have problems with installation. I suggest you install the latest versions from GitHub (i.e. insight, bayestestR, parameters, performance, correlation, modelbased, effectsize and see) and then easystats.

Sorry for the hassle, but we haven't cared about a more user friendly installation process for easystats yet.
