### ISSUE TITLE
hexsticker for the entire ecosystem

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#75]
Although we have stickers for all the individual packages, we currently do not have a sticker for the entire package ecosystem as a whole.

Just like with [tidyverse](https://tidyverse.tidyverse.org/articles/paper.html#:~:text=At%20a%20high%20level,%20the%20tidyverse%20is%20a%20language%20for), it will be nice to have a sticker for the ecosystem as well.

**Comment by mattansb** [comment]
A monster first giving a "thumbs up"? 😎

**Comment by DominiqueMakowski** [comment]
It's true, it'd be nice! 

> A monster first giving a "thumbs up"? 😎

And like the monster is the result of the [assemblage](https://youtu.be/MATWV9zhSsg?t=157) out of smaller monsters to underline that with little bricks you can build big things 😁 

That's outside my skills though I'm afraid haha

Until now I've been using this collage 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/8875533/89484746-b7340d80-d7d1-11ea-812a-4b83dc88ecd9.png)

**Comment by pdwaggoner** [comment]
We could potentially commission something from [Allison Horst](https://github.com/allisonhorst), the RStudio artist in residence... Depends how serious we want to be about this. I do like the collage too though for what it's worth. 

And side note, I am currently finishing an intro to R and tidyverse book for social scientists with a colleague for CRC press, and the `easyverse` is featured throughout. Exciting and fun to share the excellent work of this group! Thanks all.

**Comment by mattansb** [comment]
Hex-collage, with room to grow?
<img src="https://user-images.githubusercontent.com/35330040/89533418-10b13200-d7fc-11ea-8602-d2fbc1dfbb50.png" alt="drawing" width="200"/>

---

Allison's little stats-monsters seem like a perfect fit, if we want to get serious and also have her touch-up / redesign / streamline some existing hexs (then mass-produce stickers, and make billions!)

**Comment by pdwaggoner** [comment]
> and make billions!

That's exactly why I became an academic!! Oh wait... 

This looks cool though! I like it at least as a start.

**Comment by bwiernik** [comment]
I think that a cleaner sticker with just the name `easystats` and the snap might be better. That would be easiest to print stickers for. The ecosystem nature could be illustrated by showing a collage of package logos ala https://www.tidyverse.org/ or https://www.tidymodels.org/.

**Comment by mattansb** [comment]
Agreed!

**Comment by mattansb** [comment]
Also, let's get some prints!

**Comment by bwiernik** [comment]
Where do the source files of the package hex logos live?

**Comment by DominiqueMakowski** [comment]
Most of the figures stuff is here https://github.com/easystats/easystats/tree/master/man/figures
