### ISSUE TITLE
next update round...

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#76]
Just to keep you updated about recent updates

- insight 0.9.5 on CRAN
- parameters 0.8.5 on CRAN
- performance 0.5.0 on CRAN

_see_ will be submitted within the next days.

@DominiqueMakowski what about _modelbased_ or _correlation_? Any new features / bug fixes that justify an update? Or @mattansb, what about _effectsize_?

**Comment by mattansb** [comment]
I'd like to finish with https://github.com/easystats/effectsize/issues/105 (and maybe @DominiqueMakowski can fix https://github.com/easystats/effectsize/issues/104? 👀😉) and then I'll submit - in the next couple of weeks (:

**Comment by DominiqueMakowski** [comment]
No new stuff for modelbased and correlation. Eventually, for the latter, I'd like to give a look at the Bayesian partial correlations, but that won't happen in the next few days. I'll try to give a look at the effectsize thingy soon (I put it in my todo list 😁). Would be nice to upload report to CRAN too so that then we can officially start releasing the 1.0.0 versions :)

**Comment by strengejacke** [comment]
CRAN version of modelbased is from 12th March, and there have been quite some new features and fixes since then, no?

**Comment by strengejacke** [comment]
Same for correlation, it now also includes the JOSS paper.

**Comment by strengejacke** [comment]
Maybe someone forgot to care about the news file, so it's not that obvious that new features have been implemented... 😆

**Comment by DominiqueMakowski** [comment]
I'll submit correlation probably tomorrow, as I added a few methods and fixes. And modelbased too.

**Comment by strengejacke** [comment]
will re-submit _insight_ and _parameters_ the next days... 

_insight_ suddenly has all these errors in the CRAN checks (https://cran.r-project.org/web/checks/check_results_insight.html), and I don't know why. insight has been on CRAN for some days, all were OK, afex (which tests fails) was not updated, and the errors are also on the R release, so not related to changes in R devel.

In _parameters_, we missed some crucial issues and some reverse dependency issues with _effectsize_, all which were not yet detected by tests. Issues were fixed, tests added, but these are some really annoying bugs so I hope it'll be accepted on CRAN.

**Comment by mattansb** [comment]
But not this https://github.com/easystats/parameters/issues/301 right? This needs the *next* version of effectsize (:

**Comment by strengejacke** [comment]
No, but due to the removal of the class-attribute, standardizing in the current _parameters_ no longer works (unless = "refit"). Now it should work with current and forthcoming effectsize.

**Comment by mattansb** [comment]
current = CRAN , future = Github master branch?

I guess I'll have to trust you 😀😎

**Comment by strengejacke** [comment]
Yes to both :-)

**Comment by strengejacke** [comment]
@DominiqueMakowski From my side, _report_ is ready for initial submission...

**Comment by strengejacke** [comment]
I just resubmitted _parameters_... Any schedule for _report_? I'll "close" my contributions now (unless any hotfixes or so are required, where I can help), so we / @DominiqueMakowski can prepare the submission.

**Comment by DominiqueMakowski** [comment]
I wanted to revise the README a bit, to submit it after all of the other easystats packages have been updated (we could even place hard bounds on report's dependencies versions so that it requires people to finally update their easystats packages (I know several all of them that didn't do it for a while 😁)

**Comment by strengejacke** [comment]
> after all of the other easystats packages have been updated

You mean _modelbased_ and _correlation_? _effectsize_, _parameters_, _insight_, _performance_ and _see_ are fairly recent.

**Comment by strengejacke** [comment]
> I know several all of them that didn't do it for a while

Yeah, like using package functions that have been removed years ago... 😄

**Comment by DominiqueMakowski** [comment]
> You mean modelbased and correlation?

Yes, will submit them now

**Comment by IndrajeetPatil** [comment]
> will re-submit _insight_ and _parameters_ the next days...
> 
> _insight_ suddenly has all these errors in the CRAN checks (https://cran.r-project.org/web/checks/check_results_insight.html), and I don't know why. insight has been on CRAN for some days, all were OK, afex (which tests fails) was not updated, and the errors are also on the R release, so not related to changes in R devel.
> 
> In _parameters_, we missed some crucial issues and some reverse dependency issues with _effectsize_, all which were not yet detected by tests. Issues were fixed, tests added, but these are some really annoying bugs so I hope it'll be accepted on CRAN.

@strengejacke  There are no more errors in `insight` CRAN checks.

**Comment by strengejacke** [comment]
> @strengejacke There are no more errors in `insight` CRAN checks.

Yes, since the last update a few days ago.

**Comment by strengejacke** [comment]
@DominiqueMakowski What about _report_? Time to submit, or is there anything required to be fixed before submission?

**Comment by mattansb** [comment]
FYI: `effectsize` (last updated Sep 17) will need to be updated on CRAN by Nov 16 (for teaching 😀).
[I don't think anything (insight, parameters) needs to be updated on CRAN before that.]

**Comment by DominiqueMakowski** [comment]
report will need the latest effectsize, and feature-wise there's as of this morning only aovs and regressions left, will try to advance today

**Comment by IndrajeetPatil** [comment]
With the release of `insight`, I need to start updating `ggstatsverse` packages, which would require the latest versions of 
`parameters`, `effectsize`, and `performance` with the deadline:

![image](https://user-images.githubusercontent.com/11330453/96842456-566db600-144d-11eb-892f-815cf3c66f37.png)

Is this possible?

**Comment by strengejacke** [comment]
_effectsize_ needs to be submitted to CRAN before _parameters_, but _parameters_ is ready. And so is _performance_, I'd say. @DominiqueMakowski will hopefully submit _bayestestR_ soon, some test-issues needs to be fixed (https://github.com/easystats/bayestestR/issues/347) - however, I'm not sure if _bayestestR_ update is required by one of the other packages?

**Comment by mattansb** [comment]
bayestestR's update is required for performance.

**Comment by strengejacke** [comment]
1. insight (on CRAN
2. bayestestR (submitted)
3. effectsize
4. parameters
5. performance

**Comment by mattansb** [comment]
I hope to submit over the weekend (:

**Comment by IndrajeetPatil** [comment]
@strengejacke When do you plan to submit `parameters` to `CRAN`? 

I'd prefer if both `parameters` and `performance` are both on CRAN by 31st of October 🎃, so that I will at least have a couple of spare days to work on making necessary changes before start submitting my packages.

**Comment by strengejacke** [comment]
all on CRAN from my side, @DominiqueMakowski your turn with report now.

**Comment by DominiqueMakowski** [comment]
cannot, it relies on the latest of bayestestR which got submitted recently.

Let's give us like 2 weeks to test-out report and fix the most obvious issues before the initial release

**Comment by strengejacke** [comment]
bayestestR is on CRAN, or not? But anyway, we can do some final checks the next two weeks...

**Comment by DominiqueMakowski** [comment]
It is, but then the sexit framework was just added after its upload on CRAN, and report currently only supports it ^^

**Comment by IndrajeetPatil** [comment]
Closing this. 

We can open a new issue when the next next round is on the docket. :D
