### ISSUE TITLE
roxygen2md

### ISSUE THREAD

**Issue by mattansb** [easystats/easystats#77]
I'd like to suggest we switch to markdown based roxygen documentation (currently al ready implemented in `effectsize`).
This can be done semi-automatically with [`roxygen2md`](https://roxygen2md.r-lib.org/).

Tracking progress here:

- [x] insight 
- [ ] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] `datawizard`

**Comment by DominiqueMakowski** [comment]
Yes I agree, it should make it neater, though expect old dinosaurs like me to still write latex here and there out of habit 😬

**Comment by strengejacke** [comment]
I'm not sure about the translation of tags, honestly. How would I write stuff like `subsection{}`, `describe{}`, `\cite{}`, `\dQuote{}`, and all those formula-stuff?

**Comment by strengejacke** [comment]
For example: https://easystats.github.io/insight/reference/get_variance.html
How would this translate into markdown?

**Comment by mattansb** [comment]
Not all tags have an md equivalent, but some do (subsection is just `##`, like a basic md header 2), but it mostly makes the need for latex formatting obsolete, for example: 

```
#' @return A list with following elements:
#'    \itemize{
#'      \item \code{var.fixed}, variance attributable to the fixed effects
#'      \item \code{var.random}, (mean) variance of random effects
#'      \item \code{var.residual}, residual variance (sum of dispersion and distribution)
#'      \item \code{var.distribution}, distribution-specific variance
#'      \item \code{var.dispersion}, variance due to additive dispersion
#'      \item \code{var.intercept}, the random-intercept-variance, or between-subject-variance (\ifelse{html}{\out{&tau;<sub>00</sub>}}{\eqn{\tau_{00}}})
#'      \item \code{var.slope}, the random-slope-variance (\ifelse{html}{\out{&tau;<sub>11</sub>}}{\eqn{\tau_{11}}})
#'      \item \code{cor.slope_intercept}, the random-slope-intercept-correlation (\ifelse{html}{\out{&rho;<sub>01</sub>}}{\eqn{\rho_{01}}})
#'    }\
```

Would just be:
```
#' @return A list with following elements:
#' - `var.fixed`, variance attributable to the fixed effects
#' - `var.random`, (mean) variance of random effects
#' - `var.residual`, residual variance (sum of dispersion and distribution)
#' - `var.distribution`, distribution-specific variance
#' - `var.dispersion`, variance due to additive dispersion
#' - `var.intercept`, the random-intercept-variance, or between-subject-variance (\ifelse{html}{\out{&tau;<sub>00</sub>}}{\eqn{\tau_{00}}})
#' - `var.slope`, the random-slope-variance (\ifelse{html}{\out{&tau;<sub>11</sub>}}{\eqn{\tau_{11}}})
#' - `cor.slope_intercept`, the random-slope-intercept-correlation (\ifelse{html}{\out{&rho;<sub>01</sub>}}{\eqn{\rho_{01}}})
```

**Comment by DominiqueMakowski** [comment]
and subsections would be like `## subsection` I assume? and cite like \[link\]\(address)? But we can basically use a mixture of latex and markdown right? we don't have to change *everything* at once?

**Comment by mattansb** [comment]
Yes to all of that ^

**Comment by IndrajeetPatil** [comment]
I am shadowing @mattansb's opinion here. 
In all my packages, I use the markdown-based approach and it's way easier to write and maintain!

**Comment by mattansb** [comment]
@IndrajeetPatil You seem to be the champion of stylizing code and docs... I think this might fall under that category 😅

**Comment by IndrajeetPatil** [comment]
On it. Going to be huge changes though, and you will have to double-check that all changes make sense. 
I will start making PRs.

- [ ] insight 
- [ ] modelbased
- [ ] bayestestR
- [ ] effectsize
- [ ] parameters
- [ ] performance
- [ ] correlation
- [ ] report
- [ ] see

**Comment by DominiqueMakowski** [comment]
little updates might be easier to check than a massive PR 😁

**Comment by strengejacke** [comment]
I'm not sure we have a full coverage of all rd-tags in markdown, so I would prefer not to have any changes (at least for packages I maintain).

**Comment by IndrajeetPatil** [comment]
What do you mean by _full coverage_ in the context of `.rd` docs? 
I am not sure how to check if anything goes wrong with the docs except to just read through them.

**Comment by strengejacke** [comment]
I mean that we don't have an equivalent for each rd-tag, if I'm not mistaken, and then probably end up mixing rd/latex and md.

**Comment by IndrajeetPatil** [comment]
This is a draft PR for insight for changing to markdown:
https://github.com/easystats/insight/pull/294

We can close it, but this will give you a reference for what this change might look like and how well it would translate.

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/106864246-8f801c80-6704-11eb-82db-7c4d822720c8.png)

*heart stops*

**Comment by IndrajeetPatil** [comment]
🤣 

Yeah, well, literally every `.R` file has some roxygen documentation, so a lot of files will be affected by this.

The translation is surprisingly well.

**Comment by strengejacke** [comment]
But the PR is not complete yet? Checks now fail:
https://github.com/easystats/insight/pull/294/checks?check_run_id=1829058823

**Comment by IndrajeetPatil** [comment]
You said you wouldn’t want this to be done to any of the repos you maintain. So this was just meant to be a minimum effort demo for what these changes might look like. 

Maybe each maintainer can do this as they see fit (entire package, file by file, etc.).

This package makes this change a child’s play anyway:
https://roxygen2md.r-lib.org/

**Comment by strengejacke** [comment]
Ah, ok. I thought that was a fully working example. :-)

**Comment by IndrajeetPatil** [comment]
@strengejacke Can I please convert the roxygen docs to markdown for `see`?

**Comment by strengejacke** [comment]
Feel free to do so. :-)

**Comment by IndrajeetPatil** [comment]
Will handle `modelbased` once https://github.com/easystats/modelbased/pull/132 is merged.

**Comment by IndrajeetPatil** [comment]
Can someone tell me what does this do in the roxygen docs? Leave an empty line?

```r
#'   \cr \cr
```

**Comment by bwiernik** [comment]
Yes. That's "carriage return" -- make a blank line between two paragraphs.

**Comment by bwiernik** [comment]
Not sure if it's necessary. I think there should be a blank line already if they are just typed that way.

**Comment by IndrajeetPatil** [comment]
Cool, thanks! 

Yeah, I also _think_ that that's the default behavior.
