### ISSUE TITLE
switch to testthat 3rd edition for testing

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#79]
I suggest we move to testthat 3rd edition because it also allows parallel support, which makes testing much faster:
https://www.tidyverse.org/blog/2020/10/testthat-3-0-0/

We just need to add the following to `DESCRIPTION` and might have to make some minor changes to the tests, but should be pretty straightforward.

```makefile
Config/testthat/edition: 3
Config/testthat/parallel: true
```

What do you think?

**Comment by mattansb** [comment]
We would also need to add `testthat (>= 3.0.0)` to suggests, right?

**Comment by IndrajeetPatil** [comment]
Umm, no, not necessary. The `Config` figures that out.

Here is an example from `tidyBF` where I don't specify this and all the builds succeed:
https://github.com/IndrajeetPatil/tidyBF/blob/master/DESCRIPTION

**Comment by mattansb** [comment]
effectsize has also switched.

It's kinda weird that some tolerances have changes between ed2 and ed3, no? Seems like they switched some beack end algorithm, and it really gave me a headache...

**Comment by IndrajeetPatil** [comment]
Yeah, but the trouble is totally worth the performance improvement! 😅

**Comment by IndrajeetPatil** [comment]
Logging the progress here:

- [ ] see
- [x] insight 
- [ ] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [ ] correlation
- [ ] modelbased
- [ ] report

**Comment by IndrajeetPatil** [comment]
Note to self: The following line needs to be removed from `DESCRIPTION`, since this is not relevant for `easystats` packages at all

```r
Config/testthat/start-first: watcher, parallel*
```

It's a handy tool though to test the most important functions first and then move to other less important ones.
