### ISSUE TITLE
Model Performance package

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#8]
Seems like the name "performance" is available on CRAN :)

This could be a good name for covering the computation of all goodness of fit metrics, i.e., whether a model is performant in its prediction of the outcome.

From a design perspective, there could be a set of functions implementing the "computation" per se of non-base indices (Tjur's, nakawaga etc.), starting with `compute_R2tjur`, `compute_R2nakawaga` and a set of functions for retrieving these indices from the models, `performance_R2tjur(model)` etc.

Or, only one set of functions `performance_R2foo()` that would both be applicable to vectors and matrices (used for index computation), and to models (which would then retrieve the relevant things from the model and do the index computation using the former function).

**Comment by DominiqueMakowski** [comment]
Note for future, logo ideas could include (to keep consistency ^^) a roaring monster with either a small person measuring its height with a ruler, or the monster in front of a [jury](https://cdn.brainpop.com/socialstudies/usgovernment/trials/icon.png) holding some panels with grades (e.g., 7 - 9 - 8). With a different colour scheme to both keep consistency in the content and theme and underline the packages unicity.

**Comment by DominiqueMakowski** [comment]
If we keep that theme, maybe the distribution in [bayestestR's logo](https://github.com/easystats/bayestestR/blob/master/man/figures/logo.svg) could be a ghost (inspired by [this](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/37e18925-3700-4cf8-b1cd-e6fad961c8b2/dbnhztz-b48b80a4-72d1-477d-a5b6-1e349a7e9432.jpg))... And [report's logo](https://github.com/neuropsychology/report/blob/master/man/figures/logo.png) could be another monster next to a black and white sketchy drawing of that same monster on a paper sheet (representing the "report" of an object on a sheet)... Alright I think you have to stop me I'm going too far haha

**Comment by DominiqueMakowski** [comment]
However philosophically this "monster" analogy makes sense; doing stats, using R and stats models are often seen as something frightening that are too complex/hard to overcome, and the goal of easystats is to help users defeating their beasts, and help them rule the unruly models 😅

**Comment by strengejacke** [comment]
I also like the "monster" analogy, or something similar. A ghost would indeed fit to bayestestR. I also uses the paranormal-distribution ghost in one of my lectures... :-)

**Comment by DominiqueMakowski** [comment]
Note for future related to the performance package, someone recently dug out an [old thread](https://discourse.mc-stan.org/t/marginal-and-conditional-r2-for-stans-glmms/4557/6) related to the R2 for Bayesian models. To my knowledge, no packages implement an easy way of extracting different R2 metrics for Bayesian mixed model (and their posterior distribution). However, it seems to be feasible (hence my [original question](https://github.com/strengejacke/sjstats/issues/65) on sjtats 😅). 

I reckon that if we succeed in implementing such R2 metrics computation for Bayesian mixed models, it would be a very useful star feature (that could attract new users).
