### ISSUE TITLE
Missing functions psycho package

### ISSUE THREAD

**Issue by irenechenshen** [easystats/easystats#80]
Hiya,

I read the blogpost on "Beautiful and Powerful Correlation Tables in R", and was trying to use is, but then I got this error:

```
library(psycho)
library(tidyverse)
cor <- psycho::affective %>% correlation()
```
Error in correlation(.) : could not find function "correlation"

Was just wondering if this is a new problem and how to fix it...

many thanks!

**Comment by strengejacke** [comment]
Please refer to the [correlation package](https://easystats.github.io/correlation/). This is where you find all the new re-implementations of the correlation functions.

**Comment by DominiqueMakowski** [comment]
@irenechenshen yes, all the correlation-related functions have been moved to the eponym package. Let us know if you encounter any issues

**Comment by irenechenshen** [comment]
> @irenechenshen yes, all the correlation-related functions have been moved to the eponym package. Let us know if you encounter any issues

thank you, using the correlation package solved my problem :)
