### ISSUE TITLE
could not find function "analyze"

### ISSUE THREAD

**Issue by P300** [easystats/easystats#81]
library(psycho)
"Note: Many functions of the 'psycho' package have been (improved and) moved to other packages of the new 'easystats' collection (https://github.com/easystats). If you don't find where a function is gone, please open an issue at: https://github.com/easystats/easystats/issues"

**Comment by DominiqueMakowski** [comment]
`analyze` has been moved to the 'report' package (and has been renamed `report()`), please follow the instructions on this page: https://github.com/easystats/report
