### ISSUE TITLE
Issues installing and loading "parameters" and "insight" packages

### ISSUE THREAD

**Issue by Kuroshiwo** [easystats/easystats#82]
I keep getting errors in RStudio on Windows OS 10, which ever way i tried. See below

> librarian::shelf(easystats / easystats,
+                  lib = "C:/Users/richa/Documents/R/win-library/4.0")
Error: package or namespace load failed for ‘easystats’:
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: NULL
  error: package or namespace load failed for ‘parameters’:
 object ‘to_table’ is not exported by 'namespace:insight'

> librarian::shelf(easystats / parameters,  easystats / insight,
+                  lib = "C:/Users/richa/Documents/R/win-library/4.0")
Error: package or namespace load failed for ‘parameters’:
 object ‘to_table’ is not exported by 'namespace:insight'

> library(insight)
> library(parameters)
Error: package or namespace load failed for ‘parameters’:
 object ‘to_table’ is not exported by 'namespace:insight'
> library(parameters)
Error: package or namespace load failed for ‘parameters’:
 object ‘to_table’ is not exported by 'namespace:insight'

Thanks.

**Comment by strengejacke** [comment]
See https://github.com/easystats/see/issues/80
