### ISSUE TITLE
next update round: Christmas special

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#83]
- [x] insight 
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] modelbased
- [ ] report
- [x] see

**Comment by strengejacke** [comment]
@mattansb @DominiqueMakowski Make sure that you 

1. rename all former instances of `parameters::parameters_table()` into `insight::parameters_table()`.
2. rename all former instances of `insight::format_table()` into `insight::export_table()`.

for this update round.

**Comment by IndrajeetPatil** [comment]
When is `parameters` going to be submitted to `CRAN`?

**Comment by strengejacke** [comment]
Next week...

**Comment by strengejacke** [comment]
parameters and performance on CRAN

**Comment by DominiqueMakowski** [comment]
Will push bayestestR and correlation

**Comment by mattansb** [comment]
After bayestestR is on, I'll push effectsize.

**Comment by DominiqueMakowski** [comment]
new correlation on CRAN

**Comment by DominiqueMakowski** [comment]
bayestestR on CRAN

**Comment by strengejacke** [comment]
Great, so effectsize can be submitted now, @mattansb ? And what about modelbased?

**Comment by DominiqueMakowski** [comment]
modelbased can follow (but tell me what you think of [this](https://github.com/easystats/modelbased/commit/e9075e9ae46373291783a8d88ea6f3f14db86104#commitcomment-44823171))

**Comment by DominiqueMakowski** [comment]
``` r
bayestestR::ci(rnorm(1000))
#> # Equal-Tailed Interval
#> Error in names(df) <- col_names: 'names' attribute [1] must be the same length as the vector [0]
```

<sup>Created on 2020-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@strengejacke can you tell me I forgot to update something 😅

**Comment by strengejacke** [comment]
Post your session info, pls:

``` r
bayestestR::ci(rnorm(1000))
#> # Equal-Tailed Interval
#> 
#> 89% ETI      
#> -------------
#> [-1.55, 1.64]
```

<sup>Created on 2020-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
```
loaded via a namespace (and not attached):
[1] effectsize_0.4.0.001 compiler_4.0.1       tools_4.0.1          parameters_0.9.0.1   report_0.2.0         insight_0.11.0.1    
[7] packrat_0.5.0 
```

**Comment by mattansb** [comment]
Waiting to close https://github.com/easystats/effectsize/issues/222, and will then submit.

**Comment by strengejacke** [comment]
@DominiqueMakowski Have you tried `easystats::install_easystats_latest()`?

**Comment by strengejacke** [comment]
_see_ is on CRAN.

**Comment by DominiqueMakowski** [comment]
Modelbased on cran

**Comment by mattansb** [comment]
effectsize is on CRAN

**Comment by strengejacke** [comment]
Ok, it was a little bumpy, but after sending hotfixes for _parameters_ and _insight_, I'd say we are now done with our updates for this year...

**Comment by DominiqueMakowski** [comment]
maybe we could maybe try for a Christmas surprise (which starts with *r* and ends with *eport*)?

**Comment by strengejacke** [comment]
Yes, yes, but I honestly lost track of the current state of that package. We were short before release some weeks ago, then you added/revised some features... Is it ready for initial submission?

**Comment by DominiqueMakowski** [comment]
I didn't add/revise almost anything since the last overhaul a month ago, so yeah pretty much ready I think!

**Comment by DominiqueMakowski** [comment]
Although I haven't see if to works with the new display / exporting API

**Comment by mattansb** [comment]
Very exciting!

**Comment by DominiqueMakowski** [comment]
report passes checks and all. I think it only needs the latest insight... we could attempt a first submission
