### ISSUE TITLE
Welcome mkshaw 🎉

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#84]
Hi @mkshaw Welcome to easystats 🎉 a place for us to learn and eventually sometimes help others (and ourselves) in their conquest of stats. And again, congrats for your package [r2mlm](https://github.com/mkshaw/r2mlm), it's great!

You might wonder what is expected of members? Nothing, we all have busy schedules and other priorities, so no worries on that side. But feel free to comment, give suggestions in issues, retweet easystats tweets and such whenever you feel comfortable enough. You might see us ping specific people from time to time, but we encourage everyone to give their opinion and thoughts even if not directly pinged (or just reacting with a 👍 or a 😠). We have also given you writing access to the repos, so if you spot any typo or something to improve, you can make a PR to fix (or open an issue if you want to check first).

I'd recommend to "watch" (follow) all the [easystats repos](https://github.com/easystats), to stay tuned to what's going on, as we usually work in parallel (and chaotically create and move around issues in several places) :)

Easystats, a collection of packages, has a "pyramidal" organization with low-level packages, such as "insight" (named "low-level" because they do not depend on anything than themselves to work), which are cornerstones for other mid-level packages (such as effectsize, parameters and performance), which themselves are used by high-level packages (e.g., report or see) that uses the power and synergy of the whole ecosystem to achieve their purpose. Some packages are also focused on specific features/aspects/data analysis type (e.g., bayestestR, correlation, ...). This is the way it is for now, but who knows what the future has in store! 

We also focus a lot on the API, with the goal of providing the best user experience, to be intuitive and convenient, especially for new users unfamiliar with stats or R. So you might see from time to time some lengthy and obscure discussions about whether to name some column `Chi2` or `Chisq` or something even more random, so don't be surprised 😁 

Speaking of future, for a **"roadmap context"**, one of the priority is to push the only remaining easystats package `report` to CRAN. And aside from that, there is plenty of things left to be done, such as stabilizing the API, improving documentation, testing, blogging, etc. etc. Given your expertise, you might take a specific look at `performance`, which computes indices of performance for models (such as R2 measures for mixed models), as well as `effectsize`, in which we are providing measures of effect size for models' parameters. 

Don't hesitate if you have any questions, and free to share any questions thoughts, ideas, suggestions (or memes)!

@strengejacke @mattansb @IndrajeetPatil anything else I have missed?

**Comment by IndrajeetPatil** [comment]
Welcome, @mkshaw! 😊

Loved `r2mlm` as well.

Looking forward to working with you here. And, I concur with Dominique, that `performance` could use your love and help. 😊

**Comment by mkshaw** [comment]
Thanks for having me! 😄 I'm excited to help develop the ecosystem and learn a bunch along the way.

**Comment by mattansb** [comment]
Welcome aboard, Mairead!
