### ISSUE TITLE
Using testthat::skip_if_not_installed()

### ISSUE THREAD

**Issue by mattansb** [easystats/easystats#86]
I suggest replacing 

```R
if (require("suggested_package")) {
  test_that("test", {
    # run the tests
  })
}
```

With
```R
test_that("test", {
  testthat::skip_if_not_installed("suggested_package")
  # run the tests
})
```

I've already done this in `effectsize` (https://github.com/easystats/effectsize/pull/220/commits/605d15d82be59f3bf8850706bc5658d7f3d91946)- seems like the way to go (makes the code more readable and explicit)

Progress tracker:

- [ ] insight 
- [ ] modelbased
- [ ] bayestestR
- [x] effectsize
- [ ] parameters
- [ ] performance
- [ ] correlation
- [ ] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
Sometimes, loading data or fitting models is done outside `testthat()` and requires the package, so you can't skip before checking if the pkg is available or not...?

We could also completely ban testthat and only rely on base R for testing :-)

**Comment by mattansb** [comment]
> Sometimes, loading data or fitting models is done outside testthat() and requires the package, so you can't skip before checking if the pkg is available or not...?

Good point... I solved that by putting them all together into one `test_that`.

> We could also completely ban testthat and only rely on base R for testing :-)

![image](https://user-images.githubusercontent.com/35330040/100895313-124ae800-34c6-11eb-9bb3-526c35e972a2.png)

**Comment by IndrajeetPatil** [comment]
Done for _datawizard_.

**Comment by IndrajeetPatil** [comment]
I don't think this change is something any of the maintainers are actively working on making or even planning to do so.

I would just add the label "Beginner friendly" and "Help Wanted" labels, and see if anyone wants to help us with this labor-intensive change.

**Comment by IndrajeetPatil** [comment]
Done for `{see}`.

**Comment by IndrajeetPatil** [comment]
Closing in favour of https://github.com/easystats/easystats/issues/350.
