### ISSUE TITLE
Issue with installation 

### ISSUE THREAD

**Issue by Nikazahe** [easystats/easystats#87]
Hi, 
The installation error I get is pasted below. I'd appreciate your help. 

>devtools::install_github("easystats/easystats")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 99.241.67.67. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
  Rate limit remaining: 0/60
  Rate limit reset at: 2020-12-04 00:30:08 UTC
  To increase your GitHub API rate limit
  Use `usethis::browse_github_pat()` to create a Personal Access Token.
  Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

**Comment by strengejacke** [comment]
Looks like

> API rate limit exceeded for

you have downloaded too much from GitHub in a certain time span. You could try:

> To increase your GitHub API rate limit
Use usethis::browse_github_pat() to create a Personal Access Token.
Use usethis::edit_r_environ() and add the token as GITHUB_PAT.
