### ISSUE TITLE
Train Test Split Question

### ISSUE THREAD

**Issue by jcvall-olympus** [easystats/easystats#88]
Thanks for the great work on the easystats.  I was wondering... Is there a function to do train test splits in the package?  How do you usually handle that?

**Comment by DominiqueMakowski** [comment]
Hi @jcvall-olympus, we have a function to split the dataset:

``` r
dfs <- parameters::data_partition(iris, training_proportion=0.6, group="Species")
test <- dfs$test
training <- dfs$training
```

<sup>Created on 2020-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Is it what you look for?

**Comment by jcvall-olympus** [comment]
Thanks for pointing this out.  This is exactly what I was looking for among the easystats packages.  I really love easystats.  Thank you for making my work easier!

**Comment by strengejacke** [comment]
Glad we could help here. Note that the easystats packages currently don't provide much functions according to ML / cross-validation. `data_partition()` is indeed currently one of the few functions in that direction.

**Comment by DominiqueMakowski** [comment]
That said, @jcvall-olympus if you have any ideas / suggestions of useful features, please let us know 😉
