### ISSUE TITLE
Test for using suggested packages only conditionally

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#89]
I just got an email from CRAN, requesting to update _performance_, because there were still some occurrences, where suggested packages were not used conditionally.

We / you (@mattansb @DominiqueMakowski) should test that in your packages as well. You can do this...

1. by creating a file named `check.Renviron` in the folder `C:\Users\<username>\Documents\.R\` (if this file does not already exist)
2. Add the line `_R_CHECK_DEPENDS_ONLY_=true` to that file
3. in RStudio, go to the **Build** panel, menu **Configure build tools** and then remove the check from **Use  devtools package functions when available**
4. Then check your package.

**Comment by IndrajeetPatil** [comment]
Can this be closed?

**Comment by strengejacke** [comment]
Yes, I think so.
