### ISSUE TITLE
Model parameters

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#9]
Another brick of the structure appears to be functions surrounding the model's parameters. This might include consistent parameters tables extraction (similar to what broom does), which might have its place in `insight`, and additional indices computation (CIs, p values, ROPEs and so forth). I am not sure whether this should be a separate package or included in the "performance" package. What do you think?

**Comment by strengejacke** [comment]
This is very close to the idea of the broom-packages. We have to think about the benefit / surplus this package would have compared to broom / broom.mixed, so the package will be recognized.

**Comment by DominiqueMakowski** [comment]
Yes. For report, (right before the creation of easystats), I actually thought of using broom as a basis, to which I added other things. 

I think that the main benefit of this package/part of a package would be providing this other stuff, which could include:

- effects *existence* indices: p values if not there originally, but ropes and others for Bayesian
- Different CIs (bootstrapped...)
- Effect sizes indices (standardized coefficients, omega squared etc.)

**Comment by strengejacke** [comment]
> omega squared etc.

I hate these ;-) I'm no ANOVA fan and have no idea why I should use it, and the functions around anovas in _sjstats_ (like `eta_squared()` etc.) are really stepmotherly treated by me ;-)

**Comment by DominiqueMakowski** [comment]
Haha I ***totally*** agree... the only reason why I am thinking about ANOVAs is due to their (still existing) widespread use in psychology. So I tell myself that neophytes will come and find out their ANOVAs can be easily done with R, and I hope to further encourage them using better procedures (like [here](https://neuropsychology.github.io/psycho.R/2018/05/01/repeated_measure_anovas.html) when I tried to trick newcomers into using mixed models 😈).

So yes if we implement these it we should put a minimal amount of effort in it. And it shouldn't be a focus. But it could help with the popularization in psych universities (for oldschool researchers *and* teachers/students (in Paris they still teach students how to do ANOVAs by hand... 😢))
