### ISSUE TITLE
bumping mimimum R version to `3.6`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#96]
Logging the progress here:

- [x] see
- [x] insight 
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [ ] modelbased

**Comment by mattansb** [comment]
I suggest we keep then to `oldrel` as the rule (make sure the CI tests are set up accordingly!)

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski The `Depends` field is missing from `DESCRIPTION` file in `modelbased`: https://cran.r-project.org/web/packages/modelbased/index.html
