### ISSUE TITLE
next update round: the rollback to `3.4` edition

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#98]
In light of https://github.com/easystats/insight/issues/284.

Only to be attended once #92 is closed.

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [ ] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] see
- [ ] report

**Comment by strengejacke** [comment]
@DominiqueMakowski @mattansb @vincentarelbundock

I _think_ we can safely roll back to R 3.4, not sure if we even need 3.3 (as I first suggested somewhere). Any opinions?

pinging:
https://github.com/easystats/effectsize/issues/277
https://github.com/easystats/insight/issues/284

**Comment by vincentarelbundock** [comment]
3.4 is very good! But is there something we need that was introduced there? I skimmed the NEWS (too quickly) but didn't see anything.

The older the better, but of course the gains are marginal at that stage, and 3.4 is already quite old. It feels like the key will be to be semi careful in future development not to overuse exciting new features, so that 3.4 could remain supported for a looong time.

**Comment by strengejacke** [comment]
bayestestR, insight, parameters have updated news, however, I need to change 3.3 into 3.4

**Comment by mattansb** [comment]
I'm good with whatever (:

**Comment by strengejacke** [comment]
Looks like [_parameters_](https://github.com/easystats/parameters/runs/1718501662) passes all tests - on 3.4, a warning is turned into an error, that's why it fails. I wonder if we should change this line in the workflow-file "R-check.yaml":

`rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")` 

and set `error_on = "error"` - anyone experiences with this?

**Comment by strengejacke** [comment]
insight, bayestestR, performance and parameters work, however, I set back R dependency for performance and bayestestR to 3.6, else we can't submit to CRAN.

**Comment by mattansb** [comment]
Once `effectsize` is on CRAN I'll roll back also to 3.4 on GH.

**Comment by IndrajeetPatil** [comment]
Issues to resolve before the next submission round starts (edit the list as new critical issues accrue):

- [ ] https://github.com/easystats/effectsize/issues/280#issuecomment-765249918
- [ ] https://github.com/easystats/performance/issues/193

**Comment by IndrajeetPatil** [comment]
Will we be submitting the `R > 3.4` versions of `insight` and `parameters` to `CRAN` soon(-ish)?

**Comment by strengejacke** [comment]
Depends on what you consider as "soon" ;-) As long as there are no critical bugs, I'd vote for waiting a minimum time:

![image](https://user-images.githubusercontent.com/26301769/106266041-36a61500-6228-11eb-8e63-cd91cec7ce3c.png)

**Comment by IndrajeetPatil** [comment]
haha

I see. No, I thought rolling back to `3.4` was critical enough (for other maintainers) that there would be new releases asap. 

But, if that's not the case, no hurry from my side.

**Comment by strengejacke** [comment]
@DominiqueMakowski what would you say, should we submit _performance_? We have added quite some new features, or does it require stuff from _insight_ that is not on CRAN?

**Comment by IndrajeetPatil** [comment]
I would prefer it if we can push `insight` and `parameters` to CRAN by 15th of Feb, since I can then also update my ecosystem in time.
 
We will have gathered a lot of new functionality by then. What do you think?

**Comment by DominiqueMakowski** [comment]
I don't think performance requires anything from insight, afaik the main feature that was added from me was get_predicted, which is not used in the testing of performance. That said, we might look for instances of `stats::predict()` and upgrade for insight's version if there are any

**Comment by DominiqueMakowski** [comment]
But doing an early hotfix cran update tour might not be a bad idea (cf. bayestestR :)

**Comment by IndrajeetPatil** [comment]
> But doing an early hotfix cran update tour might not be a bad idea (cf. bayestestR) :)

@strengejacke Should we set deadline of 15th of February? 😅 
We will have to update `insight`, `parameters`, `correlation`, and `bayestestR`.
`performance` update is not crucial from my end.

I would like to submit my packages by then, and I have a talk where I can present all the latest features. 😃

**Comment by strengejacke** [comment]
Has anyone experiences with the [tinytest](https://cran.r-project.org/package=tinytest) package? Might be an alternative to testthat, since I still can't figure out that mysterious failing checks (https://github.com/easystats/insight/issues/286).

**Comment by IndrajeetPatil** [comment]
I don't have any experience. 

But I don't think failing check on a single platform is a strong enough reason to abandon using `testthat`. But that's just my personal opinion.

**Comment by strengejacke** [comment]
_performance 0.7.0_ on CRAN

**Comment by DominiqueMakowski** [comment]
So after this update, the priority is to finally release report so that I can stop being stressed about someone stealing the name on CRAN ^^

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski I think all critical changes are made for `correlation`. Do you want to submit it to `CRAN` soon (next week)?

**Comment by DominiqueMakowski** [comment]
will do next week

**Comment by IndrajeetPatil** [comment]
Anyone knows why binaries are not built for these packages for `MacOS` on `R-release`?

<img width="577" alt="Screenshot 2021-02-10 at 10 49 34" src="https://user-images.githubusercontent.com/11330453/107493576-1104fe00-6b8e-11eb-9b22-d77816c201ab.png">

**Comment by strengejacke** [comment]
The reason is here: https://cran.r-project.org/web/checks/check_results_insight.html

insight fails for that os/system. That's related to https://github.com/easystats/insight/issues/286.
I'm not sure, but either there's a failing test due to instable packages on Mac, or the parallel processing of testthat is error-prone.

**Comment by IndrajeetPatil** [comment]
Can we please push new versions of `insight` and `parameters` to `CRAN` soon? 

I'd prefer if they make it by 15th of Feb, so that I can also update my packages.

**Comment by strengejacke** [comment]
@DominiqueMakowski how much are you already relying on `get_predicted()` in other packages?

**Comment by DominiqueMakowski** [comment]
> @DominiqueMakowski how much are you already relying on get_predicted() in other packages?

Zero for now, as it'll be a consequent refactoring of modelbased internals, so I wait a bit until it's stabilized (and supported by CRAN bayestestR)

**Comment by IndrajeetPatil** [comment]
`correlation` is on `CRAN`, so now `insight` and `parameters` can also proceed ahead.

If the `revdepcheck` flags any failure of tests in my packages, no worries. I have kept everything synched in GitHub versions, and they are good to go. Just make sure to mention that in `cran_comments`, so that the package doesn't get stuck.

**Comment by strengejacke** [comment]
I'd like to implement https://github.com/easystats/parameters/issues/66 before submission, which shouldn't be too complicated. The more complicated thing would be the print() method, because we need an additional header row that spans over multiple columns - this needs to be in insight. So probably by the end of next week we could have this stuff implemented and be ready for submission.

**Comment by IndrajeetPatil** [comment]
But that's a rather substantial change though. Shouldn't we wait to include it in the **next-to-next** release (so after a month or so from now)? 
It will also give us sufficient time to test it thoroughly. 

What do you think?

**Comment by strengejacke** [comment]
I'd like to have that feature for the next R workshop I'm giving by the end of Feb./beginning of March. :-)

**Comment by IndrajeetPatil** [comment]
Sigh, I wanted to update my ecosystem soon for my talk on the 18th. 

But I guess I will just start out by declaring that a lot of what I am presenting works only with the `GitHub` version, and not with the `CRAN` version of the package.

**Comment by strengejacke** [comment]
Are there any particular new changes that you're relying on?

**Comment by IndrajeetPatil** [comment]
Mainly the fact that there is now a new CI column in `parameters` + `insight` output.
Also, `ci.width` is now `conf.level` in `broom` convention in `insight`.

**Comment by strengejacke** [comment]
We've just been informed about this failing check:
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/parameters-00check.html

and that we need to address this. So submission can't be done before we resolved this issue. It's probably related to knitr.

**Comment by DominiqueMakowski** [comment]
Ah these are the "unused args" he's referring to

**Comment by DominiqueMakowski** [comment]
still not sure what does it mean nor how to fix though

**Comment by IndrajeetPatil** [comment]
It's the same issue as the following one and, from the look of it, there is not much we can do from our side to prevent this from happening:
https://stackoverflow.com/questions/50789125/how-to-get-an-rmarkdown-vignette-for-r-package-to-escape-cran-warnings-on-solari

We are already following the best practices (`rmarkdown` in `Suggests` + `knitr` as `VignetteBuilder`).

I will do some more digging, but we might ultimately have to raise an issue on `knitr`'s repo and ask for advice.

**Comment by strengejacke** [comment]
I would now add that vignette to RBuildIgnore, so it's not submitted to CRAN, but GitHub pages will include that vignette.

**Comment by mattansb** [comment]
> I would now add that vignette to RBuildIgnore, so it's not submitted to CRAN, but GitHub pages will include that vignette.

Maybe add all to the vignettes to RBuildIgnore and add a "see more" vignette for CRAN?

**Comment by strengejacke** [comment]
Yeah, I completely skip the vignettes folder, because there are several vignettes affected.

**Comment by strengejacke** [comment]
ok, insight on CRAN, parameters was requested to be updated soon, so I guess by next week we have the "core" easystats packages all working with R 3.4 and higher.

**Comment by IndrajeetPatil** [comment]
Will you be submitting `parameters` today as well? 
Because I need both `insight` and `parameters` before I can submit `statsExpressions` to `CRAN`.

**Comment by strengejacke** [comment]
Once all tests pass I'll submit.

**Comment by IndrajeetPatil** [comment]
Is `parameters` being processed by `CRAN`?

It would be good if it makes to `CRAN` by tomorrow morning/afternoon, so that I can have both of the packages there tomorrow; just in time for the talk 😅

**Comment by strengejacke** [comment]
No, not yet submitted. Found some issues in compare_paramters I'm currently fixing, and I'm finding a way how to best exclude vignettes.

**Comment by strengejacke** [comment]
Mac OS sucks. I seriously think about disabling tests on Mac in general as there's always a strange exception that cannot be caught. And maybe we should add a startup message to each package suggesting users to switch to Linux/Windows.

**Comment by vincentarelbundock** [comment]
Ha! I’m in the process of moving all my machines from Mac OS to Linux, so I empathize with the point, but that warning that data.table prints on OS X is pretty obnoxious 😅

**Comment by strengejacke** [comment]
There _must_ be a reason I'm not the first one with that startup-msg idea ;-)

**Comment by strengejacke** [comment]
ok, _parameters_ submitted. The rollback to 3.4 is almost completed for the easystats-suite.

**Comment by IndrajeetPatil** [comment]
> ok, parameters submitted

Was it rejected? I don't see it here: https://lockedata.github.io/cransays/articles/dashboard.html

**Comment by DominiqueMakowski** [comment]
indra be like:

![](https://media.giphy.com/media/tei52cyY5mroA/giphy.gif)

**Comment by strengejacke** [comment]
> Flavor: r-devel-windows-ix86+x86_64
Check: Overall checktime, Result: NOTE
  Overall checktime 15 min > 10 min

**Comment by IndrajeetPatil** [comment]
Huh, that's a bit surprising, no? How can the check time now be exceeding when we are skipping all the vignettes?!

**Comment by strengejacke** [comment]
Check time still ~12 min, and I got a note. I replied via email, expressing my surprise, especially against the background that we've removed all vignettes.

**Comment by IndrajeetPatil** [comment]
![giphy](https://user-images.githubusercontent.com/11330453/108218060-919aa000-7134-11eb-8484-35d9c24b5757.gif)

**Comment by strengejacke** [comment]
CRAN continues processing the package, though the run time is ~12 min. For my information, the pure running times of the examples are ~8 minutes, and this excludes installation times and others. Not sure why the time for checking examples increased that much, did anyone add examples that may freak out here? @mattansb @IndrajeetPatil @DominiqueMakowski ?

**Comment by IndrajeetPatil** [comment]
Nope, I didn't add any examples. 

Here are some possible examples we can skip on CRAN for now:
- `methods_rstanarm.R`
- `methods_cplm.R`
- `p_value_kenward.R`
- `methods_mclust.R`
- `methods_lme4.R`
- `methods_averaging.R`
- `methods_cgam.R`

I think that should reduce enough time to pass the incoming checks?

**Comment by DominiqueMakowski** [comment]
no idea what could be the cause 🤔

**Comment by mattansb** [comment]
I added an example of emmeans-bootstrap, but those take not sig-additional time to run (they dont run additional bootstraps).

**Comment by IndrajeetPatil** [comment]
@strengejacke With all the new skipped tests and examples, is the check time still above 10 minutes? Or you didn't resubmit yet?

**Comment by strengejacke** [comment]
Some example fail, because insight 0.13.0 is not available/compiled for all systems yet, so I might need to resubmit with insight (>= 0.13.0) in DESCRIPTION...

**Comment by IndrajeetPatil** [comment]
Examples were failing on `CRAN` servers? How is that possible?
The incoming checks are run only on `Windows` and `Debian`, and both of them would use `source` version `insight` (`0.13.0`), so the examples shouldn't be failing.  

Or you meant on Github-actions? In that case, these failures can be temporarily ignored.

**Comment by strengejacke** [comment]
> Thanks, we see with --run-donttest:

```
** running examples for arch 'x64' ... [15s] ERROR
Running examples in 'parameters-Ex.R' failed
The error most likely occurred in:

 > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
 > ### Name: compare_parameters
 > ### Title: Compare model parameters of multiple models
 > ### Aliases: compare_parameters compare_models
 >
 > ### ** Examples
 >
 > data(iris)
 > lm1 <- lm(Sepal.Length ~ Species, data = iris)
 > lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
 > lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
 > compare_parameters(lm1, lm2, lm3)
Error in insight::export_table(formatted_table, format = "text", footer 
= NULL,  :
   unused argument (empty_line = "-")
Calls: <Anonymous> -> print.compare_parameters -> cat
Execution halted
```

**Comment by IndrajeetPatil** [comment]
Strange.

So we will have to run the example conditionally?

```r
if (utils::packageVersion("insight") >= package_version("0.13.0")) {
...
}
```

**Comment by strengejacke** [comment]
I think `insight (>= 0.13.0)` in the DESCRIPTION should be enough, waiting for CRAN response on that.

**Comment by IndrajeetPatil** [comment]
I wonder if this has something to do with the release of `R 4.0.4`.

**Comment by IndrajeetPatil** [comment]
@strengejacke Have you seen this additional check we are failing? 

https://www.stats.ox.ac.uk/pub/bdr/donttest/parameters.out

**Comment by strengejacke** [comment]
Yes

**Comment by IndrajeetPatil** [comment]
Still no response from `CRAN`? 🔮 

I have started to get "bug" reports from users 😭

**Comment by strengejacke** [comment]
No, not yet. Will follow-up tomorrow.

**Comment by strengejacke** [comment]
Ok, re-submitted. 🤞 🤞

**Comment by strengejacke** [comment]
_parameters_ on CRAN

**Comment by vincentarelbundock** [comment]
Fantastic! Thanks again for all your work on these awesome packages!

**Comment by strengejacke** [comment]
Will submit insight update tomorrow that should fix the check-errors on Mac.

**Comment by strengejacke** [comment]
@IndrajeetPatil Have you updated statsExpressions already? I don't want to submit an update of insight, which (still) breaks statsExpressions ;-)

**Comment by IndrajeetPatil** [comment]
@strengejacke Yes, the updated `statsExpressions` is already on CRAN and I checked it again the GitHub version of `insight` and all tests pass. 

So, feel free to submit the updated version whenever you want.

**Comment by strengejacke** [comment]
_insight_ 0.13.1 on CRAN, which now hopefully fixes the Mac issues, so subsequent packages no longer have check errors.

**Comment by strengejacke** [comment]
@mattansb do you plan to submit effectsize in the near future? Then our rollback to 3.4 would be complete (and working).

**Comment by mattansb** [comment]
Hmm I wasn't planning on it just yet. But I can submit a quick fix if you'd like. (Was originally planning in a few weeks)

**Comment by strengejacke** [comment]
I don't mind, it's not urgent, but I think some easystats packages won't install on R 3.4 unless effectsize is updated.

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/easystats/easystats/issues/106
